In [590]:
# -*- coding: utf-8 -*-
"""
Created on Thu May 28 21:21:23 2020

@author: emanu

Project name: loading data from Mergnet
"""

import os
import pandas as pd
import pandas_datareader as pdr
from datetime import datetime as dt
import xlsxwriter
from datetime import date
from win32com.client import Dispatch


#setting viewing settings of pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#function to gather data from web source(for now its from file)
def get_data():
    
    #open file 
    global data_IncomeStatement
#     data_IncomeStatement = pd.read_excel('IncomeStatement_full.xlsx', header=None, parse_dates=True)
    data_IncomeStatement = pd.read_excel('IncomeStatement_quarters.xlsx', header=None, parse_dates=True)
    global data_BalanceSheet
    data_BalanceSheet = pd.read_excel('BalanceSheet_quarters.xlsx', header=None, parse_dates=True)
    data_BalanceSheet_full = data_BalanceSheet.copy()
    data_IncomeStatement_full = data_IncomeStatement.copy()
    data_IncomeStatement = data_IncomeStatement.loc[:,~(data_IncomeStatement.columns % 2 == 0)]
    data_BalanceSheet = data_BalanceSheet.loc[:,~(data_BalanceSheet.columns % 2 == 0)]
#reverse the order of the values columns to fit model
    df_Inc = data_IncomeStatement.copy()
    df_Inc = df_Inc.iloc[:,:1:-1]
    df_Inc = df_Inc.T.reset_index(drop=True).T
#     df_Inc.insert(0, 'Indicator', data_IncomeStatement.iloc[:][0])
    df_BalSheet = data_BalanceSheet.copy()
    global df_inc
    return df_Inc, df_BalSheet, data_IncomeStatement_full, data_BalanceSheet_full

df_Inc, df_BalSheet, data_IncomeStatement_full, data_BalanceSheet_full = get_data()

display (df_Inc.head(15), df_BalSheet.head(15))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,12/31/2005,04/01/2006,07/01/2006,12/30/2006,03/31/2007,06/30/2007,12/29/2007,03/29/2008,06/28/2008,12/27/2008,03/28/2009,06/27/2009,12/26/2009,03/27/2010,06/26/2010,12/25/2010,03/26/2011,06/25/2011,12/31/2011,03/31/2012,06/30/2012,12/29/2012,03/30/2013,06/29/2013,12/28/2013,03/29/2014,06/28/2014,12/27/2014,03/28/2015,06/27/2015,12/26/2015,03/26/2016,06/25/2016,12/31/2016,04/01/2017,07/01/2017,12/30/2017,03/31/2018,06/30/2018,12/29/2018,03/30/2019,06/29/2019,12/28/2019
11,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter,2nd Quarter,3rd Quarter,1st Quarter
12,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD
13,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited
14,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes

,1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,06/27/2020,03/28/2020,12/28/2019,06/29/2019,03/30/2019,12/29/2018,06/30/2018,03/31/2018,12/30/2017,07/01/2017,04/01/2017,12/31/2016,06/25/2016,03/26/2016,12/26/2015,06/27/2015,03/28/2015,12/27/2014,06/28/2014,03/29/2014,12/28/2013,06/29/2013,03/30/2013,12/29/2012,06/30/2012,03/31/2012,12/31/2011,06/25/2011,03/26/2011,12/25/2010,06/26/2010,03/27/2010,12/26/2009,06/27/2009,03/28/2009,12/27/2008,06/28/2008,03/29/2008,12/29/2007,06/30/2007,03/31/2007,12/30/2006,07/01/2006,04/01/2006,12/31/2005,06/25/2005,03/26/2005,12/25/2004,06/26/2004,03/27/2004,12/27/2003,06/28/2003,03/29/2003,12/28/2002,06/29/2002,03/30/2002,12/29/2001,06/30/2001,03/31/2001,12/30/2000,07/01/2000,04/01/2000,01/01/2000,06/26/1999,03/27/1999,12/26/1998,06/26/1998,03/27/1998,12/26/1997,06/27/1997,03/28/1997,12/27/1996,06/28/1996,03/29/1996,12/29/1995,06/30/1995,03/31/1995,12/31/1994,07/01/1994,04/01/1994,12/31/1993,06/25/1993,03/26/1993,12/25/1992,06/26/1992,03/27/1992,12/27/1991,06/30/1991,03/29/1991
11,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter,1st Quarter,3rd Quarter,2nd Quarter
12,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD
13,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Unaudited,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
14,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes

In [591]:
data_IncomeStatement_full

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Powered by Clearbit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Apple Inc (NMS: AAPL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Exchange rate used is that of the Year End rep...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,As Reported Quarterly Income Statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Report Date,06/27/2020,NaN,03/28/2020,NaN,12/28/2019,NaN,06/29/2019,NaN,03/30/2019,NaN,12/29/2018,NaN,06/30/2018,NaN,03/31/2018,NaN,12/30/2017,NaN,07/01/2017,NaN,04/01/2017,NaN,12/31/2016,NaN,06/25/2016,NaN,03/26/2016,NaN,12/26/2015,NaN,06/27/2015,NaN,03/28/2015,NaN,12/27/2014,NaN,06/28/2014,NaN,03/29/2014,NaN,12/28/2013,NaN,06/29/2013,NaN,03/30/2013,NaN,12/29/2012,NaN,06/30/2012,NaN,03/31/2012,NaN,12/31/2011,NaN,06/25/2011,NaN,03/26/2011,NaN,12/25/2010,NaN,06/26/2010,NaN,03/27/2010,NaN,12/26/2009,NaN,06/27/2009,NaN,03/28/2009,NaN,12/27/2008,NaN,06/28/2008,NaN,03/29/2008,NaN,12/29/2007,NaN,06/30/2007,NaN,03/31/2007,NaN,12/30/2006,NaN,07/01/2006,NaN,04/01/2006,NaN,12/31/2005
11,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter
12,Currency,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD
13,Audit Status,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited
14,Consolidated,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes
15,Scale,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands
16,Net sales - products,46529000,NaN,44965000,NaN,79104000,NaN,42354000,NaN,46565000,NaN,73435000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
17,Net sales - services,13156000,NaN,13348000,NaN,12715000,NaN,11455000,NaN,11450000,NaN,10875000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
18,Total net sales,59685000,NaN,58313000,NaN,91819000,NaN,53809000,NaN,58015000,NaN,84310000,NaN,53265000,NaN,61137000,NaN,88293000,NaN,45408000,NaN,52896000,NaN,78351000,NaN,42358000,NaN,50557000,NaN,75872000,NaN,49605000,NaN,58010000,NaN,74599000,NaN,37432000,NaN,45646000,NaN,57594000,NaN,35323000,NaN,43603000,NaN,54512000,NaN,35023000,NaN,39186000,NaN,46333000,NaN,28571000,NaN,24667000,NaN,26741000,NaN,15700000,NaN,13499000,NaN,15683000,NaN,8337000,NaN,8163000,NaN,10167000,NaN,7464000,NaN,7512000,NaN,9608000,NaN,5410000,NaN,5264000,NaN,7115000,NaN,4370000,NaN,4359000,NaN,5749000
19,Cost of sales - products,32693000,NaN,31321000,NaN,52075000,NaN,29473000,NaN,32047000,NaN,48238000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
20,Cost of sales - services,4312000,NaN,4622000,NaN,4527000,NaN,4109000,NaN,4147000,NaN,4041000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
21,Total cost of sales,37005000,NaN,35943000,NaN,56602000,NaN,33582000,NaN,36194000,NaN,52279000,NaN,32844000,NaN,37715000,NaN,54381000,NaN,27920000,NaN,32305000,NaN,48175000,NaN,26252000,NaN,30636000,NaN,45449000,NaN,29924000,NaN,34354000,NaN,44858000,NaN,22697000,NaN,27699000,NaN,35748000,NaN,22299000,NaN,27254000,NaN,33452000,NaN,20029000,NaN,20622000,NaN,25630000,NaN,16649000,NaN,14449000,NaN,16443000,NaN,9564000,NaN,7874000,NaN,9272000,NaN,5314000,NaN,5192000,NaN,6635000,NaN,4864000,NaN,5038000,NaN,6276000,NaN,3415000,NaN,3415000,NaN,4895000,NaN,3045000,NaN,3062000,NaN,4185000
22,Gross margin,22680000,NaN,22370000,NaN,35217000,NaN,20227000,NaN,21821000,NaN,32031000,NaN,20421000,NaN,23422000,NaN,33912000,NaN,17488000,NaN,20591000,NaN,30176000,NaN,16106000,NaN,19921000,NaN,30423000,NaN,19681000,NaN,23656000,NaN,29741000,NaN,14735000,NaN,17947000,NaN,21846000,NaN,13024000,NaN,16349000,NaN,21060000,NaN,14994000,NaN,18564000,NaN,20703000,NaN,11922000,NaN,10218000,NaN,10298000,NaN,6136000,NaN,5625000,NaN,6411000,NaN,3023000,NaN,2971000,NaN,3532000,NaN,2600000,NaN,2474000,NaN,3332000,NaN,1995000,NaN,1849000,NaN,2220000,NaN,1325000,NaN,1297000,NaN,1564000
23,Research & development expenses,4758000,NaN,4565000,NaN,4451000,NaN,4257000,NaN,3948000,NaN,3902000,NaN,3701000,NaN,3378000,NaN,3407000,NaN,2937000,NaN,2776000,NaN,2871000,NaN,2560000,NaN,2511000,NaN,2404000,NaN,2034000,NaN,1918000,NaN,1895000,NaN,1603000,NaN,1422000,NaN,1330000,NaN,1178000,NaN,1119000,NaN,1010000,NaN,876000,NaN,841000,NaN,758000,NaN,628000,NaN,581000,NaN,575000,NaN,464000,NaN,426000,NaN,398000,NaN,341000,NaN,319000,NaN,315000,NaN,292000,NaN,273000,NaN,246000,NaN,208000,NaN,183000,NaN,184000,NaN,175000,NaN,176000,NaN,182000
24,"Selling, general & administrative expenses",4831000,NaN,4952000,NaN,5197000,NaN,4426000,NaN,4458000,NaN,4783000,NaN,4108000,NaN,4150000,NaN,4231000,NaN,3783000,NaN,3718000,NaN,3946000,NaN,3441000,NaN,3423000,NaN,3848000,NaN,3564000,NaN,3460000,NaN,3600000,NaN,2850000,NaN,2932000,NaN,3053000,NaN,2645000,NaN,2672000,NaN,2840000,NaN,2545000,NaN,2339000,NaN,2605000,NaN,1915000,NaN,1763000,NaN,1896000,NaN,1438000,NaN,1220000,NaN,1288000,NaN,1010000,NaN,985000,NaN,1091000,NaN,916000,NaN,886000,NaN,960000,NaN,746000,NaN,680000,NaN,714000,NaN,584000,NaN,592000,NaN,632000
25,Total operating expenses,9589000,NaN,9517000,NaN,9648000,NaN,8683000,NaN,8406000,NaN,8685000,NaN,7809000,NaN,7528000,NaN,7638000,NaN,6720000,NaN,6494000,NaN,6817000,NaN,6001000,NaN,5934000,NaN,6252000,NaN,5598000,NaN,5378000,NaN,5495000,NaN,4453000,NaN,4354000,NaN,4383000,NaN,3823000,NaN,3791000,NaN,3850000,NaN,3421000,NaN,3180000,NaN,3363000,NaN,2543000,NaN,2344000,NaN,2471000,NaN,1902000,NaN,1646000,NaN,1686000,NaN,1351000,NaN,1304000,NaN,1406000,NaN,1208000,NaN,1159000,NaN,1206000,NaN,954000,NaN,863000,NaN,898000,NaN,759000,NaN,768000,NaN,814000
26,Operating income (loss),13091000,NaN,12853000,NaN,25569000,NaN,11544000,NaN,13415000,NaN,23346000,NaN,12612000,NaN,15894000,NaN,26274000,NaN,10768000,NaN,14097000,NaN,23359000,NaN,10105000,NaN,13987000,NaN,24171000,NaN,14083000,NaN,18278000,NaN,24246000,NaN,10282000,NaN,13593000,NaN,17463000,NaN,9201000,NaN,12558000,NaN,17210000,NaN,11573000,NaN,15384000,NaN,17340000,NaN,9379000,NaN,7874000,NaN,7827000,NaN,4234000,NaN,3979000,NaN,4725000,NaN,1672000,NaN,1667000,NaN,2126000,NaN,1392000,NaN,1315000,NaN,2126000,NaN,1041000,NaN,986000,NaN,1322000,NaN,566000,NaN,529000,NaN,750000
27,Interest & dividend income,901000,NaN,1049000,NaN,1045000,NaN,1190000,NaN,1358000,NaN,1307000,NaN,1418000,NaN,1505000,NaN,1452000,NaN,1327000,NaN,1282000,NaN,1224000,NaN,1036000,NaN,986000,NaN,941000,NaN,766000,NaN,675000,NaN,654000,NaN,439000,NaN,410000,NaN,427000,NaN,-,NaN,420000,NaN,421000,NaN,-,NaN,254000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
28,Interest expense,697000,NaN,757000,NaN,785000,NaN,866000,NaN,1010000,NaN,890000,NaN,846000,NaN,792000,NaN,734000,NaN,602000,NaN,530000,NaN,525000,NaN,409000,NaN,321000,NaN,276000,NaN,201000,NaN,163000,NaN,131000,NaN,100000,NaN,85000,NaN,84000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
29,"Other expense, net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,185000,NaN,-,NaN,-,NaN,263000,NaN,-,NaN,-,NaN,175000,NaN,-,NaN,-,NaN,137000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,13000,NaN,-,NaN,7000,NaN,4000,NaN,11000,NaN,7000
30,Interest income,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,168000,NaN,-,NaN,133000,NaN,99000,NaN,87000,NaN,88000
31,"Other income (expense), net",-158000,NaN,-10000,NaN,89000,NaN,43000,NaN,30000,NaN,143000,NaN,100000,NaN,-439000,NaN,38000,NaN,-,NaN,-165000,NaN,122000,NaN,-,NaN,-510000,NaN,-263000,NaN,-,NaN,-226000,NaN,-353000,NaN,-,NaN,-100000,NaN,-97000,NaN,-,NaN,-73000,NaN,41000,NaN,-,NaN,-106000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
32,"Interest & other income (expense), net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,81000
33,"Other income (expense), net",46000,NaN,282000,NaN,349000,NaN,367000,NaN,378000,NaN,560000,NaN,672000,NaN,274000,NaN,756000,NaN,540000,NaN,587000,NaN,821000,NaN,364000,NaN,155000,NaN,402000,NaN,390000,NaN,286000,NaN,170000,NaN,202000,NaN,225000,NaN,246000,NaN,-,NaN,347000,NaN,462000,NaN,-,NaN,148000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,155000,NaN,-,NaN,126000,NaN,95000,NaN,76000,NaN,-
34,"Other income (expense), net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,234000,NaN,-,NaN,-,NaN,288000,NaN,-,NaN,137000,NaN,172000,NaN,26000,NaN,136000,NaN,58000,NaN,50000,NaN,33000,NaN,60000,NaN,63000,NaN,158000,NaN,118000,NaN,162000,NaN,200000,NaN,-,NaN,148000,NaN,-,NaN,-,NaN,-,NaN,-
35,Income (loss) before provision for income taxes,13137000,NaN,13135000,NaN,25918000,NaN,11911000,NaN,13793000,NaN,23906000,NaN,13284000,NaN,16168000,NaN,27030000,NaN,11308000,NaN,14684000,NaN,24180000,NaN,10469000,NaN,14142000,NaN,24573000,NaN,14473000,NaN,18564000,NaN,24416000,NaN,10484000,NaN,13818000,NaN,17709000,NaN,9435000,NaN,12905000,NaN,17672000,NaN,11861000,NaN,15532000,NaN,17477000,NaN,9551000,NaN,7900000,NaN,7963000,NaN,4292000,NaN,4029000,NaN,4758000,NaN,1732000,NaN,1730000,NaN,2284000,NaN,1510000,NaN,1477000,NaN,2326000,NaN,1196000,NaN,1134000,NaN,1448000,NaN,661000,NaN,605000,NaN,831000
36,Provision for (benefit from) income taxes,1884000,NaN,1886000,NaN,3682000,NaN,1867000,NaN,2232000,NaN,3941000,NaN,1765000,NaN,2346000,NaN,6965000,NaN,2591000,NaN,3655000,NaN,6289000,NaN,2673000,NaN,3626000,NaN,6212000,NaN,3796000,NaN,4995000,NaN,6392000,NaN,2736000,NaN,3595000,NaN,4637000,NaN,2535000,NaN,3358000,NaN,4594000,NaN,3037000,NaN,3910000,NaN,4413000,NaN,2243000,NaN,1913000,NaN,1959000,NaN,1039000,NaN,955000,NaN,1380000,NaN,503000,NaN,525000,NaN,679000,NaN,438000,NaN,432000,NaN,745000,NaN,378000,NaN,364000,NaN,444000,NaN,189000,NaN,195000,NaN,266000
37,Net income (loss),11253000,NaN,11249000,NaN,22236000,NaN,10044000,NaN,11561000,NaN,19965000,NaN,11519000,NaN,13822000,NaN,20065000,NaN,8717000,NaN,11029000,NaN,17891000,NaN,7796000,NaN,10516000,NaN,18361000,NaN,10677000,NaN,13569000,NaN,18024000,NaN,7748000,NaN,10223000,NaN,13072000,NaN,6900000,NaN,9547000,NaN,13078000,NaN,8824000,NaN,11622000,NaN,13064000,NaN,7308000,NaN,5987000,NaN,6004000,NaN,3253000,NaN,3074000,NaN,3378000,NaN,1229000,NaN,1205000,NaN,1605000,NaN,1072000,NaN,1045000,NaN,1581000,NaN,818000,NaN,770000,NaN,1004000,NaN,472000,NaN,410000,NaN,565000
38,Weighted average shares outstanding - basic,17250292,NaN,17440404,NaN,17660160,NaN,18282532,NaN,18696284,NaN,18943280,NaN,19528668,NaN,20099508,NaN,20451508,NaN,20780352,NaN,20903164,NaN,21194644,NaN,21772232,NaN,22057524,NaN,22235720,NaN,22919544,NaN,23175196,NaN,23372328,NaN,24050540,NaN,24493196,NaN,25090016,NaN,25721304,NaN,26309612,NaN,26289648,NaN,26224688,NaN,26140296,NaN,26069148,NaN,25931024,NaN,25849488,NaN,25740232,NaN,25541516,NaN,25411344,NaN,25299176,NaN,25023936,NaN,24953040,NaN,24895976,NaN,24744664,NaN,24627288,NaN,24524080,NaN,24270568,NaN,24164084,NaN,24015348,NaN,23838500,NaN,23545480,NaN,23261868
39,Weighted average shares outstanding - diluted,17419152,NaN,17618764,NaN,17818416,NaN,18405520,NaN,18802584,NaN,19093008,NaN,19706436,NaN,20273972,NaN,20631148,NaN,20933996,NaN,21046752,NaN,21311980,NaN,21891124,NaN,22163544,NaN,22376508,NaN,23092396,NaN,23339432,NaN,23527212,NaN,24206844,NaN,24626784,NaN,25240656,NaN,25879420,NaN,26488980,NaN,26522076,NaN,26517652,NaN,26457004,NaN,26364016,NaN,26258680,NaN,26206432,NaN,26128312,NaN,25966108,NaN,25840584,NaN,25753924,NaN,25456480,NaN,25283804,NaN,25241832,NaN,25288676,NaN,25181212,NaN,25201512,NaN,24938788,NaN,24826284,NaN,24732316,NaN,24538304,NaN,24599036,NaN,24477796
40,Year end shares outstanding,17135756,NaN,17295948,NaN,17539836,NaN,18125580,NaN,18429136,NaN,18919212,NaN,19371668,NaN,19773128,NaN,20326604,NaN,20679128,NaN,20823260,NaN,21021692,NaN,21572660,NaN,21913784,NaN,22177948,NaN,22821600,NaN,23049112,NaN,23305676,NaN,23956684,NaN,24128860,NaN,24988516,NaN,25436376,NaN,26322632,NaN,26291244,NaN,26243448,NaN,26179496,NaN,26101992,NaN,2.59533e+07,NaN,2.58909e+07,NaN,2.5789e+07,NaN,2.55775e+07,NaN,2.54698e+07,NaN,2.53759e+07,NaN,2.50806e+07,NaN,2.49735e+07,NaN,2.49316e+07,NaN,2.48009e+07,NaN,2.46801e+07,NaN,2.46016e+07,NaN,2.43365e+07,NaN,2.42114e+07,NaN,2.40862e+07,NaN,2.38837e+07,NaN,2.37773e+07,NaN,2.36773e+07
41,Net earnings (loss) per share - basic,0.653,NaN,0.645,NaN,1.26,NaN,0.55,NaN,0.618,NaN,1.055,NaN,0.59,NaN,0.688,NaN,0.98,NaN,0.42,NaN,0.528,NaN,0.845,NaN,0.358,NaN,0.478,NaN,0.825,NaN,0.465,NaN,0.585,NaN,0.77,NaN,0.323,NaN,0.418,NaN,0.521,NaN,0.268,NaN,0.363,NaN,0.498,NaN,0.336,NaN,0.445,NaN,0.501,NaN,0.282,NaN,0.232,NaN,0.233,NaN,0.128,NaN,0.121,NaN,0.134,NaN,0.049,NaN,0.048,NaN,0.065,NaN,0.043,NaN,0.043,NaN,0.065,NaN,0.034,NaN,0.032,NaN,0.042,NaN,0.02,NaN,0.018,NaN,0.024

In [592]:
type(data_IncomeStatement.columns)

pandas.core.indexes.numeric.Int64Index

In [593]:
os.getcwd()

'C:\\Users\\User\\github\\Guided-Capstone'

In [594]:
#run once decorator function
def run_once(f):
    def wrapper(*args, **kwargs):
        if not wrapper.has_run():
            return f(*args, **kwargs)
    wrapper.has_run = False
    return wrapper

In [595]:
# Autofit columns
#==================================================
#Just place whatever excel file that
#is needed in the same directory as main
#and those files will automatically be autofitted
# *this is not necessary so will only uncomment if 
# needed
#==================================================
#@run_once  #call run_once decorator
def auto_fill(file, worksheet_num):

    excel = Dispatch('Excel.Application')
    wb = excel.Workbooks.Open('{}\\{}'.format(os.getcwd(), file))
    excel.Worksheets(worksheet_num).Activate()
    excel.ActiveSheet.Columns.AutoFit()

#save the file
    wb.Save()
    wb.Close(True)
#already_fitted_files = []
#list name of all xlsx files in current directory
xlsx_file_names = []
for arr in os.listdir('.'):
    if arr.endswith('.xlsx'):
        xlsx_file_names.append(arr)
    else:
        pass
    
print(xlsx_file_names)
# with open('already_fitted.xlsx', 'w') as af:
#     print(af)
#     for file_name in xlsx_file_names:
#         print(file_name)
#         if file_name not in af:
#             file_name.to_excel('already_fitted.xlsx')
            
#    [file_name.to_excel('already_fitted.xlsx') for file_name in xlsx_file_names if file_name not in af]
        

# [auto_fill('{}'.format(element), 1) for element in xlsx_file_names]
print('✓All excel files have been autofitted')

['asreported.xlsx', 'asreported_full.xlsx', 'Balancesheet.xlsx', 'BalanceSheet_quarters.xlsx', 'IncomeStatement_full.xlsx', 'IncomeStatement_quarters.xlsx', 'middle_list.xlsx', 'Valuation_Ranges.xlsx', '~$asreported_full.xlsx', '~$IncomeStatement_quarters.xlsx', '~$Valuation_Ranges.xlsx']
✓All excel files have been autofitted

In [596]:
#open file and autofit function
def open_file(file, worksheet_num):

    excel = Dispatch('Excel.Application')
    wb = excel.Workbooks.Open('{}\\{}'.format(os.getcwd(), file))
    excel.Worksheets(worksheet_num).Activate()
#     excel.ActiveSheet.Columns.AutoFit()
    
    return wb

In [597]:
#not necessary
# date1 = pd.merge(df_Inc.iloc[10][0:9:2], df_Inc.iloc[10][9:19], how = 'outer')
# date1.columns = date1.iloc[0]
# date1.drop(5, axis = 0, inplace = True)
# date1.drop(0, axis = 0, inplace = True)
# net_rev = date1.rename(columns={"Report Date": "Date"}, inplace = True)
# date1

In [598]:
#main data calling and cleaning function
#returns middle list containing years 
#needs more work in data extraction from Valuation DF
# def insert_data_model():
#     #define empty list for dataframe
    
#     middle_list = []
    
#     #extract and clean info from data DataFrame 
    
#     #middle_list.append([df_Inc.iloc[[10, 15, 55, 58]]])
    
#     #open model file
#     valuation_model = pd.DataFrame(pd.read_excel('Valuation_Ranges.xlsx'))
# #     valuation_model = pd.DataFrame(valuation_model)
#     print(valuation_model.iloc[4])
#     middle_list.append([data_BalanceSheet.iloc[[98]]])
#     middle_list = pd.DataFrame(middle_list)
#     middle_list.to_excel('middle_list.xlsx')
#     return middle_list
# insert_data_model()

In [599]:
# pd.DataFrame.from_records([s.to_dict() for s in val_range])

In [600]:
#define rows that we need for our valuation model
Important_titles = [4, 6, 7, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25, 26, 27, 28, 
                   30, 31, 32, 33, 36, 37, 38, 39, 40, 41, 44, 45, 47, 48, 49, 50, 51, 52, 54,
                    55, 56, 59, 60, 61]
important_titles = [elem + 1 for elem in Important_titles]

In [601]:
#lines that are important to us in a list format --> so we can build our dataframe based on them
print(important_titles)

[5, 7, 8, 11, 12, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 45, 46, 48, 49, 50, 51, 52, 53, 55, 56, 57, 60, 61, 62]

In [602]:
#figure out earliest date data is availible for filings
dates = pd.DataFrame(pd.to_datetime(df_Inc.iloc[10]))
start_date = min(dates[10].dt.year)
start_date

2005

In [603]:
# gather data to fill into val_mod DataFrame
# THIS IS WHERE THE MAIN CODE STARTS
import pandas_datareader as pdr
from datetime import datetime
get_stock_info = 'AAPL'
 

# get_stock_info = input('Please enter the name of the stock: ')
stock_data = pdr.get_data_yahoo(symbols=get_stock_info, start=start_date, 
                                end=datetime.today())
stock_data.head(10)

                High       Low      Open     Close        Volume  Adj Close
Date
2005-01-03  1.162679  1.117857  1.156786  1.130179  6.919920e+08   0.967032
2005-01-04  1.169107  1.124464  1.139107  1.141786  1.096810e+09   0.976964
2005-01-05  1.165179  1.143750  1.151071  1.151786  6.804336e+08   0.985521
2005-01-06  1.159107  1.130893  1.154821  1.152679  7.055552e+08   0.986284
2005-01-07  1.243393  1.156250  1.160714  1.236607  2.227450e+09   1.058097
2005-01-10  1.262500  1.212143  1.246964  1.231429  1.725310e+09   1.053666
2005-01-11  1.234821  1.145357  1.218750  1.152857  2.611627e+09   0.986437
2005-01-12  1.176786  1.130357  1.168750  1.168929  1.919702e+09   1.000188
2005-01-13  1.328929  1.245179  1.316250  1.246429  3.164717e+09   1.066501
2005-01-14  1.280714  1.235536  1.254464  1.253571  1.770742e+09   1.072613

In [604]:
stock_data.index

DatetimeIndex(['2005-01-03', '2005-01-04', '2005-01-05', '2005-01-06',
               '2005-01-07', '2005-01-10', '2005-01-11', '2005-01-12',
               '2005-01-13', '2005-01-14',
               ...
               '2020-11-13', '2020-11-16', '2020-11-17', '2020-11-18',
               '2020-11-19', '2020-11-20', '2020-11-23', '2020-11-24',
               '2020-11-25', '2020-11-27'],
              dtype='datetime64[ns]', name='Date', length=4005, freq=None)

In [605]:
# stock_data.head(50)
df11 = stock_data.copy()
df11.reset_index(inplace = True)
df11.head()

        Date      High       Low      Open     Close        Volume  Adj Close
0 2005-01-03  1.162679  1.117857  1.156786  1.130179  6.919920e+08   0.967032
1 2005-01-04  1.169107  1.124464  1.139107  1.141786  1.096810e+09   0.976964
2 2005-01-05  1.165179  1.143750  1.151071  1.151786  6.804336e+08   0.985521
3 2005-01-06  1.159107  1.130893  1.154821  1.152679  7.055552e+08   0.986284
4 2005-01-07  1.243393  1.156250  1.160714  1.236607  2.227450e+09   1.058097

In [606]:
df11['Date'] = pd.to_datetime(df11['Date'])
# df11.info()
# df11['Quarters'] = df11['Date'].dt.quarter
# df11.head()

In [607]:
# Getting year and month from Date column
df12 = df11.copy()
# Define years and month and insert into main DataFrame
years = pd.DatetimeIndex(df11['Date']).year
month = pd.DatetimeIndex(df11['Date']).month
quarters = df12['Date'].dt.quarter

df12.insert(1, "Year", years)
df12.insert(2, "Month", month)
df12.insert(3, "Quarter", quarters)

df12.head(15)
# pd.merge(pd.DataFrame(df11['Date'], df11_year), pd.DataFrame(df11['Date'], df11_month), on = 'Date', how = 'outer')

,Date,Year,Month,Quarter,High,Low,Open,Close,Volume,Adj Close
0,2005-01-03,2005,1,1,1.162679,1.117857,1.156786,1.130179,6.919920e+08,0.967032
1,2005-01-04,2005,1,1,1.169107,1.124464,1.139107,1.141786,1.096810e+09,0.976964
2,2005-01-05,2005,1,1,1.165179,1.143750,1.151071,1.151786,6.804336e+08,0.985521
3,2005-01-06,2005,1,1,1.159107,1.130893,1.154821,1.152679,7.055552e+08,0.986284
4,2005-01-07,2005,1,1,1.243393,1.156250,1.160714,1.236607,2.227450e+09,1.058097
5,2005-01-10,2005,1,1,1.262500,1.212143,1.246964,1.231429,1.725310e+09,1.053666
6,2005-01-11,2005,1,1,1.234821,1.145357,1.218750,1.152857,2.611627e+09,0.986437
7,2005-01-12,2005,1,1,1.176786,1.130357,1.168750,1.168929,1.919702e+09,1.000188
8,2005-01-13,2005,1,1,1.328929,1.245179,1.316250,1.246429,3.164717e+09,1.066501
9,2005-01-14,2005,1,1,1.280714,1.235536,1.254464,1.253571,1.770742e+09,1.072613
10,2005-01-18,2005,1,1,1.262500,1.209821,1.247321,1.261607,1.006460e+09,1.079488
11,2005-01-19,2005,1,1,1.276071,1.245536,1.258750,1.247857,7.518952e+08,1.067723
12,2005-01-20,2005,1,1,1.272679,1.240536,1.243750,1.258214,9.149224e+08,1.076585
13,2005-01-21,2005,1,1,1.278571,1.250000,1.273393,1.258750,9.113328e+08,1.077043
14,2005-01-24,2005,1,1,1.281786,1.259821,1.267500,1.263571,8.416296e+08,1.081169

In [608]:
dec_df = df12

In [609]:
display(dec_df.head())

,Date,Year,Month,Quarter,High,Low,Open,Close,Volume,Adj Close
0,2005-01-03,2005,1,1,1.162679,1.117857,1.156786,1.130179,6.919920e+08,0.967032
1,2005-01-04,2005,1,1,1.169107,1.124464,1.139107,1.141786,1.096810e+09,0.976964
2,2005-01-05,2005,1,1,1.165179,1.143750,1.151071,1.151786,6.804336e+08,0.985521
3,2005-01-06,2005,1,1,1.159107,1.130893,1.154821,1.152679,7.055552e+08,0.986284
4,2005-01-07,2005,1,1,1.243393,1.156250,1.160714,1.236607,2.227450e+09,1.058097

In [610]:
# Getting price based on quarters (Now we need to devide DataFrame into Years and Quarters for further processing)
dec_df13 = dec_df.pivot_table(index=['Year', 'Quarter'], values=['Close', 'High', 'Low'], aggfunc='mean')
dec_df13.head()

                 Close      High       Low
Year Quarter
2005 1        1.411996  1.433908  1.390404
     2        1.352740  1.375603  1.332132
     3        1.632829  1.650273  1.608292
     4        2.267874  2.295085  2.232783
2006 1        2.505685  2.559983  2.467074

In [611]:
IncomeStatement_Quarterly = pd.read_excel('IncomeStatement_quarters.xlsx')
IncomeStatement_Quarterly

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Powered by Clearbit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Apple Inc (NMS: AAPL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Exchange rate used is that of the Year End rep...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,As Reported Quarterly Income Statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Report Date,06/27/2020,NaN,03/28/2020,NaN,12/28/2019,NaN,06/29/2019,NaN,03/30/2019,NaN,12/29/2018,NaN,06/30/2018,NaN,03/31/2018,NaN,12/30/2017,NaN,07/01/2017,NaN,04/01/2017,NaN,12/31/2016,NaN,06/25/2016,NaN,03/26/2016,NaN,12/26/2015,NaN,06/27/2015,NaN,03/28/2015,NaN,12/27/2014,NaN,06/28/2014,NaN,03/29/2014,NaN,12/28/2013,NaN,06/29/2013,NaN,03/30/2013,NaN,12/29/2012,NaN,06/30/2012,NaN,03/31/2012,NaN,12/31/2011,NaN,06/25/2011,NaN,03/26/2011,NaN,12/25/2010,NaN,06/26/2010,NaN,03/27/2010,NaN,12/26/2009,NaN,06/27/2009,NaN,03/28/2009,NaN,12/27/2008,NaN,06/28/2008,NaN,03/29/2008,NaN,12/29/2007,NaN,06/30/2007,NaN,03/31/2007,NaN,12/30/2006,NaN,07/01/2006,NaN,04/01/2006,NaN,12/31/2005
10,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter
11,Currency,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD
12,Audit Status,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited
13,Consolidated,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes
14,Scale,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands
15,Net sales - products,46529000,NaN,44965000,NaN,79104000,NaN,42354000,NaN,46565000,NaN,73435000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
16,Net sales - services,13156000,NaN,13348000,NaN,12715000,NaN,11455000,NaN,11450000,NaN,10875000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
17,Total net sales,59685000,NaN,58313000,NaN,91819000,NaN,53809000,NaN,58015000,NaN,84310000,NaN,53265000,NaN,61137000,NaN,88293000,NaN,45408000,NaN,52896000,NaN,78351000,NaN,42358000,NaN,50557000,NaN,75872000,NaN,49605000,NaN,58010000,NaN,74599000,NaN,37432000,NaN,45646000,NaN,57594000,NaN,35323000,NaN,43603000,NaN,54512000,NaN,35023000,NaN,39186000,NaN,46333000,NaN,28571000,NaN,24667000,NaN,26741000,NaN,15700000,NaN,13499000,NaN,15683000,NaN,8337000,NaN,8163000,NaN,10167000,NaN,7464000,NaN,7512000,NaN,9608000,NaN,5410000,NaN,5264000,NaN,7115000,NaN,4370000,NaN,4359000,NaN,5749000
18,Cost of sales - products,32693000,NaN,31321000,NaN,52075000,NaN,29473000,NaN,32047000,NaN,48238000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
19,Cost of sales - services,4312000,NaN,4622000,NaN,4527000,NaN,4109000,NaN,4147000,NaN,4041000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
20,Total cost of sales,37005000,NaN,35943000,NaN,56602000,NaN,33582000,NaN,36194000,NaN,52279000,NaN,32844000,NaN,37715000,NaN,54381000,NaN,27920000,NaN,32305000,NaN,48175000,NaN,26252000,NaN,30636000,NaN,45449000,NaN,29924000,NaN,34354000,NaN,44858000,NaN,22697000,NaN,27699000,NaN,35748000,NaN,22299000,NaN,27254000,NaN,33452000,NaN,20029000,NaN,20622000,NaN,25630000,NaN,16649000,NaN,14449000,NaN,16443000,NaN,9564000,NaN,7874000,NaN,9272000,NaN,5314000,NaN,5192000,NaN,6635000,NaN,4864000,NaN,5038000,NaN,6276000,NaN,3415000,NaN,3415000,NaN,4895000,NaN,3045000,NaN,3062000,NaN,4185000
21,Gross margin,22680000,NaN,22370000,NaN,35217000,NaN,20227000,NaN,21821000,NaN,32031000,NaN,20421000,NaN,23422000,NaN,33912000,NaN,17488000,NaN,20591000,NaN,30176000,NaN,16106000,NaN,19921000,NaN,30423000,NaN,19681000,NaN,23656000,NaN,29741000,NaN,14735000,NaN,17947000,NaN,21846000,NaN,13024000,NaN,16349000,NaN,21060000,NaN,14994000,NaN,18564000,NaN,20703000,NaN,11922000,NaN,10218000,NaN,10298000,NaN,6136000,NaN,5625000,NaN,6411000,NaN,3023000,NaN,2971000,NaN,3532000,NaN,2600000,NaN,2474000,NaN,3332000,NaN,1995000,NaN,1849000,NaN,2220000,NaN,1325000,NaN,1297000,NaN,1564000
22,Research & development expenses,4758000,NaN,4565000,NaN,4451000,NaN,4257000,NaN,3948000,NaN,3902000,NaN,3701000,NaN,3378000,NaN,3407000,NaN,2937000,NaN,2776000,NaN,2871000,NaN,2560000,NaN,2511000,NaN,2404000,NaN,2034000,NaN,1918000,NaN,1895000,NaN,1603000,NaN,1422000,NaN,1330000,NaN,1178000,NaN,1119000,NaN,1010000,NaN,876000,NaN,841000,NaN,758000,NaN,628000,NaN,581000,NaN,575000,NaN,464000,NaN,426000,NaN,398000,NaN,341000,NaN,319000,NaN,315000,NaN,292000,NaN,273000,NaN,246000,NaN,208000,NaN,183000,NaN,184000,NaN,175000,NaN,176000,NaN,182000
23,"Selling, general & administrative expenses",4831000,NaN,4952000,NaN,5197000,NaN,4426000,NaN,4458000,NaN,4783000,NaN,4108000,NaN,4150000,NaN,4231000,NaN,3783000,NaN,3718000,NaN,3946000,NaN,3441000,NaN,3423000,NaN,3848000,NaN,3564000,NaN,3460000,NaN,3600000,NaN,2850000,NaN,2932000,NaN,3053000,NaN,2645000,NaN,2672000,NaN,2840000,NaN,2545000,NaN,2339000,NaN,2605000,NaN,1915000,NaN,1763000,NaN,1896000,NaN,1438000,NaN,1220000,NaN,1288000,NaN,1010000,NaN,985000,NaN,1091000,NaN,916000,NaN,886000,NaN,960000,NaN,746000,NaN,680000,NaN,714000,NaN,584000,NaN,592000,NaN,632000
24,Total operating expenses,9589000,NaN,9517000,NaN,9648000,NaN,8683000,NaN,8406000,NaN,8685000,NaN,7809000,NaN,7528000,NaN,7638000,NaN,6720000,NaN,6494000,NaN,6817000,NaN,6001000,NaN,5934000,NaN,6252000,NaN,5598000,NaN,5378000,NaN,5495000,NaN,4453000,NaN,4354000,NaN,4383000,NaN,3823000,NaN,3791000,NaN,3850000,NaN,3421000,NaN,3180000,NaN,3363000,NaN,2543000,NaN,2344000,NaN,2471000,NaN,1902000,NaN,1646000,NaN,1686000,NaN,1351000,NaN,1304000,NaN,1406000,NaN,1208000,NaN,1159000,NaN,1206000,NaN,954000,NaN,863000,NaN,898000,NaN,759000,NaN,768000,NaN,814000
25,Operating income (loss),13091000,NaN,12853000,NaN,25569000,NaN,11544000,NaN,13415000,NaN,23346000,NaN,12612000,NaN,15894000,NaN,26274000,NaN,10768000,NaN,14097000,NaN,23359000,NaN,10105000,NaN,13987000,NaN,24171000,NaN,14083000,NaN,18278000,NaN,24246000,NaN,10282000,NaN,13593000,NaN,17463000,NaN,9201000,NaN,12558000,NaN,17210000,NaN,11573000,NaN,15384000,NaN,17340000,NaN,9379000,NaN,7874000,NaN,7827000,NaN,4234000,NaN,3979000,NaN,4725000,NaN,1672000,NaN,1667000,NaN,2126000,NaN,1392000,NaN,1315000,NaN,2126000,NaN,1041000,NaN,986000,NaN,1322000,NaN,566000,NaN,529000,NaN,750000
26,Interest & dividend income,901000,NaN,1049000,NaN,1045000,NaN,1190000,NaN,1358000,NaN,1307000,NaN,1418000,NaN,1505000,NaN,1452000,NaN,1327000,NaN,1282000,NaN,1224000,NaN,1036000,NaN,986000,NaN,941000,NaN,766000,NaN,675000,NaN,654000,NaN,439000,NaN,410000,NaN,427000,NaN,-,NaN,420000,NaN,421000,NaN,-,NaN,254000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
27,Interest expense,697000,NaN,757000,NaN,785000,NaN,866000,NaN,1010000,NaN,890000,NaN,846000,NaN,792000,NaN,734000,NaN,602000,NaN,530000,NaN,525000,NaN,409000,NaN,321000,NaN,276000,NaN,201000,NaN,163000,NaN,131000,NaN,100000,NaN,85000,NaN,84000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
28,"Other expense, net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,185000,NaN,-,NaN,-,NaN,263000,NaN,-,NaN,-,NaN,175000,NaN,-,NaN,-,NaN,137000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,13000,NaN,-,NaN,7000,NaN,4000,NaN,11000,NaN,7000
29,Interest income,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,168000,NaN,-,NaN,133000,NaN,99000,NaN,87000,NaN,88000
30,"Other income (expense), net",-158000,NaN,-10000,NaN,89000,NaN,43000,NaN,30000,NaN,143000,NaN,100000,NaN,-439000,NaN,38000,NaN,-,NaN,-165000,NaN,122000,NaN,-,NaN,-510000,NaN,-263000,NaN,-,NaN,-226000,NaN,-353000,NaN,-,NaN,-100000,NaN,-97000,NaN,-,NaN,-73000,NaN,41000,NaN,-,NaN,-106000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
31,"Interest & other income (expense), net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,81000
32,"Other income (expense), net",46000,NaN,282000,NaN,349000,NaN,367000,NaN,378000,NaN,560000,NaN,672000,NaN,274000,NaN,756000,NaN,540000,NaN,587000,NaN,821000,NaN,364000,NaN,155000,NaN,402000,NaN,390000,NaN,286000,NaN,170000,NaN,202000,NaN,225000,NaN,246000,NaN,-,NaN,347000,NaN,462000,NaN,-,NaN,148000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,155000,NaN,-,NaN,126000,NaN,95000,NaN,76000,NaN,-
33,"Other income (expense), net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,234000,NaN,-,NaN,-,NaN,288000,NaN,-,NaN,137000,NaN,172000,NaN,26000,NaN,136000,NaN,58000,NaN,50000,NaN,33000,NaN,60000,NaN,63000,NaN,158000,NaN,118000,NaN,162000,NaN,200000,NaN,-,NaN,148000,NaN,-,NaN,-,NaN,-,NaN,-
34,Income (loss) before provision for income taxes,13137000,NaN,13135000,NaN,25918000,NaN,11911000,NaN,13793000,NaN,23906000,NaN,13284000,NaN,16168000,NaN,27030000,NaN,11308000,NaN,14684000,NaN,24180000,NaN,10469000,NaN,14142000,NaN,24573000,NaN,14473000,NaN,18564000,NaN,24416000,NaN,10484000,NaN,13818000,NaN,17709000,NaN,9435000,NaN,12905000,NaN,17672000,NaN,11861000,NaN,15532000,NaN,17477000,NaN,9551000,NaN,7900000,NaN,7963000,NaN,4292000,NaN,4029000,NaN,4758000,NaN,1732000,NaN,1730000,NaN,2284000,NaN,1510000,NaN,1477000,NaN,2326000,NaN,1196000,NaN,1134000,NaN,1448000,NaN,661000,NaN,605000,NaN,831000
35,Provision for (benefit from) income taxes,1884000,NaN,1886000,NaN,3682000,NaN,1867000,NaN,2232000,NaN,3941000,NaN,1765000,NaN,2346000,NaN,6965000,NaN,2591000,NaN,3655000,NaN,6289000,NaN,2673000,NaN,3626000,NaN,6212000,NaN,3796000,NaN,4995000,NaN,6392000,NaN,2736000,NaN,3595000,NaN,4637000,NaN,2535000,NaN,3358000,NaN,4594000,NaN,3037000,NaN,3910000,NaN,4413000,NaN,2243000,NaN,1913000,NaN,1959000,NaN,1039000,NaN,955000,NaN,1380000,NaN,503000,NaN,525000,NaN,679000,NaN,438000,NaN,432000,NaN,745000,NaN,378000,NaN,364000,NaN,444000,NaN,189000,NaN,195000,NaN,266000
36,Net income (loss),11253000,NaN,11249000,NaN,22236000,NaN,10044000,NaN,11561000,NaN,19965000,NaN,11519000,NaN,13822000,NaN,20065000,NaN,8717000,NaN,11029000,NaN,17891000,NaN,7796000,NaN,10516000,NaN,18361000,NaN,10677000,NaN,13569000,NaN,18024000,NaN,7748000,NaN,10223000,NaN,13072000,NaN,6900000,NaN,9547000,NaN,13078000,NaN,8824000,NaN,11622000,NaN,13064000,NaN,7308000,NaN,5987000,NaN,6004000,NaN,3253000,NaN,3074000,NaN,3378000,NaN,1229000,NaN,1205000,NaN,1605000,NaN,1072000,NaN,1045000,NaN,1581000,NaN,818000,NaN,770000,NaN,1004000,NaN,472000,NaN,410000,NaN,565000
37,Weighted average shares outstanding - basic,17250292,NaN,17440404,NaN,17660160,NaN,18282532,NaN,18696284,NaN,18943280,NaN,19528668,NaN,20099508,NaN,20451508,NaN,20780352,NaN,20903164,NaN,21194644,NaN,21772232,NaN,22057524,NaN,22235720,NaN,22919544,NaN,23175196,NaN,23372328,NaN,24050540,NaN,24493196,NaN,25090016,NaN,25721304,NaN,26309612,NaN,26289648,NaN,26224688,NaN,26140296,NaN,26069148,NaN,25931024,NaN,25849488,NaN,25740232,NaN,25541516,NaN,25411344,NaN,25299176,NaN,25023936,NaN,24953040,NaN,24895976,NaN,24744664,NaN,24627288,NaN,24524080,NaN,24270568,NaN,24164084,NaN,24015348,NaN,23838500,NaN,23545480,NaN,23261868
38,Weighted average shares outstanding - diluted,17419152,NaN,17618764,NaN,17818416,NaN,18405520,NaN,18802584,NaN,19093008,NaN,19706436,NaN,20273972,NaN,20631148,NaN,20933996,NaN,21046752,NaN,21311980,NaN,21891124,NaN,22163544,NaN,22376508,NaN,23092396,NaN,23339432,NaN,23527212,NaN,24206844,NaN,24626784,NaN,25240656,NaN,25879420,NaN,26488980,NaN,26522076,NaN,26517652,NaN,26457004,NaN,26364016,NaN,26258680,NaN,26206432,NaN,26128312,NaN,25966108,NaN,25840584,NaN,25753924,NaN,25456480,NaN,25283804,NaN,25241832,NaN,25288676,NaN,25181212,NaN,25201512,NaN,24938788,NaN,24826284,NaN,24732316,NaN,24538304,NaN,24599036,NaN,24477796
39,Year end shares outstanding,17135756,NaN,17295948,NaN,17539836,NaN,18125580,NaN,18429136,NaN,18919212,NaN,19371668,NaN,19773128,NaN,20326604,NaN,20679128,NaN,20823260,NaN,21021692,NaN,21572660,NaN,21913784,NaN,22177948,NaN,22821600,NaN,23049112,NaN,23305676,NaN,23956684,NaN,24128860,NaN,24988516,NaN,25436376,NaN,26322632,NaN,26291244,NaN,26243448,NaN,26179496,NaN,26101992,NaN,2.59533e+07,NaN,2.58909e+07,NaN,2.5789e+07,NaN,2.55775e+07,NaN,2.54698e+07,NaN,2.53759e+07,NaN,2.50806e+07,NaN,2.49735e+07,NaN,2.49316e+07,NaN,2.48009e+07,NaN,2.46801e+07,NaN,2.46016e+07,NaN,2.43365e+07,NaN,2.42114e+07,NaN,2.40862e+07,NaN,2.38837e+07,NaN,2.37773e+07,NaN,2.36773e+07

In [612]:
#getting unique years - whats the point?
print(set(stock_data.index.year))

{2016, 2017, 2018, 2019, 2020, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015}

In [613]:
IncomeStatement_Quarterly.iloc[[10, 17]]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
10,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter
17,Total net sales,59685000,NaN,58313000,NaN,91819000,NaN,53809000,NaN,58015000,NaN,84310000,NaN,53265000,NaN,61137000,NaN,88293000,NaN,45408000,NaN,52896000,NaN,78351000,NaN,42358000,NaN,50557000,NaN,75872000,NaN,49605000,NaN,58010000,NaN,74599000,NaN,37432000,NaN,45646000,NaN,57594000,NaN,35323000,NaN,43603000,NaN,54512000,NaN,35023000,NaN,39186000,NaN,46333000,NaN,28571000,NaN,24667000,NaN,26741000,NaN,15700000,NaN,13499000,NaN,15683000,NaN,8337000,NaN,8163000,NaN,10167000,NaN,7464000,NaN,7512000,NaN,9608000,NaN,5410000,NaN,5264000,NaN,7115000,NaN,4370000,NaN,4359000,NaN,5749000

In [614]:
def net_rev():
    net_rev = IncomeStatement_Quarterly.iloc[[9, 17]]
    net_rev = net_rev.T
    net_rev.reset_index(inplace = True)
    net_rev.drop('index', axis = 1, inplace = True)
    net_rev = net_rev[~(net_rev.index % 2 == 0)]
    net_rev = net_rev.rename(columns={9: "Date", 17: "Total Revenue"})
    return net_rev
net_rev = net_rev()
net_rev.head(8)

          Date Total Revenue
1   06/27/2020      59685000
3   03/28/2020      58313000
5   12/28/2019      91819000
7   06/29/2019      53809000
9   03/30/2019      58015000
11  12/29/2018      84310000
13  06/30/2018      53265000
15  03/31/2018      61137000

In [615]:
net_rev.index

Int64Index([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
            35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
            69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89],
           dtype='int64')

In [616]:
# Define years and month and insert into main DataFrame
# net_rev_years = pd.DatetimeIndex(net_rev['Date']).year
net_rev['Date'] = pd.to_datetime(net_rev['Date'])
net_rev_quarters = net_rev['Date'].dt.quarter
# net_rev.insert(1, "Year", years)
net_rev.head()

        Date Total Revenue
1 2020-06-27      59685000
3 2020-03-28      58313000
5 2019-12-28      91819000
7 2019-06-29      53809000
9 2019-03-30      58015000

In [617]:
net_rev.insert(1, "Quarter", net_rev_quarters)

#change dates to datetime format
net_rev['Date'] = pd.to_datetime(net_rev['Date'])
net_rev.reset_index(inplace = True)
net_rev.head()

   index       Date  Quarter Total Revenue
0      1 2020-06-27        2      59685000
1      3 2020-03-28        1      58313000
2      5 2019-12-28        4      91819000
3      7 2019-06-29        2      53809000
4      9 2019-03-30        1      58015000

In [618]:
# net_rev['Date'].dt.quarter
net_rev.head()

   index       Date  Quarter Total Revenue
0      1 2020-06-27        2      59685000
1      3 2020-03-28        1      58313000
2      5 2019-12-28        4      91819000
3      7 2019-06-29        2      53809000
4      9 2019-03-30        1      58015000

In [619]:
net_rev.drop('index', axis = 1, inplace = True)

In [620]:
display(dec_df13.head(), net_rev.head())

                 Close      High       Low
Year Quarter
2005 1        1.411996  1.433908  1.390404
     2        1.352740  1.375603  1.332132
     3        1.632829  1.650273  1.608292
     4        2.267874  2.295085  2.232783
2006 1        2.505685  2.559983  2.467074

        Date  Quarter Total Revenue
0 2020-06-27        2      59685000
1 2020-03-28        1      58313000
2 2019-12-28        4      91819000
3 2019-06-29        2      53809000
4 2019-03-30        1      58015000

In [621]:
# print(net_rev['Date'].dt.year)

In [622]:
net_rev['Date'] = net_rev['Date'].dt.year
net_rev = net_rev.rename(columns = {'Date' : 'Year'})

In [623]:
net_rev

    Year  Quarter Total Revenue
0   2020        2      59685000
1   2020        1      58313000
2   2019        4      91819000
3   2019        2      53809000
4   2019        1      58015000
5   2018        4      84310000
6   2018        2      53265000
7   2018        1      61137000
8   2017        4      88293000
9   2017        3      45408000
10  2017        2      52896000
11  2016        4      78351000
12  2016        2      42358000
13  2016        1      50557000
14  2015        4      75872000
15  2015        2      49605000
16  2015        1      58010000
17  2014        4      74599000
18  2014        2      37432000
19  2014        1      45646000
20  2013        4      57594000
21  2013        2      35323000
22  2013        1      43603000
23  2012        4      54512000
24  2012        2      35023000
25  2012        1      39186000
26  2011        4      46333000
27  2011        2      28571000
28  2011        1      24667000
29  2010        4      26741000
30  2010        2      15700000
31  2010        1      13499000
32  2009        4      15683000
33  2009        2       8337000
34  2009        1       8163000
35  2008        4      10167000
36  2008        2       7464000
37  2008        1       7512000
38  2007        4       9608000
39  2007        2       5410000
40  2007        1       5264000
41  2006        4       7115000
42  2006        3       4370000
43  2006        2       4359000
44  2005        4       5749000

In [624]:
try:
    filter = net_rev['Total Revenue']=="-"
# printing only filtered columns 
    net_rev['Total Revenue'][filter] = net_rev['Total Revenue'].iloc[15]
# net_rev.where(filter).fillna(method = "bfill") 
# net_rev['Total Revenue'].str.replace('-', NaN)
    net_rev['Total Revenue'].iloc[16]
# net_rev['Total Revenue'][filter]
except:
    print(" no - found in data")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [625]:
net_rev

    Year  Quarter Total Revenue
0   2020        2      59685000
1   2020        1      58313000
2   2019        4      91819000
3   2019        2      53809000
4   2019        1      58015000
5   2018        4      84310000
6   2018        2      53265000
7   2018        1      61137000
8   2017        4      88293000
9   2017        3      45408000
10  2017        2      52896000
11  2016        4      78351000
12  2016        2      42358000
13  2016        1      50557000
14  2015        4      75872000
15  2015        2      49605000
16  2015        1      58010000
17  2014        4      74599000
18  2014        2      37432000
19  2014        1      45646000
20  2013        4      57594000
21  2013        2      35323000
22  2013        1      43603000
23  2012        4      54512000
24  2012        2      35023000
25  2012        1      39186000
26  2011        4      46333000
27  2011        2      28571000
28  2011        1      24667000
29  2010        4      26741000
30  2010        2      15700000
31  2010        1      13499000
32  2009        4      15683000
33  2009        2       8337000
34  2009        1       8163000
35  2008        4      10167000
36  2008        2       7464000
37  2008        1       7512000
38  2007        4       9608000
39  2007        2       5410000
40  2007        1       5264000
41  2006        4       7115000
42  2006        3       4370000
43  2006        2       4359000
44  2005        4       5749000

In [626]:
net_rev['Total Revenue'] = net_rev['Total Revenue'].astype('int')

In [627]:
net_rev.head()

   Year  Quarter  Total Revenue
0  2020        2       59685000
1  2020        1       58313000
2  2019        4       91819000
3  2019        2       53809000
4  2019        1       58015000

In [628]:
# Getting price based on quarters 
net_rev1 = pd.pivot_table(net_rev, index=['Year', 'Quarter'], values=['Total Revenue'])
net_rev1

              Total Revenue
Year Quarter
2005 4              5749000
2006 2              4359000
     3              4370000
     4              7115000
2007 1              5264000
     2              5410000
     4              9608000
2008 1              7512000
     2              7464000
     4             10167000
2009 1              8163000
     2              8337000
     4             15683000
2010 1             13499000
     2             15700000
     4             26741000
2011 1             24667000
     2             28571000
     4             46333000
2012 1             39186000
     2             35023000
     4             54512000
2013 1             43603000
     2             35323000
     4             57594000
2014 1             45646000
     2             37432000
     4             74599000
2015 1             58010000
     2             49605000
     4             75872000
2016 1             50557000
     2             42358000
     4             78351000
2017 2             52896000
     3             45408000
     4             88293000
2018 1             61137000
     2             53265000
     4             84310000
2019 1             58015000
     2             53809000
     4             91819000
2020 1             58313000
     2             59685000

In [629]:
net_rev1.head(10)

              Total Revenue
Year Quarter
2005 4              5749000
2006 2              4359000
     3              4370000
     4              7115000
2007 1              5264000
     2              5410000
     4              9608000
2008 1              7512000
     2              7464000
     4             10167000

In [630]:
#trying to add third quarter data as average of 2nd and 4th quarter
# # print(net_rev1.index)
# year_quarter = {}
# for year, quarter in net_rev1.index:
# #     print(quarter)
#     year_quarter[year] = quarter
# #     if quarter == 2:
        
# #    print((quarter, quarter % 3 == 1))
# #     net_rev['Quarter'].insert(3)
# print(year_quarter)

In [631]:
net_rev = net_rev1

In [632]:
display(net_rev.head(), dec_df13.head())

              Total Revenue
Year Quarter
2005 4              5749000
2006 2              4359000
     3              4370000
     4              7115000
2007 1              5264000

                 Close      High       Low
Year Quarter
2005 1        1.411996  1.433908  1.390404
     2        1.352740  1.375603  1.332132
     3        1.632829  1.650273  1.608292
     4        2.267874  2.295085  2.232783
2006 1        2.505685  2.559983  2.467074

In [633]:
#merging net_revenue into main dataframe (dec_df)
dec_df = pd.merge(dec_df13, net_rev, left_index = True,right_index = True,  how = 'outer')
dec_df.head()

                 Close      High       Low  Total Revenue
Year Quarter
2005 1        1.411996  1.433908  1.390404            NaN
     2        1.352740  1.375603  1.332132            NaN
     3        1.632829  1.650273  1.608292            NaN
     4        2.267874  2.295085  2.232783      5749000.0
2006 1        2.505685  2.559983  2.467074            NaN

In [634]:
# net_rev_test = net_rev.copy()
# net_rev_test['Date'] = pd.to_datetime(net_rev_test['Date']).dt.strftime('%Y-%m-%d')
# #                 pd.to_datetime(df['column'], format = "%Y%m%d").dt.strftime('%Y-%m-%d')
# net_rev_test['Date'] = pd.to_datetime(net_rev_test['Date'])
# net_rev_quarters = net_rev_test['Date'].dt.quarter
# net_rev = net_rev.insert(1, 'Quarters', net_rev_quarters)
# display(net_rev_test.head(), net_rev_test.dtypes)

In [635]:
dec_df.head()

                 Close      High       Low  Total Revenue
Year Quarter
2005 1        1.411996  1.433908  1.390404            NaN
     2        1.352740  1.375603  1.332132            NaN
     3        1.632829  1.650273  1.608292            NaN
     4        2.267874  2.295085  2.232783      5749000.0
2006 1        2.505685  2.559983  2.467074            NaN

In [636]:
dec_df['Total Revenue'] = dec_df['Total Revenue'].bfill()
dec_df

                   Close        High         Low  Total Revenue
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0
     2          1.352740    1.375603    1.332132      5749000.0
     3          1.632829    1.650273    1.608292      5749000.0
     4          2.267874    2.295085    2.232783      5749000.0
2006 1          2.505685    2.559983    2.467074      4359000.0
     2          2.286786    2.328282    2.255096      4359000.0
     3          2.364666    2.395510    2.328226      4370000.0
     4          2.958299    2.993095    2.922098      7115000.0
2007 1          3.161434    3.198688    3.124374      5264000.0
     2          3.868152    3.911213    3.819632      5410000.0
     3          4.843560    4.917976    4.756417      9608000.0
     4          6.378103    6.478594    6.254314      9608000.0
2008 1          4.969239    5.091739    4.861475      7512000.0
     2          6.198811    6.287919    6.089431      7464000.0
     3          5.719330    5.841925    5.604046     10167000.0
     4          3.390580    3.504258    3.277282     10167000.0
2009 1          3.341932    3.404854    3.276996      8163000.0
     2          4.621905    4.674467    4.550397      8337000.0
     3          5.865184    5.913728    5.804018     15683000.0
     4          7.045586    7.121797    6.978984     15683000.0
2010 1          7.530539    7.605164    7.447541     13499000.0
     2          9.097817    9.215408    8.952097     15700000.0
     3          9.282327    9.375893    9.172846     26741000.0
     4         11.124810   11.199632   11.035692     26741000.0
2011 1         12.345830   12.433525   12.223433     24667000.0
     2         12.057585   12.168316   11.964943     28571000.0
     3         13.589654   13.743108   13.414397     46333000.0
     4         13.987806   14.123345   13.849422     46333000.0
2012 1         17.988566   18.112079   17.793992     39186000.0
     2         20.753220   21.005403   20.527902     35023000.0
     3         22.876553   23.032630   22.669093     54512000.0
     4         20.634424   20.927817   20.386187     54512000.0
2013 1         16.649083   16.863107   16.481637     43603000.0
     2         15.383677   15.582623   15.222015     35323000.0
     3         16.580195   16.742271   16.435720     57594000.0
     4         18.891892   19.033917   18.737980     57594000.0
2014 1         19.021592   19.174455   18.879549     45646000.0
     2         21.279382   21.413271   21.106015     37432000.0
     3         24.540859   24.739531   24.327422     74599000.0
     4         27.205313   27.465469   26.948008     74599000.0
2015 1         30.194262   30.514057   29.889016     58010000.0
     2         31.984524   32.242222   31.759048     49605000.0
     3         29.325859   29.688789   28.963242     75872000.0
     4         28.574844   28.839141   28.291836     75872000.0
2016 1         24.913770   25.169385   24.618688     50557000.0
     2         24.850313   25.066563   24.645742     42358000.0
     3         26.466523   26.629531   26.276172     78351000.0
     4         28.349762   28.540159   28.122936     78351000.0
2017 1         32.928145   33.041290   32.713387     52896000.0
     2         36.968849   37.205000   36.719960     52896000.0
     3         38.792262   39.065119   38.494127     45408000.0
     4         41.787064   42.018294   41.486230     88293000.0
2018 1         43.047828   43.524303   42.654017     61137000.0
     2         45.349141   45.678125   44.980117     53265000.0
     3         52.075000   52.473532   51.630238     84310000.0
     4         48.478016   49.216905   47.816468     84310000.0
2019 1         42.415943   42.764181   41.969795     58015000.0
     2         48.723175   49.139563   48.247698     53809000.0
     3         52.280195   52.753438   51.826523     91819000.0
     4         64.332187   64.668281   63.725820     91819000.0
2020 1         73.540927   74.693105   72.257581     58313000.0
     2         77.490317   78.341389   76.394960     59685000.0
     3        109.115351  110.836680  107.262734            NaN
     4        116.550244  118.171951  115.108536            NaN

In [637]:
mask = data_IncomeStatement_full[0].str.contains('share', case=False, na=False)
# mask = data_IncomeStatement_full[0].fillna(1)
mask.isnull().sum()

0

In [638]:
data_IncomeStatement_full[mask]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89
38,Weighted average shares outstanding - basic,17250292,NaN,17440404,NaN,17660160,NaN,18282532,NaN,18696284,NaN,18943280,NaN,19528668,NaN,20099508,NaN,20451508,NaN,20780352,NaN,20903164,NaN,21194644,NaN,21772232,NaN,22057524,NaN,22235720,NaN,22919544,NaN,23175196,NaN,23372328,NaN,24050540,NaN,24493196,NaN,25090016,NaN,25721304,NaN,26309612,NaN,26289648,NaN,26224688,NaN,26140296,NaN,26069148,NaN,25931024,NaN,25849488,NaN,25740232,NaN,25541516,NaN,25411344,NaN,25299176,NaN,25023936,NaN,24953040,NaN,24895976,NaN,24744664,NaN,24627288,NaN,24524080,NaN,24270568,NaN,24164084,NaN,24015348,NaN,23838500,NaN,23545480,NaN,23261868
39,Weighted average shares outstanding - diluted,17419152,NaN,17618764,NaN,17818416,NaN,18405520,NaN,18802584,NaN,19093008,NaN,19706436,NaN,20273972,NaN,20631148,NaN,20933996,NaN,21046752,NaN,21311980,NaN,21891124,NaN,22163544,NaN,22376508,NaN,23092396,NaN,23339432,NaN,23527212,NaN,24206844,NaN,24626784,NaN,25240656,NaN,25879420,NaN,26488980,NaN,26522076,NaN,26517652,NaN,26457004,NaN,26364016,NaN,26258680,NaN,26206432,NaN,26128312,NaN,25966108,NaN,25840584,NaN,25753924,NaN,25456480,NaN,25283804,NaN,25241832,NaN,25288676,NaN,25181212,NaN,25201512,NaN,24938788,NaN,24826284,NaN,24732316,NaN,24538304,NaN,24599036,NaN,24477796
40,Year end shares outstanding,17135756,NaN,17295948,NaN,17539836,NaN,18125580,NaN,18429136,NaN,18919212,NaN,19371668,NaN,19773128,NaN,20326604,NaN,20679128,NaN,20823260,NaN,21021692,NaN,21572660,NaN,21913784,NaN,22177948,NaN,22821600,NaN,23049112,NaN,23305676,NaN,23956684,NaN,24128860,NaN,24988516,NaN,25436376,NaN,26322632,NaN,26291244,NaN,26243448,NaN,26179496,NaN,26101992,NaN,2.59533e+07,NaN,2.58909e+07,NaN,2.5789e+07,NaN,2.55775e+07,NaN,2.54698e+07,NaN,2.53759e+07,NaN,2.50806e+07,NaN,2.49735e+07,NaN,2.49316e+07,NaN,2.48009e+07,NaN,2.46801e+07,NaN,2.46016e+07,NaN,2.43365e+07,NaN,2.42114e+07,NaN,2.40862e+07,NaN,2.38837e+07,NaN,2.37773e+07,NaN,2.36773e+07
41,Net earnings (loss) per share - basic,0.653,NaN,0.645,NaN,1.26,NaN,0.55,NaN,0.618,NaN,1.055,NaN,0.59,NaN,0.688,NaN,0.98,NaN,0.42,NaN,0.528,NaN,0.845,NaN,0.358,NaN,0.478,NaN,0.825,NaN,0.465,NaN,0.585,NaN,0.77,NaN,0.323,NaN,0.418,NaN,0.521,NaN,0.268,NaN,0.363,NaN,0.498,NaN,0.336,NaN,0.445,NaN,0.501,NaN,0.282,NaN,0.232,NaN,0.233,NaN,0.128,NaN,0.121,NaN,0.134,NaN,0.049,NaN,0.048,NaN,0.065,NaN,0.043,NaN,0.043,NaN,0.065,NaN,0.034,NaN,0.032,NaN,0.042,NaN,0.02,NaN,0.018,NaN,0.024
42,Net earnings (loss) per share - diluted,0.645,NaN,0.638,NaN,1.248,NaN,0.545,NaN,0.615,NaN,1.045,NaN,0.585,NaN,0.683,NaN,0.973,NaN,0.418,NaN,0.525,NaN,0.84,NaN,0.355,NaN,0.475,NaN,0.82,NaN,0.463,NaN,0.583,NaN,0.765,NaN,0.32,NaN,0.415,NaN,0.518,NaN,0.267,NaN,0.36,NaN,0.493,NaN,0.333,NaN,0.439,NaN,0.495,NaN,0.278,NaN,0.229,NaN,0.23,NaN,0.125,NaN,0.119,NaN,0.131,NaN,0.048,NaN,0.048,NaN,0.064,NaN,0.043,NaN,0.041,NaN,0.063,NaN,0.033,NaN,0.031,NaN,0.041,NaN,0.019,NaN,0.017,NaN,0.023
43,Cash dividends declared per share,0.205,NaN,0.193,NaN,0.193,NaN,0.193,NaN,0.183,NaN,0.183,NaN,0.183,NaN,0.158,NaN,0.158,NaN,0.158,NaN,0.143,NaN,0.143,NaN,0.143,NaN,0.13,NaN,0.13,NaN,0.13,NaN,0.118,NaN,0.118,NaN,0.118,NaN,0.109,NaN,0.109,NaN,0.109,NaN,0.095,NaN,0.095,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-

In [639]:
avg_shares1 = data_IncomeStatement.iloc[[10, 39]]
avg_shares1 = avg_shares1.T
avg_shares1.head()

           10        39
1  06/27/2020  17419152
3  03/28/2020  17618764
5  12/28/2019  17818416
7  06/29/2019  18405520
9  03/30/2019  18802584

In [640]:
#adding quarters and merging with dec_df
avg_shares1.rename(columns = {10 : "Date", 39 : "Avg_Shares"}, inplace = True)

avg_shares1['Date'] = pd.to_datetime(avg_shares1['Date'])
avg_shares_quarters = avg_shares1['Date'].dt.quarter
avg_shares_years = avg_shares1['Date'].dt.year

# # #change dates to datetime format
avg_shares1['Date'] = pd.to_datetime(avg_shares1['Date'])

#sort years from low to high in order to fit with dec_df
avg_shares1.sort_values(by=['Date'], inplace=True)
# avg_shares1.reset_index(inplace = True)
# avg_shares1.drop(['index', 'level_0'], axis = 1, inplace = True)
# avg_shares1.drop('index', axis = 1, inplace = True)
avg_shares1.insert(1, "Year", avg_shares_years)
avg_shares1.insert(2, "Quarter", avg_shares_quarters)

avg_shares1

         Date  Year  Quarter Avg_Shares
89 2005-12-31  2005        4   24477796
87 2006-04-01  2006        2   24599036
85 2006-07-01  2006        3   24538304
83 2006-12-30  2006        4   24732316
81 2007-03-31  2007        1   24826284
79 2007-06-30  2007        2   24938788
77 2007-12-29  2007        4   25201512
75 2008-03-29  2008        1   25181212
73 2008-06-28  2008        2   25288676
71 2008-12-27  2008        4   25241832
69 2009-03-28  2009        1   25283804
67 2009-06-27  2009        2   25456480
65 2009-12-26  2009        4   25753924
63 2010-03-27  2010        1   25840584
61 2010-06-26  2010        2   25966108
59 2010-12-25  2010        4   26128312
57 2011-03-26  2011        1   26206432
55 2011-06-25  2011        2   26258680
53 2011-12-31  2011        4   26364016
51 2012-03-31  2012        1   26457004
49 2012-06-30  2012        2   26517652
47 2012-12-29  2012        4   26522076
45 2013-03-30  2013        1   26488980
43 2013-06-29  2013        2   25879420
41 2013-12-28  2013        4   25240656
39 2014-03-29  2014        1   24626784
37 2014-06-28  2014        2   24206844
35 2014-12-27  2014        4   23527212
33 2015-03-28  2015        1   23339432
31 2015-06-27  2015        2   23092396
29 2015-12-26  2015        4   22376508
27 2016-03-26  2016        1   22163544
25 2016-06-25  2016        2   21891124
23 2016-12-31  2016        4   21311980
21 2017-04-01  2017        2   21046752
19 2017-07-01  2017        3   20933996
17 2017-12-30  2017        4   20631148
15 2018-03-31  2018        1   20273972
13 2018-06-30  2018        2   19706436
11 2018-12-29  2018        4   19093008
9  2019-03-30  2019        1   18802584
7  2019-06-29  2019        2   18405520
5  2019-12-28  2019        4   17818416
3  2020-03-28  2020        1   17618764
1  2020-06-27  2020        2   17419152

In [641]:
avg_shares1['Avg_Shares'] = avg_shares1['Avg_Shares'].astype('int64')
avg_shares1.dtypes

Date          datetime64[ns]
Year                   int64
Quarter                int64
Avg_Shares             int64
dtype: object

In [642]:
# Getting price based on quarters 
avg_shares1 = pd.pivot_table(avg_shares1, index=['Year', 'Quarter'], values=['Avg_Shares'])
avg_shares1

              Avg_Shares
Year Quarter
2005 4          24477796
2006 2          24599036
     3          24538304
     4          24732316
2007 1          24826284
     2          24938788
     4          25201512
2008 1          25181212
     2          25288676
     4          25241832
2009 1          25283804
     2          25456480
     4          25753924
2010 1          25840584
     2          25966108
     4          26128312
2011 1          26206432
     2          26258680
     4          26364016
2012 1          26457004
     2          26517652
     4          26522076
2013 1          26488980
     2          25879420
     4          25240656
2014 1          24626784
     2          24206844
     4          23527212
2015 1          23339432
     2          23092396
     4          22376508
2016 1          22163544
     2          21891124
     4          21311980
2017 2          21046752
     3          20933996
     4          20631148
2018 1          20273972
     2          19706436
     4          19093008
2019 1          18802584
     2          18405520
     4          17818416
2020 1          17618764
     2          17419152

In [643]:
#merging net_revenue into main dataframe (dec_df)
dec_df = pd.merge(dec_df, avg_shares1, left_index = True,right_index = True,  how = 'outer')
dec_df.head()

                 Close      High       Low  Total Revenue  Avg_Shares
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0         NaN
     2        1.352740  1.375603  1.332132      5749000.0         NaN
     3        1.632829  1.650273  1.608292      5749000.0         NaN
     4        2.267874  2.295085  2.232783      5749000.0  24477796.0
2006 1        2.505685  2.559983  2.467074      4359000.0         NaN

In [644]:
test = IncomeStatement_Quarterly.iloc[[9, 39]]
test.iloc[1][0]

'Year end shares outstanding'

In [645]:
import os
os.getcwd()

'C:\\Users\\User\\github\\Guided-Capstone'

In [646]:
IncomeStatement_Quarterly.iloc[[9, 36]]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
9,Report Date,06/27/2020,NaN,03/28/2020,NaN,12/28/2019,NaN,06/29/2019,NaN,03/30/2019,NaN,12/29/2018,NaN,06/30/2018,NaN,03/31/2018,NaN,12/30/2017,NaN,07/01/2017,NaN,04/01/2017,NaN,12/31/2016,NaN,06/25/2016,NaN,03/26/2016,NaN,12/26/2015,NaN,06/27/2015,NaN,03/28/2015,NaN,12/27/2014,NaN,06/28/2014,NaN,03/29/2014,NaN,12/28/2013,NaN,06/29/2013,NaN,03/30/2013,NaN,12/29/2012,NaN,06/30/2012,NaN,03/31/2012,NaN,12/31/2011,NaN,06/25/2011,NaN,03/26/2011,NaN,12/25/2010,NaN,06/26/2010,NaN,03/27/2010,NaN,12/26/2009,NaN,06/27/2009,NaN,03/28/2009,NaN,12/27/2008,NaN,06/28/2008,NaN,03/29/2008,NaN,12/29/2007,NaN,06/30/2007,NaN,03/31/2007,NaN,12/30/2006,NaN,07/01/2006,NaN,04/01/2006,NaN,12/31/2005
36,Net income (loss),11253000,NaN,11249000,NaN,22236000,NaN,10044000,NaN,11561000,NaN,19965000,NaN,11519000,NaN,13822000,NaN,20065000,NaN,8717000,NaN,11029000,NaN,17891000,NaN,7796000,NaN,10516000,NaN,18361000,NaN,10677000,NaN,13569000,NaN,18024000,NaN,7748000,NaN,10223000,NaN,13072000,NaN,6900000,NaN,9547000,NaN,13078000,NaN,8824000,NaN,11622000,NaN,13064000,NaN,7308000,NaN,5987000,NaN,6004000,NaN,3253000,NaN,3074000,NaN,3378000,NaN,1229000,NaN,1205000,NaN,1605000,NaN,1072000,NaN,1045000,NaN,1581000,NaN,818000,NaN,770000,NaN,1004000,NaN,472000,NaN,410000,NaN,565000

In [647]:
global dec_df_copy
dec_df_copy = dec_df.copy()

def data_cleaning(df, row, dec_df_copy):
    
#     dec_df_copy = dec_df.copy()
    #getting net income per share and merging with main dec_df
    param = df.iloc[[9, row]]
    param_name = param.iloc[1][0].title()
    print(param_name)  
    param.drop('Unnamed: 0', axis = 1, inplace = True)
#     param.columns = param.iloc[0]
#     
#     param.reset_index(inplace = True)
    #adding quarters and merging with dec_df
    param = param.T
    param.rename(columns = {9 : "Date", row : "{}".format(param_name)}, inplace = True)
    param.reset_index(inplace = True)
    param.drop('index', axis = 1, inplace = True)
    param = param[~(param.index % 2 == 1)]
    param['Date'] = pd.to_datetime(param['Date'])
    param_quarters = param['Date'].dt.quarter
    param_years = param['Date'].dt.year

    # # #change dates to datetime format
    param['Date'] = pd.to_datetime(param['Date'])

    #sort years from low to high in order to fit with dec_df
    param.sort_values(by=['Date'], inplace=True)
    # avg_shares1.reset_index(inplace = True)
    # avg_shares1.drop(['index', 'level_0'], axis = 1, inplace = True)
    # avg_shares1.drop('index', axis = 1, inplace = True)
    param.insert(1, "Year", param_years)
    param.insert(2, "Quarter", param_quarters)
    param[param_name] = param[param_name].astype('int64')
    param = param.pivot_table(index=['Year', 'Quarter'], values=param_name, aggfunc='mean')
#     dec_df_copy 
    
    display(dec_df_copy)
    global dec_df_final
    dec_df_final = pd.merge(dec_df_copy, param, left_index = True,right_index = True,  how = 'outer')
    display(dec_df_final)
    dec_df_final[param_name] = dec_df_final[param_name].bfill()
#     global dec_df_copy
#     dec_df_copy = dec_df_final
#     dec_df_copy = dec_df_final
    return dec_df_final

In [648]:
# global dec_df_copy
dec_df_copy = data_cleaning(IncomeStatement_Quarterly, 39, dec_df_copy)
dec_df_copy = data_cleaning(IncomeStatement_Quarterly, 36, dec_df_copy )
# dec_df_copy = data_cleaning(IncomeStatement_Quarterly, 36 )
dec_df_copy

Year End Shares Outstanding

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3994: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                   Close        High         Low  Total Revenue  Avg_Shares
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding
Year Quarter
2005 1                                NaN
     2                                NaN
     3                                NaN
     4                         23677280.0
2006 1                                NaN
     2                         23777268.0
     3                         23883653.0
     4                         24086156.0
2007 1                         24211406.0
     2                         24336530.0
     3                                NaN
     4                         24601608.0
2008 1                         24680068.0
     2                         24800906.0
     3                                NaN
     4                         24931617.0
2009 1                         24973530.0
     2                         25080585.0
     3                                NaN
     4                         25375901.0
2010 1                         25469802.0
     2                         25577505.0
     3                                NaN
     4                         25788993.0
2011 1                         25890874.0
     2                         25953305.0
     3                                NaN
     4                         26101992.0
2012 1                         26179496.0
     2                         26243448.0
     3                                NaN
     4                         26291244.0
2013 1                         26322632.0
     2                         25436376.0
     3                                NaN
     4                         24988516.0
2014 1                         24128860.0
     2                         23956684.0
     3                                NaN
     4                         23305676.0
2015 1                         23049112.0
     2                         22821600.0
     3                                NaN
     4                         22177948.0
2016 1                         21913784.0
     2                         21572660.0
     3                                NaN
     4                         21021692.0
2017 1                                NaN
     2                         20823260.0
     3                         20679128.0
     4                         20326604.0
2018 1                         19773128.0
     2                         19371668.0
     3                                NaN
     4                         18919212.0
2019 1                         18429136.0
     2                         18125580.0
     3                                NaN
     4                         17539836.0
2020 1                         17295948.0
     2                         17135756.0
     3                                NaN
     4                                NaN

Net Income (Loss)

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding
Year Quarter
2005 1                         23677280.0
     2                         23677280.0
     3                         23677280.0
     4                         23677280.0
2006 1                         23777268.0
     2                         23777268.0
     3                         23883653.0
     4                         24086156.0
2007 1                         24211406.0
     2                         24336530.0
     3                         24601608.0
     4                         24601608.0
2008 1                         24680068.0
     2                         24800906.0
     3                         24931617.0
     4                         24931617.0
2009 1                         24973530.0
     2                         25080585.0
     3                         25375901.0
     4                         25375901.0
2010 1                         25469802.0
     2                         25577505.0
     3                         25788993.0
     4                         25788993.0
2011 1                         25890874.0
     2                         25953305.0
     3                         26101992.0
     4                         26101992.0
2012 1                         26179496.0
     2                         26243448.0
     3                         26291244.0
     4                         26291244.0
2013 1                         26322632.0
     2                         25436376.0
     3                         24988516.0
     4                         24988516.0
2014 1                         24128860.0
     2                         23956684.0
     3                         23305676.0
     4                         23305676.0
2015 1                         23049112.0
     2                         22821600.0
     3                         22177948.0
     4                         22177948.0
2016 1                         21913784.0
     2                         21572660.0
     3                         21021692.0
     4                         21021692.0
2017 1                         20823260.0
     2                         20823260.0
     3                         20679128.0
     4                         20326604.0
2018 1                         19773128.0
     2                         19371668.0
     3                         18919212.0
     4                         18919212.0
2019 1                         18429136.0
     2                         18125580.0
     3                         17539836.0
     4                         17539836.0
2020 1                         17295948.0
     2                         17135756.0
     3                                NaN
     4                                NaN

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding  Net Income (Loss)
Year Quarter
2005 1                         23677280.0                NaN
     2                         23677280.0                NaN
     3                         23677280.0                NaN
     4                         23677280.0           565000.0
2006 1                         23777268.0                NaN
     2                         23777268.0           410000.0
     3                         23883653.0           472000.0
     4                         24086156.0          1004000.0
2007 1                         24211406.0           770000.0
     2                         24336530.0           818000.0
     3                         24601608.0                NaN
     4                         24601608.0          1581000.0
2008 1                         24680068.0          1045000.0
     2                         24800906.0          1072000.0
     3                         24931617.0                NaN
     4                         24931617.0          1605000.0
2009 1                         24973530.0          1205000.0
     2                         25080585.0          1229000.0
     3                         25375901.0                NaN
     4                         25375901.0          3378000.0
2010 1                         25469802.0          3074000.0
     2                         25577505.0          3253000.0
     3                         25788993.0                NaN
     4                         25788993.0          6004000.0
2011 1                         25890874.0          5987000.0
     2                         25953305.0          7308000.0
     3                         26101992.0                NaN
     4                         26101992.0         13064000.0
2012 1                         26179496.0         11622000.0
     2                         26243448.0          8824000.0
     3                         26291244.0                NaN
     4                         26291244.0         13078000.0
2013 1                         26322632.0          9547000.0
     2                         25436376.0          6900000.0
     3                         24988516.0                NaN
     4                         24988516.0         13072000.0
2014 1                         24128860.0         10223000.0
     2                         23956684.0          7748000.0
     3                         23305676.0                NaN
     4                         23305676.0         18024000.0
2015 1                         23049112.0         13569000.0
     2                         22821600.0         10677000.0
     3                         22177948.0                NaN
     4                         22177948.0         18361000.0
2016 1                         21913784.0         10516000.0
     2                         21572660.0          7796000.0
     3                         21021692.0                NaN
     4                         21021692.0         17891000.0
2017 1                         20823260.0                NaN
     2                         20823260.0         11029000.0
     3                         20679128.0          8717000.0
     4                         20326604.0         20065000.0
2018 1                         19773128.0         13822000.0
     2                         19371668.0         11519000.0
     3                         18919212.0                NaN
     4                         18919212.0         19965000.0
2019 1                         18429136.0         11561000.0
     2                         18125580.0         10044000.0
     3                         17539836.0                NaN
     4                         17539836.0         22236000.0
2020 1                         17295948.0         11249000.0
     2                         17135756.0         11253000.0
     3                                NaN                NaN
     4                                NaN                NaN

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding  Net Income (Loss)
Year Quarter
2005 1                         23677280.0           565000.0
     2                         23677280.0           565000.0
     3                         23677280.0           565000.0
     4                         23677280.0           565000.0
2006 1                         23777268.0           410000.0
     2                         23777268.0           410000.0
     3                         23883653.0           472000.0
     4                         24086156.0          1004000.0
2007 1                         24211406.0           770000.0
     2                         24336530.0           818000.0
     3                         24601608.0          1581000.0
     4                         24601608.0          1581000.0
2008 1                         24680068.0          1045000.0
     2                         24800906.0          1072000.0
     3                         24931617.0          1605000.0
     4                         24931617.0          1605000.0
2009 1                         24973530.0          1205000.0
     2                         25080585.0          1229000.0
     3                         25375901.0          3378000.0
     4                         25375901.0          3378000.0
2010 1                         25469802.0          3074000.0
     2                         25577505.0          3253000.0
     3                         25788993.0          6004000.0
     4                         25788993.0          6004000.0
2011 1                         25890874.0          5987000.0
     2                         25953305.0          7308000.0
     3                         26101992.0         13064000.0
     4                         26101992.0         13064000.0
2012 1                         26179496.0         11622000.0
     2                         26243448.0          8824000.0
     3                         26291244.0         13078000.0
     4                         26291244.0         13078000.0
2013 1                         26322632.0          9547000.0
     2                         25436376.0          6900000.0
     3                         24988516.0         13072000.0
     4                         24988516.0         13072000.0
2014 1                         24128860.0         10223000.0
     2                         23956684.0          7748000.0
     3                         23305676.0         18024000.0
     4                         23305676.0         18024000.0
2015 1                         23049112.0         13569000.0
     2                         22821600.0         10677000.0
     3                         22177948.0         18361000.0
     4                         22177948.0         18361000.0
2016 1                         21913784.0         10516000.0
     2                         21572660.0          7796000.0
     3                         21021692.0         17891000.0
     4                         21021692.0         17891000.0
2017 1                         20823260.0         11029000.0
     2                         20823260.0         11029000.0
     3                         20679128.0          8717000.0
     4                         20326604.0         20065000.0
2018 1                         19773128.0         13822000.0
     2                         19371668.0         11519000.0
     3                         18919212.0         19965000.0
     4                         18919212.0         19965000.0
2019 1                         18429136.0         11561000.0
     2                         18125580.0         10044000.0
     3                         17539836.0         22236000.0
     4                         17539836.0         22236000.0
2020 1                         17295948.0         11249000.0
     2                         17135756.0         11253000.0
     3                                NaN                NaN
     4                                NaN                NaN

In [649]:
# finding specific elements in income statement
mask = IncomeStatement_Quarterly['Unnamed: 0'].str.contains('revenue', case=False, na=False)
IncomeStatement_Quarterly[mask]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, Unnamed: 23, Unnamed: 24, Unnamed: 25, Unnamed: 26, Unnamed: 27, Unnamed: 28, Unnamed: 29, Unnamed: 30, Unnamed: 31, Unnamed: 32, Unnamed: 33, Unnamed: 34, Unnamed: 35, Unnamed: 36, Unnamed: 37, Unnamed: 38, Unnamed: 39, Unnamed: 40, Unnamed: 41, Unnamed: 42, Unnamed: 43, Unnamed: 44, Unnamed: 45, Unnamed: 46, Unnamed: 47, Unnamed: 48, Unnamed: 49, Unnamed: 50, Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, Unnamed: 69, Unnamed: 70, Unnamed: 71, Unnamed: 72, Unnamed: 73, Unnamed: 74, Unnamed: 75, Unnamed: 76, Unnamed: 77, Unnamed: 78, Unnamed: 79, Unnamed: 80, Unnamed: 81, Unnamed: 82, Unnamed: 83, Unnamed: 84, Unnamed: 85, Unnamed: 86, Unnamed: 87, Unnamed: 88, Unnamed: 89]
Index: []

In [650]:
dec_df_copy.head()

                 Close      High       Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0         NaN
     2        1.352740  1.375603  1.332132      5749000.0         NaN
     3        1.632829  1.650273  1.608292      5749000.0         NaN
     4        2.267874  2.295085  2.232783      5749000.0  24477796.0
2006 1        2.505685  2.559983  2.467074      4359000.0         NaN

              Year End Shares Outstanding  Net Income (Loss)
Year Quarter
2005 1                         23677280.0           565000.0
     2                         23677280.0           565000.0
     3                         23677280.0           565000.0
     4                         23677280.0           565000.0
2006 1                         23777268.0           410000.0

In [651]:
dec_df_copy['Net Income Per Share'] = dec_df_copy['Net Income (Loss)']/dec_df_copy['Year End Shares Outstanding']
display(dec_df_copy.head(), dec_df_copy.tail())

                 Close      High       Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0         NaN
     2        1.352740  1.375603  1.332132      5749000.0         NaN
     3        1.632829  1.650273  1.608292      5749000.0         NaN
     4        2.267874  2.295085  2.232783      5749000.0  24477796.0
2006 1        2.505685  2.559983  2.467074      4359000.0         NaN

              Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1                         23677280.0           565000.0
     2                         23677280.0           565000.0
     3                         23677280.0           565000.0
     4                         23677280.0           565000.0
2006 1                         23777268.0           410000.0

              Net Income Per Share
Year Quarter
2005 1                    0.023863
     2                    0.023863
     3                    0.023863
     4                    0.023863
2006 1                    0.017243

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2019 4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2019 4                         17539836.0         22236000.0
2020 1                         17295948.0         11249000.0
     2                         17135756.0         11253000.0
     3                                NaN                NaN
     4                                NaN                NaN

              Net Income Per Share
Year Quarter
2019 4                    1.267743
2020 1                    0.650384
     2                    0.656697
     3                         NaN
     4                         NaN

In [652]:
dec_df_copy = data_cleaning(IncomeStatement_Quarterly, 17, dec_df_copy)
dec_df_copy

Total Net Sales

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3994: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1                         23677280.0           565000.0
     2                         23677280.0           565000.0
     3                         23677280.0           565000.0
     4                         23677280.0           565000.0
2006 1                         23777268.0           410000.0
     2                         23777268.0           410000.0
     3                         23883653.0           472000.0
     4                         24086156.0          1004000.0
2007 1                         24211406.0           770000.0
     2                         24336530.0           818000.0
     3                         24601608.0          1581000.0
     4                         24601608.0          1581000.0
2008 1                         24680068.0          1045000.0
     2                         24800906.0          1072000.0
     3                         24931617.0          1605000.0
     4                         24931617.0          1605000.0
2009 1                         24973530.0          1205000.0
     2                         25080585.0          1229000.0
     3                         25375901.0          3378000.0
     4                         25375901.0          3378000.0
2010 1                         25469802.0          3074000.0
     2                         25577505.0          3253000.0
     3                         25788993.0          6004000.0
     4                         25788993.0          6004000.0
2011 1                         25890874.0          5987000.0
     2                         25953305.0          7308000.0
     3                         26101992.0         13064000.0
     4                         26101992.0         13064000.0
2012 1                         26179496.0         11622000.0
     2                         26243448.0          8824000.0
     3                         26291244.0         13078000.0
     4                         26291244.0         13078000.0
2013 1                         26322632.0          9547000.0
     2                         25436376.0          6900000.0
     3                         24988516.0         13072000.0
     4                         24988516.0         13072000.0
2014 1                         24128860.0         10223000.0
     2                         23956684.0          7748000.0
     3                         23305676.0         18024000.0
     4                         23305676.0         18024000.0
2015 1                         23049112.0         13569000.0
     2                         22821600.0         10677000.0
     3                         22177948.0         18361000.0
     4                         22177948.0         18361000.0
2016 1                         21913784.0         10516000.0
     2                         21572660.0          7796000.0
     3                         21021692.0         17891000.0
     4                         21021692.0         17891000.0
2017 1                         20823260.0         11029000.0
     2                         20823260.0         11029000.0
     3                         20679128.0          8717000.0
     4                         20326604.0         20065000.0
2018 1                         19773128.0         13822000.0
     2                         19371668.0         11519000.0
     3                         18919212.0         19965000.0
     4                         18919212.0         19965000.0
2019 1                         18429136.0         11561000.0
     2                         18125580.0         10044000.0
     3                         17539836.0         22236000.0
     4                         17539836.0         22236000.0
2020 1                         17295948.0         11249000.0
     2                         17135756.0         11253000.0
     3                                NaN                NaN
     4                                NaN                NaN

              Net Income Per Share
Year Quarter
2005 1                    0.023863
     2                    0.023863
     3                    0.023863
     4                    0.023863
2006 1                    0.017243
     2                    0.017243
     3                    0.019762
     4                    0.041684
2007 1                    0.031803
     2                    0.033612
     3                    0.064264
     4                    0.064264
2008 1                    0.042342
     2                    0.043224
     3                    0.064376
     4                    0.064376
2009 1                    0.048251
     2                    0.049002
     3                    0.133118
     4                    0.133118
2010 1                    0.120692
     2                    0.127182
     3                    0.232813
     4                    0.232813
2011 1                    0.231240
     2                    0.281583
     3                    0.500498
     4                    0.500498
2012 1                    0.443935
     2                    0.336236
     3                    0.497428
     4                    0.497428
2013 1                    0.362692
     2                    0.271265
     3                    0.523120
     4                    0.523120
2014 1                    0.423684
     2                    0.323417
     3                    0.773374
     4                    0.773374
2015 1                    0.588699
     2                    0.467846
     3                    0.827894
     4                    0.827894
2016 1                    0.479881
     2                    0.361383
     3                    0.851073
     4                    0.851073
2017 1                    0.529648
     2                    0.529648
     3                    0.421536
     4                    0.987130
2018 1                    0.699030
     2                    0.594631
     3                    1.055277
     4                    1.055277
2019 1                    0.627322
     2                    0.554134
     3                    1.267743
     4                    1.267743
2020 1                    0.650384
     2                    0.656697
     3                         NaN
     4                         NaN

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1                         23677280.0           565000.0
     2                         23677280.0           565000.0
     3                         23677280.0           565000.0
     4                         23677280.0           565000.0
2006 1                         23777268.0           410000.0
     2                         23777268.0           410000.0
     3                         23883653.0           472000.0
     4                         24086156.0          1004000.0
2007 1                         24211406.0           770000.0
     2                         24336530.0           818000.0
     3                         24601608.0          1581000.0
     4                         24601608.0          1581000.0
2008 1                         24680068.0          1045000.0
     2                         24800906.0          1072000.0
     3                         24931617.0          1605000.0
     4                         24931617.0          1605000.0
2009 1                         24973530.0          1205000.0
     2                         25080585.0          1229000.0
     3                         25375901.0          3378000.0
     4                         25375901.0          3378000.0
2010 1                         25469802.0          3074000.0
     2                         25577505.0          3253000.0
     3                         25788993.0          6004000.0
     4                         25788993.0          6004000.0
2011 1                         25890874.0          5987000.0
     2                         25953305.0          7308000.0
     3                         26101992.0         13064000.0
     4                         26101992.0         13064000.0
2012 1                         26179496.0         11622000.0
     2                         26243448.0          8824000.0
     3                         26291244.0         13078000.0
     4                         26291244.0         13078000.0
2013 1                         26322632.0          9547000.0
     2                         25436376.0          6900000.0
     3                         24988516.0         13072000.0
     4                         24988516.0         13072000.0
2014 1                         24128860.0         10223000.0
     2                         23956684.0          7748000.0
     3                         23305676.0         18024000.0
     4                         23305676.0         18024000.0
2015 1                         23049112.0         13569000.0
     2                         22821600.0         10677000.0
     3                         22177948.0         18361000.0
     4                         22177948.0         18361000.0
2016 1                         21913784.0         10516000.0
     2                         21572660.0          7796000.0
     3                         21021692.0         17891000.0
     4                         21021692.0         17891000.0
2017 1                         20823260.0         11029000.0
     2                         20823260.0         11029000.0
     3                         20679128.0          8717000.0
     4                         20326604.0         20065000.0
2018 1                         19773128.0         13822000.0
     2                         19371668.0         11519000.0
     3                         18919212.0         19965000.0
     4                         18919212.0         19965000.0
2019 1                         18429136.0         11561000.0
     2                         18125580.0         10044000.0
     3                         17539836.0         22236000.0
     4                         17539836.0         22236000.0
2020 1                         17295948.0         11249000.0
     2                         17135756.0         11253000.0
     3                                NaN                NaN
     4                                NaN                NaN

              Net Income Per Share  Total Net Sales
Year Quarter
2005 1                    0.023863              NaN
     2                    0.023863              NaN
     3                    0.023863              NaN
     4                    0.023863        5749000.0
2006 1                    0.017243              NaN
     2                    0.017243        4359000.0
     3                    0.019762        4370000.0
     4                    0.041684        7115000.0
2007 1                    0.031803        5264000.0
     2                    0.033612        5410000.0
     3                    0.064264              NaN
     4                    0.064264        9608000.0
2008 1                    0.042342        7512000.0
     2                    0.043224        7464000.0
     3                    0.064376              NaN
     4                    0.064376       10167000.0
2009 1                    0.048251        8163000.0
     2                    0.049002        8337000.0
     3                    0.133118              NaN
     4                    0.133118       15683000.0
2010 1                    0.120692       13499000.0
     2                    0.127182       15700000.0
     3                    0.232813              NaN
     4                    0.232813       26741000.0
2011 1                    0.231240       24667000.0
     2                    0.281583       28571000.0
     3                    0.500498              NaN
     4                    0.500498       46333000.0
2012 1                    0.443935       39186000.0
     2                    0.336236       35023000.0
     3                    0.497428              NaN
     4                    0.497428       54512000.0
2013 1                    0.362692       43603000.0
     2                    0.271265       35323000.0
     3                    0.523120              NaN
     4                    0.523120       57594000.0
2014 1                    0.423684       45646000.0
     2                    0.323417       37432000.0
     3                    0.773374              NaN
     4                    0.773374       74599000.0
2015 1                    0.588699       58010000.0
     2                    0.467846       49605000.0
     3                    0.827894              NaN
     4                    0.827894       75872000.0
2016 1                    0.479881       50557000.0
     2                    0.361383       42358000.0
     3                    0.851073              NaN
     4                    0.851073       78351000.0
2017 1                    0.529648              NaN
     2                    0.529648       52896000.0
     3                    0.421536       45408000.0
     4                    0.987130       88293000.0
2018 1                    0.699030       61137000.0
     2                    0.594631       53265000.0
     3                    1.055277              NaN
     4                    1.055277       84310000.0
2019 1                    0.627322       58015000.0
     2                    0.554134       53809000.0
     3                    1.267743              NaN
     4                    1.267743       91819000.0
2020 1                    0.650384       58313000.0
     2                    0.656697       59685000.0
     3                         NaN              NaN
     4                         NaN              NaN

                   Close        High         Low  Total Revenue  Avg_Shares  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0         NaN
     2          1.352740    1.375603    1.332132      5749000.0         NaN
     3          1.632829    1.650273    1.608292      5749000.0         NaN
     4          2.267874    2.295085    2.232783      5749000.0  24477796.0
2006 1          2.505685    2.559983    2.467074      4359000.0         NaN
     2          2.286786    2.328282    2.255096      4359000.0  24599036.0
     3          2.364666    2.395510    2.328226      4370000.0  24538304.0
     4          2.958299    2.993095    2.922098      7115000.0  24732316.0
2007 1          3.161434    3.198688    3.124374      5264000.0  24826284.0
     2          3.868152    3.911213    3.819632      5410000.0  24938788.0
     3          4.843560    4.917976    4.756417      9608000.0         NaN
     4          6.378103    6.478594    6.254314      9608000.0  25201512.0
2008 1          4.969239    5.091739    4.861475      7512000.0  25181212.0
     2          6.198811    6.287919    6.089431      7464000.0  25288676.0
     3          5.719330    5.841925    5.604046     10167000.0         NaN
     4          3.390580    3.504258    3.277282     10167000.0  25241832.0
2009 1          3.341932    3.404854    3.276996      8163000.0  25283804.0
     2          4.621905    4.674467    4.550397      8337000.0  25456480.0
     3          5.865184    5.913728    5.804018     15683000.0         NaN
     4          7.045586    7.121797    6.978984     15683000.0  25753924.0
2010 1          7.530539    7.605164    7.447541     13499000.0  25840584.0
     2          9.097817    9.215408    8.952097     15700000.0  25966108.0
     3          9.282327    9.375893    9.172846     26741000.0         NaN
     4         11.124810   11.199632   11.035692     26741000.0  26128312.0
2011 1         12.345830   12.433525   12.223433     24667000.0  26206432.0
     2         12.057585   12.168316   11.964943     28571000.0  26258680.0
     3         13.589654   13.743108   13.414397     46333000.0         NaN
     4         13.987806   14.123345   13.849422     46333000.0  26364016.0
2012 1         17.988566   18.112079   17.793992     39186000.0  26457004.0
     2         20.753220   21.005403   20.527902     35023000.0  26517652.0
     3         22.876553   23.032630   22.669093     54512000.0         NaN
     4         20.634424   20.927817   20.386187     54512000.0  26522076.0
2013 1         16.649083   16.863107   16.481637     43603000.0  26488980.0
     2         15.383677   15.582623   15.222015     35323000.0  25879420.0
     3         16.580195   16.742271   16.435720     57594000.0         NaN
     4         18.891892   19.033917   18.737980     57594000.0  25240656.0
2014 1         19.021592   19.174455   18.879549     45646000.0  24626784.0
     2         21.279382   21.413271   21.106015     37432000.0  24206844.0
     3         24.540859   24.739531   24.327422     74599000.0         NaN
     4         27.205313   27.465469   26.948008     74599000.0  23527212.0
2015 1         30.194262   30.514057   29.889016     58010000.0  23339432.0
     2         31.984524   32.242222   31.759048     49605000.0  23092396.0
     3         29.325859   29.688789   28.963242     75872000.0         NaN
     4         28.574844   28.839141   28.291836     75872000.0  22376508.0
2016 1         24.913770   25.169385   24.618688     50557000.0  22163544.0
     2         24.850313   25.066563   24.645742     42358000.0  21891124.0
     3         26.466523   26.629531   26.276172     78351000.0         NaN
     4         28.349762   28.540159   28.122936     78351000.0  21311980.0
2017 1         32.928145   33.041290   32.713387     52896000.0         NaN
     2         36.968849   37.205000   36.719960     52896000.0  21046752.0
     3         38.792262   39.065119   38.494127     45408000.0  20933996.0
     4         41.787064   42.018294   41.486230     88293000.0  20631148.0
2018 1         43.047828   43.524303   42.654017     61137000.0  20273972.0
     2         45.349141   45.678125   44.980117     53265000.0  19706436.0
     3         52.075000   52.473532   51.630238     84310000.0         NaN
     4         48.478016   49.216905   47.816468     84310000.0  19093008.0
2019 1         42.415943   42.764181   41.969795     58015000.0  18802584.0
     2         48.723175   49.139563   48.247698     53809000.0  18405520.0
     3         52.280195   52.753438   51.826523     91819000.0         NaN
     4         64.332187   64.668281   63.725820     91819000.0  17818416.0
2020 1         73.540927   74.693105   72.257581     58313000.0  17618764.0
     2         77.490317   78.341389   76.394960     59685000.0  17419152.0
     3        109.115351  110.836680  107.262734            NaN         NaN
     4        116.550244  118.171951  115.108536            NaN         NaN

              Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1                         23677280.0           565000.0
     2                         23677280.0           565000.0
     3                         23677280.0           565000.0
     4                         23677280.0           565000.0
2006 1                         23777268.0           410000.0
     2                         23777268.0           410000.0
     3                         23883653.0           472000.0
     4                         24086156.0          1004000.0
2007 1                         24211406.0           770000.0
     2                         24336530.0           818000.0
     3                         24601608.0          1581000.0
     4                         24601608.0          1581000.0
2008 1                         24680068.0          1045000.0
     2                         24800906.0          1072000.0
     3                         24931617.0          1605000.0
     4                         24931617.0          1605000.0
2009 1                         24973530.0          1205000.0
     2                         25080585.0          1229000.0
     3                         25375901.0          3378000.0
     4                         25375901.0          3378000.0
2010 1                         25469802.0          3074000.0
     2                         25577505.0          3253000.0
     3                         25788993.0          6004000.0
     4                         25788993.0          6004000.0
2011 1                         25890874.0          5987000.0
     2                         25953305.0          7308000.0
     3                         26101992.0         13064000.0
     4                         26101992.0         13064000.0
2012 1                         26179496.0         11622000.0
     2                         26243448.0          8824000.0
     3                         26291244.0         13078000.0
     4                         26291244.0         13078000.0
2013 1                         26322632.0          9547000.0
     2                         25436376.0          6900000.0
     3                         24988516.0         13072000.0
     4                         24988516.0         13072000.0
2014 1                         24128860.0         10223000.0
     2                         23956684.0          7748000.0
     3                         23305676.0         18024000.0
     4                         23305676.0         18024000.0
2015 1                         23049112.0         13569000.0
     2                         22821600.0         10677000.0
     3                         22177948.0         18361000.0
     4                         22177948.0         18361000.0
2016 1                         21913784.0         10516000.0
     2                         21572660.0          7796000.0
     3                         21021692.0         17891000.0
     4                         21021692.0         17891000.0
2017 1                         20823260.0         11029000.0
     2                         20823260.0         11029000.0
     3                         20679128.0          8717000.0
     4                         20326604.0         20065000.0
2018 1                         19773128.0         13822000.0
     2                         19371668.0         11519000.0
     3                         18919212.0         19965000.0
     4                         18919212.0         19965000.0
2019 1                         18429136.0         11561000.0
     2                         18125580.0         10044000.0
     3                         17539836.0         22236000.0
     4                         17539836.0         22236000.0
2020 1                         17295948.0         11249000.0
     2                         17135756.0         11253000.0
     3                                NaN                NaN
     4                                NaN                NaN

              Net Income Per Share  Total Net Sales
Year Quarter
2005 1                    0.023863        5749000.0
     2                    0.023863        5749000.0
     3                    0.023863        5749000.0
     4                    0.023863        5749000.0
2006 1                    0.017243        4359000.0
     2                    0.017243        4359000.0
     3                    0.019762        4370000.0
     4                    0.041684        7115000.0
2007 1                    0.031803        5264000.0
     2                    0.033612        5410000.0
     3                    0.064264        9608000.0
     4                    0.064264        9608000.0
2008 1                    0.042342        7512000.0
     2                    0.043224        7464000.0
     3                    0.064376       10167000.0
     4                    0.064376       10167000.0
2009 1                    0.048251        8163000.0
     2                    0.049002        8337000.0
     3                    0.133118       15683000.0
     4                    0.133118       15683000.0
2010 1                    0.120692       13499000.0
     2                    0.127182       15700000.0
     3                    0.232813       26741000.0
     4                    0.232813       26741000.0
2011 1                    0.231240       24667000.0
     2                    0.281583       28571000.0
     3                    0.500498       46333000.0
     4                    0.500498       46333000.0
2012 1                    0.443935       39186000.0
     2                    0.336236       35023000.0
     3                    0.497428       54512000.0
     4                    0.497428       54512000.0
2013 1                    0.362692       43603000.0
     2                    0.271265       35323000.0
     3                    0.523120       57594000.0
     4                    0.523120       57594000.0
2014 1                    0.423684       45646000.0
     2                    0.323417       37432000.0
     3                    0.773374       74599000.0
     4                    0.773374       74599000.0
2015 1                    0.588699       58010000.0
     2                    0.467846       49605000.0
     3                    0.827894       75872000.0
     4                    0.827894       75872000.0
2016 1                    0.479881       50557000.0
     2                    0.361383       42358000.0
     3                    0.851073       78351000.0
     4                    0.851073       78351000.0
2017 1                    0.529648       52896000.0
     2                    0.529648       52896000.0
     3                    0.421536       45408000.0
     4                    0.987130       88293000.0
2018 1                    0.699030       61137000.0
     2                    0.594631       53265000.0
     3                    1.055277       84310000.0
     4                    1.055277       84310000.0
2019 1                    0.627322       58015000.0
     2                    0.554134       53809000.0
     3                    1.267743       91819000.0
     4                    1.267743       91819000.0
2020 1                    0.650384       58313000.0
     2                    0.656697       59685000.0
     3                         NaN              NaN
     4                         NaN              NaN

In [653]:
dec_df_copy.insert(4, '%Rev Growth', (dec_df_copy['Total Revenue'].pct_change())*100)
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales
Year Quarter
2005 1                    0.023863        5749000.0
     2                    0.023863        5749000.0
     3                    0.023863        5749000.0
     4                    0.023863        5749000.0
2006 1                    0.017243        4359000.0

In [654]:
dec_df_copy['Sales Per Share'] = dec_df_copy['Total Net Sales']/dec_df_copy['Year End Shares Outstanding']
dec_df_copy.head(15)

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118
     2        2.286786  2.328282  2.255096      4359000.0     0.000000
     3        2.364666  2.395510  2.328226      4370000.0     0.252351
     4        2.958299  2.993095  2.922098      7115000.0    62.814645
2007 1        3.161434  3.198688  3.124374      5264000.0   -26.015460
     2        3.868152  3.911213  3.819632      5410000.0     2.773556
     3        4.843560  4.917976  4.756417      9608000.0    77.597043
     4        6.378103  6.478594  6.254314      9608000.0     0.000000
2008 1        4.969239  5.091739  4.861475      7512000.0   -21.815154
     2        6.198811  6.287919  6.089431      7464000.0    -0.638978
     3        5.719330  5.841925  5.604046     10167000.0    36.213826

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0
     2        24599036.0                   23777268.0           410000.0
     3        24538304.0                   23883653.0           472000.0
     4        24732316.0                   24086156.0          1004000.0
2007 1        24826284.0                   24211406.0           770000.0
     2        24938788.0                   24336530.0           818000.0
     3               NaN                   24601608.0          1581000.0
     4        25201512.0                   24601608.0          1581000.0
2008 1        25181212.0                   24680068.0          1045000.0
     2        25288676.0                   24800906.0          1072000.0
     3               NaN                   24931617.0          1605000.0

              Net Income Per Share  Total Net Sales  Sales Per Share
Year Quarter
2005 1                    0.023863        5749000.0         0.242807
     2                    0.023863        5749000.0         0.242807
     3                    0.023863        5749000.0         0.242807
     4                    0.023863        5749000.0         0.242807
2006 1                    0.017243        4359000.0         0.183326
     2                    0.017243        4359000.0         0.183326
     3                    0.019762        4370000.0         0.182970
     4                    0.041684        7115000.0         0.295398
2007 1                    0.031803        5264000.0         0.217418
     2                    0.033612        5410000.0         0.222300
     3                    0.064264        9608000.0         0.390544
     4                    0.064264        9608000.0         0.390544
2008 1                    0.042342        7512000.0         0.304375
     2                    0.043224        7464000.0         0.300957
     3                    0.064376       10167000.0         0.407795

In [655]:
dec_df_copy.insert(10, '%Annual Sales Growth', (dec_df_copy['Sales Per Share'].pct_change())*100)
dec_df_copy

                   Close        High         Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0          NaN
     2          1.352740    1.375603    1.332132      5749000.0     0.000000
     3          1.632829    1.650273    1.608292      5749000.0     0.000000
     4          2.267874    2.295085    2.232783      5749000.0     0.000000
2006 1          2.505685    2.559983    2.467074      4359000.0   -24.178118
     2          2.286786    2.328282    2.255096      4359000.0     0.000000
     3          2.364666    2.395510    2.328226      4370000.0     0.252351
     4          2.958299    2.993095    2.922098      7115000.0    62.814645
2007 1          3.161434    3.198688    3.124374      5264000.0   -26.015460
     2          3.868152    3.911213    3.819632      5410000.0     2.773556
     3          4.843560    4.917976    4.756417      9608000.0    77.597043
     4          6.378103    6.478594    6.254314      9608000.0     0.000000
2008 1          4.969239    5.091739    4.861475      7512000.0   -21.815154
     2          6.198811    6.287919    6.089431      7464000.0    -0.638978
     3          5.719330    5.841925    5.604046     10167000.0    36.213826
     4          3.390580    3.504258    3.277282     10167000.0     0.000000
2009 1          3.341932    3.404854    3.276996      8163000.0   -19.710829
     2          4.621905    4.674467    4.550397      8337000.0     2.131569
     3          5.865184    5.913728    5.804018     15683000.0    88.113230
     4          7.045586    7.121797    6.978984     15683000.0     0.000000
2010 1          7.530539    7.605164    7.447541     13499000.0   -13.925907
     2          9.097817    9.215408    8.952097     15700000.0    16.304911
     3          9.282327    9.375893    9.172846     26741000.0    70.324841
     4         11.124810   11.199632   11.035692     26741000.0     0.000000
2011 1         12.345830   12.433525   12.223433     24667000.0    -7.755880
     2         12.057585   12.168316   11.964943     28571000.0    15.826813
     3         13.589654   13.743108   13.414397     46333000.0    62.167933
     4         13.987806   14.123345   13.849422     46333000.0     0.000000
2012 1         17.988566   18.112079   17.793992     39186000.0   -15.425291
     2         20.753220   21.005403   20.527902     35023000.0   -10.623692
     3         22.876553   23.032630   22.669093     54512000.0    55.646290
     4         20.634424   20.927817   20.386187     54512000.0     0.000000
2013 1         16.649083   16.863107   16.481637     43603000.0   -20.012107
     2         15.383677   15.582623   15.222015     35323000.0   -18.989519
     3         16.580195   16.742271   16.435720     57594000.0    63.049571
     4         18.891892   19.033917   18.737980     57594000.0     0.000000
2014 1         19.021592   19.174455   18.879549     45646000.0   -20.745217
     2         21.279382   21.413271   21.106015     37432000.0   -17.995005
     3         24.540859   24.739531   24.327422     74599000.0    99.292050
     4         27.205313   27.465469   26.948008     74599000.0     0.000000
2015 1         30.194262   30.514057   29.889016     58010000.0   -22.237564
     2         31.984524   32.242222   31.759048     49605000.0   -14.488881
     3         29.325859   29.688789   28.963242     75872000.0    52.952323
     4         28.574844   28.839141   28.291836     75872000.0     0.000000
2016 1         24.913770   25.169385   24.618688     50557000.0   -33.365405
     2         24.850313   25.066563   24.645742     42358000.0   -16.217339
     3         26.466523   26.629531   26.276172     78351000.0    84.973323
     4         28.349762   28.540159   28.122936     78351000.0     0.000000
2017 1         32.928145   33.041290   32.713387     52896000.0   -32.488418
     2         36.968849   37.205000   36.719960     52896000.0     0.000000
     3         38.792262   39.065119   38.494127     45408000.0   -14.156080
     4         41.787064   42.018294   41.486230     88293000.0    94.443710
2018 1         43.047828   43.524303   42.654017     61137000.0   -30.756685
     2         45.349141   45.678125   44.980117     53265000.0   -12.876000
     3         52.075000   52.473532   51.630238     84310000.0    58.284051
     4         48.478016   49.216905   47.816468     84310000.0     0.000000
2019 1         42.415943   42.764181   41.969795     58015000.0   -31.188471
     2         48.723175   49.139563   48.247698     53809000.0    -7.249849
     3         52.280195   52.753438   51.826523     91819000.0    70.638741
     4         64.332187   64.668281   63.725820     91819000.0     0.000000
2020 1         73.540927   74.693105   72.257581     58313000.0   -36.491358
     2         77.490317   78.341389   76.394960     59685000.0     2.352820
     3        109.115351  110.836680  107.262734            NaN     0.000000
     4        116.550244  118.171951  115.108536            NaN     0.000000

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0
     2        24599036.0                   23777268.0           410000.0
     3        24538304.0                   23883653.0           472000.0
     4        24732316.0                   24086156.0          1004000.0
2007 1        24826284.0                   24211406.0           770000.0
     2        24938788.0                   24336530.0           818000.0
     3               NaN                   24601608.0          1581000.0
     4        25201512.0                   24601608.0          1581000.0
2008 1        25181212.0                   24680068.0          1045000.0
     2        25288676.0                   24800906.0          1072000.0
     3               NaN                   24931617.0          1605000.0
     4        25241832.0                   24931617.0          1605000.0
2009 1        25283804.0                   24973530.0          1205000.0
     2        25456480.0                   25080585.0          1229000.0
     3               NaN                   25375901.0          3378000.0
     4        25753924.0                   25375901.0          3378000.0
2010 1        25840584.0                   25469802.0          3074000.0
     2        25966108.0                   25577505.0          3253000.0
     3               NaN                   25788993.0          6004000.0
     4        26128312.0                   25788993.0          6004000.0
2011 1        26206432.0                   25890874.0          5987000.0
     2        26258680.0                   25953305.0          7308000.0
     3               NaN                   26101992.0         13064000.0
     4        26364016.0                   26101992.0         13064000.0
2012 1        26457004.0                   26179496.0         11622000.0
     2        26517652.0                   26243448.0          8824000.0
     3               NaN                   26291244.0         13078000.0
     4        26522076.0                   26291244.0         13078000.0
2013 1        26488980.0                   26322632.0          9547000.0
     2        25879420.0                   25436376.0          6900000.0
     3               NaN                   24988516.0         13072000.0
     4        25240656.0                   24988516.0         13072000.0
2014 1        24626784.0                   24128860.0         10223000.0
     2        24206844.0                   23956684.0          7748000.0
     3               NaN                   23305676.0         18024000.0
     4        23527212.0                   23305676.0         18024000.0
2015 1        23339432.0                   23049112.0         13569000.0
     2        23092396.0                   22821600.0         10677000.0
     3               NaN                   22177948.0         18361000.0
     4        22376508.0                   22177948.0         18361000.0
2016 1        22163544.0                   21913784.0         10516000.0
     2        21891124.0                   21572660.0          7796000.0
     3               NaN                   21021692.0         17891000.0
     4        21311980.0                   21021692.0         17891000.0
2017 1               NaN                   20823260.0         11029000.0
     2        21046752.0                   20823260.0         11029000.0
     3        20933996.0                   20679128.0          8717000.0
     4        20631148.0                   20326604.0         20065000.0
2018 1        20273972.0                   19773128.0         13822000.0
     2        19706436.0                   19371668.0         11519000.0
     3               NaN                   18919212.0         19965000.0
     4        19093008.0                   18919212.0         19965000.0
2019 1        18802584.0                   18429136.0         11561000.0
     2        18405520.0                   18125580.0         10044000.0
     3               NaN                   17539836.0         22236000.0
     4        17818416.0                   17539836.0         22236000.0
2020 1        17618764.0                   17295948.0         11249000.0
     2        17419152.0                   17135756.0         11253000.0
     3               NaN                          NaN                NaN
     4               NaN                          NaN                NaN

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964
     2                    0.017243        4359000.0              0.000000
     3                    0.019762        4370000.0             -0.194203
     4                    0.041684        7115000.0             61.445790
2007 1                    0.031803        5264000.0            -26.398196
     2                    0.033612        5410000.0              2.245156
     3                    0.064264        9608000.0             75.683466
     4                    0.064264        9608000.0              0.000000
2008 1                    0.042342        7512000.0            -22.063710
     2                    0.043224        7464000.0             -1.123097
     3                    0.064376       10167000.0             35.499687
     4                    0.064376       10167000.0              0.000000
2009 1                    0.048251        8163000.0            -19.845578
     2                    0.049002        8337000.0              1.695627
     3                    0.133118       15683000.0             85.924033
     4                    0.133118       15683000.0              0.000000
2010 1                    0.120692       13499000.0            -14.243241
     2                    0.127182       15700000.0             15.815169
     3                    0.232813       26741000.0             68.928056
     4                    0.232813       26741000.0              0.000000
2011 1                    0.231240       24667000.0             -8.118863
     2                    0.281583       28571000.0             15.548190
     3                    0.500498       46333000.0             61.244162
     4                    0.500498       46333000.0              0.000000
2012 1                    0.443935       39186000.0            -15.675673
     2                    0.336236       35023000.0            -10.841491
     3                    0.497428       54512000.0             55.363333
     4                    0.497428       54512000.0              0.000000
2013 1                    0.362692       43603000.0            -20.107488
     2                    0.271265       35323000.0            -16.166946
     3                    0.523120       57594000.0             65.971849
     4                    0.523120       57594000.0              0.000000
2014 1                    0.423684       45646000.0            -17.921550
     2                    0.323417       37432000.0            -17.405637
     3                    0.773374       74599000.0            104.858965
     4                    0.773374       74599000.0              0.000000
2015 1                    0.588699       58010000.0            -21.371975
     2                    0.467846       49605000.0            -13.636408
     3                    0.827894       75872000.0             57.391330
     4                    0.827894       75872000.0              0.000000
2016 1                    0.479881       50557000.0            -32.562145
     2                    0.361383       42358000.0            -14.892501
     3                    0.851073       78351000.0             89.821381
     4                    0.851073       78351000.0              0.000000
2017 1                    0.529648       52896000.0            -31.845076
     2                    0.529648       52896000.0              0.000000
     3                    0.421536       45408000.0            -13.557754
     4                    0.987130       88293000.0             97.815945
2018 1                    0.699030       61137000.0            -28.818473
     2                    0.594631       53265000.0            -11.070435
     3                    1.055277       84310000.0             62.069440
     4                    1.055277       84310000.0              0.000000
2019 1                    0.627322       58015000.0            -29.358604
     2                    0.554134       53809000.0             -5.696527
     3                    1.267743       91819000.0             76.337233
     4                    1.267743       91819000.0              0.000000
2020 1                    0.650384       58313000.0            -35.595831
     2                    0.656697       59685000.0              3.309656
     3                         NaN              NaN              0.000000
     4                         NaN              NaN              0.000000

              Sales Per Share
Year Quarter
2005 1               0.242807
     2               0.242807
     3               0.242807
     4               0.242807
2006 1               0.183326
     2               0.183326
     3               0.182970
     4               0.295398
2007 1               0.217418
     2               0.222300
     3               0.390544
     4               0.390544
2008 1               0.304375
     2               0.300957
     3               0.407795
     4               0.407795
2009 1               0.326866
     2               0.332409
     3               0.618027
     4               0.618027
2010 1               0.530000
     2               0.613821
     3               1.036915
     4               1.036915
2011 1               0.952730
     2               1.100862
     3               1.775075
     4               1.775075
2012 1               1.496820
     2               1.334543
     3               2.073390
     4               2.073390
2013 1               1.656483
     2               1.388681
     3               2.304819
     4               2.304819
2014 1               1.891759
     2               1.562487
     3               3.200894
     4               3.200894
2015 1               2.516800
     2               2.173599
     3               3.421056
     4               3.421056
2016 1               2.307087
     2               1.963504
     3               3.727150
     4               3.727150
2017 1               2.540236
     2               2.540236
     3               2.195837
     4               4.343716
2018 1               3.091924
     2               2.749634
     3               4.456317
     4               4.456317
2019 1               3.148004
     2               2.968677
     3               5.234884
     4               5.234884
2020 1               3.371483
     2               3.483068
     3                    NaN
     4                    NaN

In [656]:
dec_df_copy.index.name = "Symbol: "+ get_stock_info
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share
Year Quarter
2005 1               0.242807
     2               0.242807
     3               0.242807
     4               0.242807
2006 1               0.183326

In [657]:
len_hist_data = len(dec_df_copy.index)/4
start_year = int((dt.now().year - len_hist_data) + 1)
start_year

2005

In [658]:
# results = requests.get('http://www.marketwatch.com/investing/stock/{}/financials'.format(get_stock_info))
# print(results)
# # print(results.headers)
# src = results.content
# Soup = BeautifulSoup(src, 'lxml')
# links = Soup.find_all('a')
# # print(links)
# for link in links:
#     if 'EPS' in  link:
#         print(link)
#         print(link.attr['href'])

In [659]:
#Adding high and low range for price per Annual Sales
dec_df_copy['High Price/Share'] = dec_df_copy["Sales Per Share"]/dec_df_copy["High"]
dec_df_copy['Low Price/Share'] = dec_df_copy["Sales Per Share"]/dec_df_copy["Low"]
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

In [660]:
#key historic metrics from FinancialModelingPrep & Yahoo Finance (good source)
import FundamentalAnalysis as fa

# Variables
ticker = "AAPL"
api_key = '71b43c3b9db8001d692abeb097117fd9'


# get enterprise value
enterprise_value = fa.enterprise(ticker, api_key, period="quarter")
enterprise_value

,2020-09,2020-06,2020-03,2019-12,2019-09,2019-06,2019-03,2018-12,2018-09,2018-06,2018-03,2017-12,2017-09,2017-07,2017-04,2016-12,2016-09,2016-06,2016-03,2015-12,2015-09,2015-06,2015-03,2014-12,2014-09,2014-06,2014-03,2013-12,2013-09,2013-06,2013-03,2012-12,2012-09,2012-06,2012-03,2011-12,2011-09,2011-06,2011-03,2010-12,2010-09,2010-06,2010-03,2009-12,2009-09,2009-06,2009-03,2008-12,2008-09,2008-06,2008-03,2007-12,2007-09,2007-06,2007-03,2006-12,2006-09,2006-07,2006-04,2005-12,2005-09,2005-06,2005-03,2004-12,2004-09,2004-06,2004-03,2003-12,2003-09,2003-06,2003-03,2002-12,2002-09,2002-06,2002-03,2001-12,2001-09,2001-06,2001-03,2000-12,2000-09,2000-07,2000-04,2000-01,1999-09,1999-06,1999-03,1998-12,1998-09,1998-06,1998-03,1997-12,1997-09,1997-06,1997-03,1996-12,1996-09,1996-06,1996-03,1995-12,1995-09,1995-06,1995-03,1994-12,1994-09,1994-07,1994-04,1993-12,1993-09,1993-06,1993-03,1992-12,1992-09,1992-06,1992-03,1991-12,1991-09,1991-06,1991-03,1990-12,1990-09,1990-06,1990-03,1989-12,1989-09
symbol,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
stockPrice,112.28,88.4075,61.935,72.45,54.705,49.48,47.4875,39.0575,56.435,46.2775,41.67,42.3075,38.53,36.005,35.915,28.955,28.1775,23.35,26.2975,26.705,28.6775,31.6875,30.8125,28.4975,25.1875,22.995,19.1736,20.0032,17.2411,14.1618,15.3182,18.1996,23.825,20.8571,21.4125,14.4643,14.4393,11.6554,12.555,11.5957,10.44,9.525,8.24643,7.5575,6.51321,5.08714,3.81607,3.06464,4.58,6.07464,5.1075,7.13679,5.48107,4.35857,3.31821,3.03,2.74929,2.04536,2.24,2.5675,1.9,1.34857,1.51893,1.12786,0.665893,0.601786,0.482857,0.371071,0.369464,0.334464,0.260179,0.251071,0.262857,0.316429,0.436786,0.400536,0.276964,0.415179,0.394107,0.265625,0.459821,0.935268,1.21261,0.917969,0.579799,0.376674,0.296875,0.364955,0.345982,0.251674,0.240513,0.118862,0.19029,0.131138,0.166295,0.206473,0.199219,0.1875,0.219308,0.284598,0.332589,0.414621,0.314732,0.348214,0.300781,0.229911,0.296875,0.261161,0.223214,0.357143,0.475446,0.526786,0.40625,0.404018,0.544643,0.491071,0.4375,0.370536,0.607143,0.383929,0.258929,0.399554,0.359375,0.314732,0.397321
numberOfShares,17352119000,17419152000,17618764000,17818416000,18081500000,18405520000,18802584000,19093008000,19392000000,19528668000,20099508000,20632000000,20597712000,20932000000,21048000000,21194644000,21572000000,21892000000,22164000000,22376000000,22732000000,23092000000,23340000000,23528000000,23888000000,24208000000,24628000000,25240000000,25456000000,25880000000,26488000000,26524000000,26548000000,26224688000,26140296000,26069148000,26308000000,26260000000,26208000000,26128000000,26008000000,25968000000,25840000000,25752000000,25604000000,25456000000,25284000000,25240000000,25336000000,25288000000,25180000000,25200000000,25080000000,24270568000,24164084000,24732000000,0,24540000000,24600000000,23261868000,24260000000,24100000000,23896000000,23468000000,22564000000,21988000000,21180000000,20848000000,20760000000,20372000000,20284000000,20108000000,20100000000,20544000000,20492000000,20020000000,19964000000,19530840000,19380480000,18880000000,0,20260000000,20384000000,19984000000,19796000000,19560000000,19400000000,19272000000,22728000000,19240000000,16344000000,15660000000,14292000000,14168000000,14068000000,13948000000,13948000000,13860000000,13848000000,13776000000,13972000000,13798736000,13736128000,13624000000,0,13312000000,13320000000,13100000000,13304000000,12956000000,13540000000,13568000000,13536000000,13768000000,13892000000,13680000000,13580000000,13420000000,13680000000,13208000000,13700000000,13940000000,14220000000,14504000000,14548000000
marketCapitalization,1.9483e+12,1.53998e+12,1.09122e+12,1.29094e+12,989148493663,910705129600,8.92888e+11,7.45725e+11,1094387539392,9.03738e+11,8.37546e+11,872888319368,7.9363e+11,753656680932,7.55939e+11,613690917020,607845030000,5.11178e+11,582857812164,597551080000,651896930000,731727750000,719163750000,670489156472,601679000000,556662984208,472206706588,504881121360,438888728832,366507021680,405748852432,482727304408,632506126548,5.46972e+11,559729088100,3.77072e+11,379868709780,306069674820,329041440000,302972841520,271523520000,247345200000,213087699520,194620740000,166764331256,129498312208,96485564448,77351589320,116038880000,153615572184,128606850000,179847007200,137465260680,1.05785e+11,8.01816e+10,74937960000,0,50193060780,5.5104e+10,59724846090,46094000000,32500561100,36296327384,2.64685e+10,1.50252e+10,13232070568,10226911260,7736088208,7670072640,6813700608,5277470836,5048535668,5283425700,6500717376,8950618712,8018730720,5529309296,8.10879e+09,7.63798e+09,5015000000,0,18948529680,24717883008,18344692496,11477701004,7367743440,5759375000,7.03341e+09,7863478896,4842207760,3930944472,1861378920,2719624680,1857963184,2339438060,2879885404,2778706612,2598750000,3036977184,3.92062e+09,4646933508,5.72125e+09,4.3232e+09,4744067536,0,3060575232,3954375000,3.42121e+09,2969639056,4627144708,6437538840,7147432448,5499000000,5562519824,7566180556,6717851280,5941250000,4972593120,8305716240,5070934232,3.54733e+09,5569782760,5110312500,4564872928,5780225908
minusCashAndCashEquivalents,38016000000,33383000000,40174000000,39771000000,48844000000,50530000000,37988000000,44771000000,25913000000,31971000000,45059000000,27491000000,20289000000,18571000000,15157000000,16371000000,20484000000,18237000000,21514000000,16689000000,21120000000,15319000000,14489000000,19478000000,13844000000,12977000000,18949000000,14077000000,14259000000,11248000000,12053000000,16154000000,10746000000,7945000000,10121000000,10310000000,9815000000,12091000000,15978000000,10734000000,11261000000,9705000000,10018000000,7609000000,5263000000,5605000000,4466000000,7236000000,11875000000,9373000000,9070000000,9162000000,9352000000,7118000000,7095000000,7159000000,6392000000,8013000000,6346000000,4150000000,3491000000,3094000000,2254000000,2475000000,2969000000,3120000000,3158000000,3724000000,3396000000,3507000000,3410000000,2612000000,2252000000,1246000000,1159000000,1946000000,2310000000,2121000000,2138000000,1737000000,1191000000,1344000000,1662000000,1586000000,1326000000,1773000000,1358000000,1221000000,1481000000,1203000000,1285000000,1193000000,1230000000,1018000000,1273000000,1174000000,1552000000,1359000000,500000000,824000000,756000000,1168000000,1375000000,1148000000,1203488000,1142000000,1087000000,972000000,676000000,393000000,561000000,584000000,499000000,731000000,767000000,530000000,604000000,774000000,874000000,739000000,375000000,665000000,646000000,411000000,438000000
addTotalDebt,107440000000,105844000000,99744000000,98695000000,97787000000,94889000000,102125000000,104958000000,105699000000,136127000000,144243000000,115902000000,151099000000,101844000000,94523000000,117638000000,83532000000,81435000000,77372000000,60463000000,61828000000,51918000000,43871000000,36403000000,35295000000,31040000000,16962000000,16961000000,16960000000,16958000000,0,0,0,19709000000,18417000000,19846000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6649000000,5482000000,0,3718000000,0,0,4557000000,0,0,0,0,0,0,0,0,0,0,0,320000000,316000000,316000000,311000000,315000000,317000000,2414000000,2323000000,311000000,3136000000,300000000,300000000,300000000,300000000,300000000,955000000,954000000,954000000,953000000,976000000,976000000,976000000,1078000000,1085000000,1130000000,1135000000,1136000000,655000000,802000000,764000000,811000000,915000000,513000000,358840000,821000000,796000000,752000000,830000000,308000000,60000000,191000000,184000000,180000000,136000000,46000000,149000000,156000000,6000000,23000000,123000000,25000000,20000000,68000000,57000000
enterpriseValue,2.01772e+12,1.61244e+12,1.15079e+12,1.34987e+12,1038091493663,955064129600,9.57025e+11,8.05912e+11,1174173539392,1.00789e+12,9.3673e+11,961299319368,9.2444e+11,836929680932,8.35305e+11,714957917020,670893030000,574376200000,638715812164,641325080000,692604930000,768326750000,748545750000,687414156472,623130000000,574725984208,470219706588,507765121360,441589728832,372217021680,393695852432,466573304408,621760126548,5.58736e+11,568025088100,3.86608e+11,370053709780,293978674820,313063440000,292238841520,260262520000,237640200000,203069699520,187011740000,161501331256,123893312208,92019564448,70115589320,104163880000,144242572184,119536850000,170685007200,128113260680,1.05316e+11,7.85686e+10,67778960000,-2674000000,42180060780,4.8758e+10,60131846090,42603000000,29406561100,34042327384,2.39935e+10,1.20562e+10,10112070568,7068911260,4012088208,4274072640,3306700608,1867470836,2756535668,3347425700,5570717376,8102618712,6387730720,3536309296,8.40179e+09,7.82298e+09,3589000000,1945000000,17904529680,23355883008,17058692496,10451701004,5894743440,5356375000,6.76641e+09,7336478896,4592207760,3621944472,1644378920,2465624680,1917963184,2151438060,2835885404,2361706612,2375750000,3191977184,3.89862e+09,4654933508,5.36425e+09,3.8632e+09,4109067536,-844648000,2739575232,3663375000,3.20121e+09,3123639056,4542144708,5936538840,6754432448,5184000000,5011519824,6935180556,6233851280,5486250000,4354593120,7437716240,4354934232,3.29533e+09,4929782760,4484312500,4221872928,5399225908

In [661]:
#setting the DataFrame options so it shows actual number instead of the 
# number e to the power of another number
# pd.set_option('display.float_format', lambda x: '%.2f' % x)
# dec_df['3 Year Average High'] =

In [662]:
key_mtrcs = fa.key_metrics(ticker, api_key, period="quarter")
key_mtrcs.head()

,2020-09,2020-06,2020-03,2019-12,2019-09,2019-06,2019-03,2018-12,2018-09,2018-06,2018-03,2017-12,2017-09,2017-07,2017-04,2016-12,2016-09,2016-06,2016-03,2015-12,2015-09,2015-06,2015-03,2014-12,2014-09,2014-06,2014-03,2013-12,2013-09,2013-06,2013-03,2012-12,2012-09,2012-06,2012-03,2011-12,2011-09,2011-06,2011-03,2010-12,2010-09,2010-06,2010-03,2009-12,2009-09,2009-06,2009-03,2008-12,2008-09,2008-06,2008-03,2007-12,2007-09,2007-06,2007-03,2006-12,2006-09,2006-07,2006-04,2005-12,2005-09,2005-06,2005-03,2004-12,2004-09,2004-06,2004-03,2003-12,2003-09,2003-06,2003-03,2002-12,2002-09,2002-06,2002-03,2001-12,2001-09,2001-06,2001-03,2000-12,2000-09,2000-07,2000-04,2000-01,1999-09,1999-06,1999-03,1998-12,1998-09,1998-06,1998-03,1997-12,1997-09,1997-06,1997-03,1996-12,1996-09,1996-06,1996-03,1995-12,1995-09,1995-06,1995-03,1994-12,1994-09,1994-07,1994-04,1993-12,1993-09,1993-06,1993-03,1992-12,1992-09,1992-06,1992-03,1991-12,1991-09,1991-06,1991-03,1990-12,1990-09,1990-06,1990-03,1989-12,1989-09
revenuePerShare,3.728536,3.426401,3.309710,5.153039,3.541742,2.923525,3.085480,4.415753,3.243606,2.727529,3.041716,4.279420,2.552662,2.169310,2.513113,3.696736,2.171889,1.934862,2.281041,3.390776,2.265573,2.148147,2.485433,3.170648,1.763354,1.546266,1.853419,2.281854,1.472030,1.364876,1.646142,2.055195,1.354754,1.335497,1.499065,1.777312,1.074578,1.088005,0.941201,1.023461,0.782182,0.604590,0.522407,0.609001,0.476761,0.382385,0.359279,0.470681,0.454689,0.298996,0.316918,0.413889,0.263397,0.222904,0.217844,0.288007,NaN,0.178077,0.177195,0.247143,0.151608,0.146058,0.135713,0.148713,0.104148,0.091595,0.090132,0.096220,0.082611,0.075839,0.072717,0.073205,0.071791,0.069558,0.072955,0.068681,0.072631,0.075522,0.073837,0.053337,NaN,0.090079,0.095418,0.117244,0.067488,0.079652,0.078866,0.088730,0.068462,0.072869,0.085964,0.100766,0.112930,0.122600,0.113804,0.152638,0.166404,0.157215,0.157785,0.228513,0.214930,0.186611,0.193068,0.207868,NaN,0.161508,0.155931,0.188473,0.160929,0.143717,0.145790,0.147406,0.130615,0.126380,0.123524,0.136184,0.110972,0.113934,0.116813,0.126893,0.098832,0.097920,0.094655,0.102937,0.095133
netIncomePerShare,0.730343,0.646013,0.638467,1.247922,0.756906,0.545706,0.614862,1.045671,0.728393,0.589851,0.687679,0.972518,0.520155,0.416444,0.523993,0.844128,0.417856,0.356112,0.474463,0.820567,0.489354,0.462368,0.581362,0.766066,0.354446,0.320059,0.415097,0.517908,0.295097,0.266615,0.360427,0.493063,0.309741,0.336477,0.444601,0.501129,0.251749,0.278294,0.228442,0.229792,0.165641,0.125270,0.118963,0.131174,0.098891,0.071810,0.064072,0.089342,0.088688,0.044725,0.043725,0.065079,0.034689,0.033703,0.031865,0.040878,NaN,0.019234,0.016667,0.024289,0.017725,0.013278,0.011927,0.012570,0.004698,0.002774,0.002172,0.003022,0.002119,0.000933,0.000690,-0.000398,-0.002239,0.001558,0.001952,0.001898,0.003306,0.003123,0.002219,-0.010328,NaN,0.009872,0.011431,0.009157,0.005607,0.010378,0.006959,0.007887,0.004664,0.005249,0.003365,0.003001,-0.011265,-0.003953,-0.050327,-0.008603,0.001792,-0.002309,-0.053437,-0.005009,0.004294,0.007464,0.005314,0.013799,NaN,0.010367,0.001276,0.003053,0.000225,-0.014511,0.008198,0.011866,0.007240,0.009587,0.009718,0.012135,0.005965,-0.003949,0.009576,0.011432,0.007153,0.008608,0.009283,0.008618,0.011067
operatingCashFlowPerShare,1.185792,0.934087,0.755501,1.712610,1.101125,0.632202,0.593270,1.397894,1.006755,0.741884,0.752755,1.371316,0.760084,0.388783,0.597206,1.276549,0.747543,0.485748,0.523416,1.227342,0.592777,0.649056,0.817524,1.433271,0.554672,0.423620,0.549700,0.898177,0.389221,0.302473,0.472063,0.883200,0.344131,0.388527,0.534692,0.673363,0.396419,0.423001,0.237294,0.374043,0.218510,0.184881,0.090170,0.224487,0.121465,0.089173,0.033262,0.156022,0.169522,0.052238,0.047379,0.110595,0.067624,0.050555,0.030376,0.073306,NaN,0.041035,-0.005081,0.012166,0.030998,0.019585,0.022431,0.033024,0.019633,0.009596,0.002880,0.010505,0.003516,0.000393,0.004831,0.005470,0.004129,-0.001801,0.000098,0.002098,0.013775,-0.001690,-0.002270,-0.000689,NaN,0.011550,0.002993,0.018665,0.012225,0.004499,0.013866,0.011571,0.012408,0.010707,0.009484,0.008429,0.011125,-0.014540,0.007748,0.006596,0.021222,0.020707,-0.026141,0.013574,-0.048168,-0.001957,0.000510,0.033250,NaN,0.010667,-0.001276,0.028244,-0.029991,-0.021920,-0.003471,0.005823,0.004285,0.017141,0.022819,0.022661,0.008542,-0.010134,-0.001316,0.017187,0.007153,0.021664,0.021308,0.017995,0.005362
freeCashFlowPerShare,1.082980,0.844243,0.650329,1.594362,0.947543,0.523539,0.467595,1.222175,0.849938,0.574591,0.551705,1.227656,0.565888,0.270017,0.459949,1.115187,0.560356,0.353051,0.406154,1.048311,0.431858,0.558592,0.711440,1.294500,0.393419,0.323199,0.489362,0.817195,0.298633,0.224575,0.385269,0.790642,0.212257,0.275542,0.476965,0.618547,0.222670,0.386367,0.212263,0.325704,0.187250,0.160775,0.078522,0.209692,0.103031,0.078488,0.028674,0.142036,0.152865,0.039189,0.038840,0.101389,0.058293,0.038648,0.021851,0.062914,NaN,0.031377,-0.012927,0.008641,0.027040,0.016971,0.020631,0.030552,0.017018,0.007868,0.001228,0.008394,0.000723,-0.001865,0.002859,0.004476,0.000945,-0.003310,-0.002001,0.000300,0.005610,-0.003226,-0.003147,-0.001854,NaN,0.011007,0.001668,0.016763,0.010204,0.004141,0.012887,0.011312,0.011660,0.009304,0.009178,0.007982,0.010355,-0.014963,0.006611,0.005162,0.020361,0.019769,-0.026935,0.011324,-0.051675,-0.006160,-0.001674,0.031635,NaN,0.008864,-0.006907,0.026412,-0.033599,-0.027478,-0.007090,0.002580,0.001034,0.013001,0.019796,0.018860,0.004786,-0.014158,-0.004167,0.011584,0.002190,0.018077,0.018284,0.013651,0.001237
cashPerShare,2.190856,1.916454,2.280183,2.232017,2.701325,2.745372,2.020361,2.344890,1.336273,1.637132,2.241796,1.332445,0.985012,0.887206,0.720116,0.772412,0.949564,0.833044,0.970673,0.745844,0.929087,0.663390,0.620780,0.827865,0.579538,0.536062,0.769409,0.557726,0.560143,0.434621,0.455036,0.609033,0.404776,0.302959,0.387180,0.395487,0.373080,0.460434,0.609661,0.410824,0.432982,0.373729,0.387693,0.295472,0.205554,0.220184,0.176633,0.286688,0.468701,0.370650,0.360207,0.363571,0.372887,0.293277,0.293618,0.289463,NaN,0.326528,0.257967,0.178404,0.143899,0.128382,0.094325,0.105463,0.131581,0.141896,0.149103,0.178626,0.163584,0.172148,0.168113,0.129899,0.112040,0.060650,0.056559,0.097203,0.115708,0.108597,0.110317,0.092002,NaN,0.066338,0.081535,0.079363,0.066983,0.090644,0.070000,0.063356,0.065162,0.062526,0.078622,0.076181,0.086062,0.071852,0.090489,0.084170,0.111270,0.098052,0.036106,0.059814,0.054108,0.084645,0.100101,0.084263,NaN,0.085787,0.081607,0.074198,0.050812,0.030333,0.041433,0.043042,0.036865,0.053094,0.055212,0.038743,0.044477,0.057675,0.063889,0.055951,0.027372,0.047704,0.045429,0.028337,0.030107

In [663]:
key_metrics = key_mtrcs.T
key_mtrcs.index.get_loc('peRatio')
key_metrics = key_metrics.reset_index().rename(columns={'index': "Date"})
key_metrics.T.sort_index()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124
Date,2020-09,2020-06,2020-03,2019-12,2019-09,2019-06,2019-03,2018-12,2018-09,2018-06,2018-03,2017-12,2017-09,2017-07,2017-04,2016-12,2016-09,2016-06,2016-03,2015-12,2015-09,2015-06,2015-03,2014-12,2014-09,2014-06,2014-03,2013-12,2013-09,2013-06,2013-03,2012-12,2012-09,2012-06,2012-03,2011-12,2011-09,2011-06,2011-03,2010-12,2010-09,2010-06,2010-03,2009-12,2009-09,2009-06,2009-03,2008-12,2008-09,2008-06,2008-03,2007-12,2007-09,2007-06,2007-03,2006-12,2006-09,2006-07,2006-04,2005-12,2005-09,2005-06,2005-03,2004-12,2004-09,2004-06,2004-03,2003-12,2003-09,2003-06,2003-03,2002-12,2002-09,2002-06,2002-03,2001-12,2001-09,2001-06,2001-03,2000-12,2000-09,2000-07,2000-04,2000-01,1999-09,1999-06,1999-03,1998-12,1998-09,1998-06,1998-03,1997-12,1997-09,1997-06,1997-03,1996-12,1996-09,1996-06,1996-03,1995-12,1995-09,1995-06,1995-03,1994-12,1994-09,1994-07,1994-04,1993-12,1993-09,1993-06,1993-03,1992-12,1992-09,1992-06,1992-03,1991-12,1991-09,1991-06,1991-03,1990-12,1990-09,1990-06,1990-03,1989-12,1989-09
averageInventory,4.0195e+09,3.978e+09,3.656e+09,4.0375e+09,4.042e+09,3.6665e+09,4.431e+09,4.483e+09,3.967e+09,4.957e+09,5.82e+09,4.1995e+09,4.4165e+09,3.562e+09,3.444e+09,3.345e+09,3.055e+09,2.9045e+09,3.1295e+09,3.2145e+09,3.1635e+09,3.01e+09,3.187e+09,3.1305e+09,3.0445e+09,2.786e+09,2.9035e+09,3.05e+09,2.871e+09,2.8375e+09,2.6115e+09,2.7165e+09,2.3845e+09,2.55e+09,2.54e+09,2.607e+09,2.377e+09,2.4335e+09,2.454e+09,2.4315e+09,2.5145e+09,2.46e+09,2.308e+09,2.277e+09,2.2165e+09,2.179e+09,2.145e+09,2.187e+09,2.2435e+09,2.2615e+09,2.171e+09,2.2185e+09,2.162e+09,2.1145e+09,2.093e+09,2.1405e+09,2.124e+09,2.0955e+09,2.091e+09,2.111e+09,2.0715e+09,2.0855e+09,2.071e+09,2.067e+09,2.0395e+09,2.025e+09,2.0205e+09,2.0335e+09,2.017e+09,2.008e+09,2.0095e+09,2.011e+09,2.0115e+09,2.006e+09,2.002e+09,2.0005e+09,1.9945e+09,1.9985e+09,1.994e+09,1.9995e+09,2.0055e+09,1.9915e+09,1.994e+09,1.9965e+09,1.999e+09,1.9925e+09,1.998e+09,2.0015e+09,2.028e+09,2.0535e+09,2.1175e+09,2.191e+09,2.2075e+09,2.256e+09,2.2435e+09,2.233e+09,2.32e+09,2.5195e+09,2.722e+09,2.9625e+09,2.8765e+09,2.6725e+09,2.481e+09,2.531e+09,2.53322e+09,2.5875e+09,2.6325e+09,2.6585e+09,2.7425e+09,2.6085e+09,2.4275e+09,2.2875e+09,2.279e+09,2.257e+09,2.2605e+09,2.3105e+09,2.325e+09,2.3555e+09,2.2995e+09,2.1935e+09,2.1665e+09,2.135e+09,2.145e+09,2.2025e+09,2.2265e+09
averagePayables,3.88105e+10,3.5325e+10,3.3873e+10,4.0218e+10,4.07805e+10,3.222e+10,3.2884e+10,3.9809e+10,4.56065e+10,3.6907e+10,3.4818e+10,4.9155e+10,4.2187e+10,3.362e+10,3.1949e+10,3.69175e+10,3.63095e+10,3.08215e+10,3.02115e+10,3.43185e+10,3.54075e+10,3.08995e+10,2.9242e+10,3.6663e+10,3.27605e+10,2.793e+10,2.71195e+10,3.24565e+10,2.8846e+10,2.54205e+10,2.51185e+10,3.08615e+10,2.825e+10,2.60665e+10,2.6168e+10,2.6773e+10,2.49785e+10,2.52975e+10,2.45195e+10,2.4813e+10,2.367e+10,2.1897e+10,2.04955e+10,2.0918e+10,2.0463e+10,2.00895e+10,1.96505e+10,2.002e+10,2.04225e+10,1.9504e+10,1.97395e+10,2.03455e+10,2.01475e+10,1.94925e+10,1.8864e+10,1.9605e+10,1.93575e+10,1.8919e+10,1.87165e+10,1.91105e+10,1.8552e+10,1.84275e+10,1.8549e+10,1.8531e+10,1.8388e+10,1.8193e+10,1.8158e+10,1.8205e+10,1.82395e+10,1.81025e+10,1.8123e+10,1.8071e+10,1.8118e+10,1.81145e+10,1.8156e+10,1.80775e+10,1.8063e+10,1.8086e+10,1.8143e+10,1.7981e+10,1.8241e+10,1.81825e+10,1.8218e+10,1.82495e+10,1.80685e+10,1.80585e+10,1.8058e+10,1.799e+10,1.8022e+10,1.7949e+10,1.7924e+10,1.799e+10,1.8005e+10,1.80685e+10,1.80825e+10,1.80725e+10,1.8058e+10,1.80435e+10,1.8071e+10,1.8378e+10,1.8245e+10,1.81865e+10,1.80895e+10,1.81405e+10,1.81034e+10,1.80105e+10,1.80435e+10,1.80325e+10,1.8034e+10,1.79925e+10,1.79695e+10,1.7896e+10,1.7876e+10,1.7857e+10,1.7833e+10,1.7863e+10,1.7841e+10,1.78435e+10,1.7873e+10,1.7871e+10,1.7833e+10,1.7802e+10,1.77805e+10,1.7792e+10,1.78295e+10
averageReceivables,2.40975e+10,3.2075e+10,3.1376e+10,3.60105e+10,3.89395e+10,2.92745e+10,2.91765e+10,3.4528e+10,4.0535e+10,2.9221e+10,2.72415e+10,4.1487e+10,3.3874e+10,2.73535e+10,2.63435e+10,3.0026e+10,3.0687e+10,2.55585e+10,2.59495e+10,2.8348e+10,3.1209e+10,2.5991e+10,2.51195e+10,3.10255e+10,2.9647e+10,2.4458e+10,2.39475e+10,2.86365e+10,2.6358e+10,2.2764e+10,2.27055e+10,2.68045e+10,2.53835e+10,2.31865e+10,2.2922e+10,2.42795e+10,2.1896e+10,2.1773e+10,2.1585e+10,2.14745e+10,2.09995e+10,1.9237e+10,1.8352e+10,1.8478e+10,1.8566e+10,1.81275e+10,1.75555e+10,1.7744e+10,1.83895e+10,1.6834e+10,1.6834e+10,1.7007e+10,1.6856e+10,1.7488e+10,1.6871e+10,1.6848e+10,1.746e+10,1.6582e+10,1.6468e+10,1.7244e+10,1.6485e+10,1.6451e+10,1.64815e+10,1.647e+10,1.64245e+10,1.6352e+10,1.633e+10,1.63305e+10,1.64205e+10,1.63215e+10,1.62835e+10,1.6286e+10,1.632e+10,1.63505e+10,1.63595e+10,1.62865e+10,1.62705e+10,1.63365e+10,1.6356e+10,1.6258e+10,1.6514e+10,1.6521e+10,1.65075e+10,1.64835e+10,1.6378e+10,1.64855e+10,1.64395e+10,1.6494e+10,1.6515e+10,1.6495e+10,1.6441e+10,1.64885e+10,1.6555e+10,1.6641e+10,1.6612e+10,1.67835e+10,1.67855e+10,1.66835e+10,1.67205e+10,1.70095e+10,1.7003e+10,1.6814e+10,1.6854e+10,1.6837e+10,1.68282e+10,1.6676e+10,1.6709e+10,1.66615e+10,1.67285e+10,1.667e+10,1.66805e+10,1.6637e+10,1.6581e+10,1.6516e+10,1.6474e+10,1.6524e+10,1.6491e+10,1.6421e+10,1.6433e+10,1.6464e+10,1.64185e+10,1.63905e+10,1.6367e+10,1.6412e+10,1.6434e+10
bookValuePerShare,3.76548,4.14957,4.45122,5.02463,5.00445,5.2406,5.63008,6.17462,5.52532,5.88617,6.31249,6.79522,6.50786,6.32644,6.3703,6.24639,5.94516,5.78024,5.88599,5.73235,5.25053,5.44245,5.52725,5.24175,4.66958,4.99587,4.87977,5.13803,4.85343,4.76638,5.11515,4.80116,4.45269,4.2611,3.92107,3.45443,2.91223,2.64063,2.34573,2.09224,1.83755,1.66016,1.52276,1.38894,1.23574,1.01697,0.961517,0.907647,0.880052,0.775941,0.716958,0.666825,0.579426,0.552274,0.507406,0.453987,NaN,0.380196,0.352927,0.360246,0.306183,0.283029,0.267241,0.246719,0.22496,0.218847,0.211992,0.207694,0.20342,0.206067,0.204052,0.204695,0.203731,0.197917,0.195881,0.198102,0.196353,0.197534,0.192874,0.19661,NaN,0.20612,0.20678,0.220877,0.156799,0.15184,0.112113,0.0997821,0.0722457,0.0772349,0.0849241,0.0794381,0.0839631,0.0844156,0.0882855,0.139231,0.147548,0.145743,0.148469,0.202816,0.20763,0.204946,0.197581,0.18805,NaN,0.168645,0.158333,0.156718,0.152285,0.155912,0.168833,0.168264,0.161569,0.154053,0.15023,0.14057,0.130118,0.124143,0.132602,0.116975,0.10562,0.108106,0.109072,0.105074,0.102145
capexPerShare,0.102812,-0.0898436,-0.105172,-0.118248,-0.153582,-0.108663,-0.125674,-0.175719,-0.156817,-0.167293,-0.20105,-0.14366,-0.194196,-0.118766,-0.137258,-0.161362,-0.187187,-0.132697,-0.117262,-0.179031,-0.160919,-0.0904642,-0.106084,-0.138771,-0.161253,-0.100421,-0.0603378,-0.0809826,-0.0905877,-0.077898,-0.086794,-0.0925577,-0.131874,-0.112985,-0.057727,-0.0548158,-0.173749,-0.0366337,-0.0250305,-0.0483389,-0.0312596,-0.0241066,-0.0116486,-0.014795,-0.0184346,-0.0106851,-0.00458788,-0.0139857,-0.0166561,-0.0130497,-0.00853852,-0.00920635,-0.00933014,-0.0119074,-0.00852505,-0.0103914,NaN,-0.0096577,-0.00784553,-0.00352508,-0.00395713,-0.00261411,-0.00179946,-0.00247145,-0.00261478,-0.00172822,-0.0016525,-0.00211051,-0.00279383,-0.002258,-0.001972,-0.000994629,-0.00318408,-0.00150896,-0.00209838,-0.0017982,-0.0081647,-0.00153603,-0.000877171,-0.00116525,NaN,-0.000542942,-0.00132457,-0.00190152,-0.00202061,-0.000357873,-0.000979381,-0.000259444,-0.000747976,-0.00140333,-0.000305923,-0.000446999,-0.000769661,-0.00042349,-0.00113733,-0.0014339,-0.000860338,-0.000937951,-0.000794339,-0.00225029,-0.00350701,-0.00420328,-0.00218402,-0.0016148,NaN,-0.00180288,-0.00563063,-0.00183206,-0.00360794,-0.00555727,-0.00361891,-0.00324292,-0.00325059,-0.00414003,-0.00302332,-0.00380117,-0.00375552,-0.00402385,-0.00285088,-0.00560267,-0.0049635,-0.0035868,-0.00302391,-0.00434363,-0.00412428
capexToDepreciation,1.51457,-1.75847,-1.50351,-1.3365,-1.14476,-1.4665,-1.2865,-1.01192,-0.905623,-0.815733,-0.677803,-0.926113,-0.621,-0.946903,-0.8072,-0.873392,-0.631005,-0.869535,-0.953059,-0.737394,-0.852652,-1.4763,-1.00121,-0.788668,-0.511163,-0.800494,-1.26985,-1.04892,-0.7732,-0.840278,-0.735972,-0.646843,-0.280206,-0.281809,-0.490391,-0.504549,-0.118792,-0.5,-0.661585,-0.281869,-0.404674,-0.436102,-0.717608,-0.548556,-0.430085,-0.669118,-1.56034,-0.475921,-0.372038,-0.354545,-0.539535,-0.456897,-0.440171,-0.280277,-0.334951,-0.287938,-0.455172,-0.240506,-0.259067,-0.634146,-0.53125,-0.730159,-0.953488,-0.706897,-0.677966,-1.07895,-1.02857,-0.75,-0.5,-0.521739,-0.725,-1.55,-0.453125,-0.903226,-0.674419,-0.777778,-0.171779,-0.866667,-1.29412,-1.09091,-0.580645,-2.27273,-0.777778,-0.526316,-0.475,-2.71429,-1.26316,-4.6,-1.35294,-1.18519,-5.6,-4,-3.72727,-3.66667,-1.875,-1.25,-0.5,-1.69231,-4.18182,-1.35484,-0.469388,-0.637931,-0.966667,-1.72727,-1.2598,-1.70833,-0.506667,-1.79167,-0.875,-0.583333,-0.877551,-0.886364,-1.36364,-1,-1.19048,-0.961538,-1.13725,-0.981481,-1.17949,-0.635135,-0.897059,-1,-1.02326,-0.761905,-0.666667
capexToOperatingCashFlow,11.5336,-10.3968,-7.18349,-14.4832,-7.16961,-5.818,-4.72069,-7.95529,-6.41993,-4.43465,-3.74412,-9.54555,-3.914,-3.27353,-4.35099,-7.91111,-3.99356,-3.66059,-4.46364,-6.85547,-3.68371,-7.17472,-7.70638,-10.3283,-3.43977,-4.21843,-9.11036,-11.091,-4.29662,-3.88294,-5.43889,-9.54216,-2.60954,-3.43874,-9.26243,-12.2841,-2.28156,-11.5468,-9.48018,-7.73793,-6.99016,-7.66933,-7.74086,-15.1732,-6.58898,-8.34559,-7.25,-11.1558,-10.1777,-4.00303,-5.54884,-12.0129,-7.24786,-4.24567,-3.56311,-7.05447,-7.27586,-4.24895,0.647668,-3.45122,-7.83333,-7.49206,-12.4651,-13.3621,-7.50847,-5.55263,-1.74286,-4.97727,-1.25862,-0.173913,-2.45,-5.5,-1.29688,1.19355,-0.0465116,-1.16667,-1.68712,1.1,2.58824,0.590909,-5.09677,-21.2727,-2.25926,-9.81579,-6.05,-12.5714,-14.1579,-44.6,-16.5882,-7.62963,-31,-18.8571,-14.4545,34.3333,-6.8125,-4.6,-24.6667,-22.0769,32.9091,-6.03226,13.7347,0.465517,-0.233333,-20.5909,-6.68392,-5.91667,0.226667,-15.4167,8.3125,3.94444,0.959184,-1.79545,-1.31818,-4.14035,-7.54762,-5.96154,-2.27451,2.51852,0.461538,-3.06757,-1.44118,-6.04,-7.04651,-4.14286,-1.3
capexToRevenue,36.2657,-38.1374,-31.4695,-43.5781,-23.0609,-26.9045,-24.5514,-25.1297,-20.684,-16.3039,-15.1292,-29.7885,-13.1448,-18.2655,-18.3094,-22.9096,-11.6028,-14.5811,-19.4525,-18.9396,-14.079,-23.7458,-23.4289,-22.8481,-10.9354,-15.3978,-30.7174,-28.1771,-16.2498,-17.5213,-18.9661,-22.2045,-10.2731,-11.8201,-25.9682,-32.4234,-6.18464,-29.6996,-37.6021,-21.1726,-25.0221,-25.0799,-44.8472,-41.1627,-25.8623,-35.7868,-78.3103,-33.6544,-27.2986,-22.9121,-37.1163,-44.9569,-28.2308,-18.7197,-25.5534,-27.716,-33.3586,-18.4388,-22.5855,-70.1098,-38.3125,-55.873,-75.4186,-60.1724,-39.8305,-53,-54.5429,-45.5909,-29.569,-33.587,-36.875,-73.6,-22.5469,-46.0968,-34.7674,-38.1944,-8.89571,-49.1667,-84.1765,-45.7727,-60.3226,-165.909,-72.037,-61.6579,-33.4,-222.571,-80.5263,-342,-91.5294,-51.9259,-281,-225.429,-146.727,-289.5,-100.062,-106.45,-193.417,-167.615,-198.636,-101.548,-61.2857,-44.3966,-88.4,-128.727,-68.8525,-89.5833,-27.6933,-102.875,-44.6042,-25.8611,-40.2857,-45.4545,-40.1818,-30.5263,-40.8571,-35.8269,-29.549,-28.3148,-40.9744,-22.6486,-19.9118,-27.3,-31.3023,-23.6984,-23.0667
cashPerShare,2.19086,1.91645,2.28018,2.23202,2.70132,2.74537,2.02036,2.34489,1.33627,1.63713,2.2418,1.33244,0.985012,0.887206,0.720116,0.772412,0.949564,0.833044,0.970673,0.745844,0.929087,0.66339,0.62078,0.827865,0.579538,0.536062,0.769409,0.557726,0.560143,0.434621,0.455036,0.609033,0.404776,0.302959,0.38718,0.395487,0.37308,0.460434,0.609661,0.410824,0.432982,0.373729,0.387693,0.295472,0.205554,0.220184,0.176633,0.286688,0.468701,0.37065,0.360207,0.363571,0.372887,0.293277,0.293618,0.289463,NaN,0.326528,0.257967,0.178404,0.143899,0.128382,0.0943254,0.105463,0.131581,0.141896,0.149103,0.178626,0.163584,0.172148,0.168113,0.129899,0.11204,0.0606503,0.0565587,0.0972028,0.115708,0.108597,0.110317,0.0920021,NaN,0.0663376,0.0815345,0.0793635,0.0669832,0.0906442,0.07,0.0633562,0.0651619,0.062526,0.0786221,0.0761814,0.0860621,0.0718521,0.0904891,0.0841698,0.11127,0.0980519,0.0361063,0.0598142,0.0541082,0.0846454,0.100101,0.0842631,NaN,0.0857873,0.0816066,0.0741985,0.0508118,0.0303334,0.0414328,0.0430425,0.0368647,0.0530941,0.0552116,0.0387427,0.0444772,0.0576751,0.0638889,0.0559509,0.0273723,0.0477044,0.045429,0.028337,0.0301072
currentRatio,1.3636,1.46945,1.49596,1.59778,1.54013,1.50465,1.31538,1.30056,1.13293,1.30732,1.45603,1.24201,1.27606,1.38834,1.39061,1.22824,1.35267,1.3116,1.28312,1.00167,1.10877,1.08682,1.156,1.13302,1.08011,1.4706,1.63259,1.4943,1.67864,1.87833,1.78374,1.54329,1.49585,1.57117,1.58297,1.58266,1.60844,1.74608,1.93189,1.84606,2.01129,2.30803,2.64421,2.54501,2.74248,2.11092,2.46186,2.3828,2.64114,3.03623,2.77517,2.4859,2.36595,2.68092,2.92233,2.27123,2.24216,2.48676,2.53276,2.40356,2.95383,3.00224,2.68705,2.58127,2.66126,2.91694,2.92121,2.53107,2.49767,2.73877,2.72446,3.37555,3.2497,3.16822,3.16793,3.33882,3.38801,3.25155,2.97772,3.00916,2.80755,2.75334,2.65084,2.49822,2.7663,2.79272,2.65026,2.6058,2.43289,2.42981,2.32153,2.02097,1.88339,1.8288,1.81104,2.16194,2.25412,2.31256,1.88165,2.05213,2.24688,2.38338,2.30094,2.43824,2.30234,2.22222,2.03591,1.80756,1.72967,1.86934,2.48639,2.40767,2.49509,2.52062,2.60352,2.41699,2.35333,2.19736,2.8243,2.37313,2.33982,2.63698,2.93282,2.6047,2.56313
daysOfInventoryOnHand,9.13519,9.67491,8.34822,6.51443,9.30199,8.99142,12.1446,8.587,9.17251,16.266,18.284,7.31671,13.3837,10.1411,8.1071,5.06653,6.60767,6.27724,6.70094,4.85357,6.83003,6.14156,6.277,4.58045,7.27541,6.32066,5.94281,5.3424,6.72683,6.84919,4.11132,3.91456,3.30118,5.04169,4.80943,4.34023,4.13499,4.80569,5.79279,4.84401,7.37199,8.86449,7.29235,5.59103,5.76598,5.94679,5.14568,4.83385,6.47308,10.1806,6.09715,5.87959,6.82745,6.61493,5.4817,5.56531,7.09489,6.29557,5.99608,5.24731,5.61862,7.01535,6.48506,5.62951,5.2972,4.45361,4.11168,5.44898,4.00318,3.06177,3.49101,3.71482,3.81356,2.94798,2.1547,2.17209,0.977295,1.64265,0.860421,1.83852,2.11689,0.351014,0.644699,0.77765,1.89076,0.557029,1.43744,1.83225,6.1633,11.142,21.9034,29.6816,30.3941,34.6004,35.2928,25.358,32.9171,53.7669,50.6293,65.5556,67.0655,66.6107,45.2529,48.3449,53.9894,68.3566,73.403,64.2035,85.3019,88.7818,65.0701,45.1892,51.5301,49.7833,50.9062,55.1668,70.9859,79.6739,68.2418,45.1656,49.0031,41.8471,46.0328,53.6732,63.1462
daysPayablesOutstanding,95.1446,85.9141,81.181,71.7287,104.746,78.0284,75.6996,76.2518,129.584,105.469,81.877,104.24,135.212,102.878,79.6028,71.944,115.585,90.2263,73.7309,65.9658,103.192,79.6237,60.6715,76.2426,104.068,81.4271,61.4556,74.4914,85.2943,62.6234,49.2434,71.0218,88.3724,75.5265,74.2406,63.9832,77.968,82.5455,85.4218,78.2759,84.2764,79.6957,64.7625,63.2,70.9786,75.9624,65.5745,57.5546,70.1992,68.7983,69.5812,68.7361,98.0706,96.4568,63.3294,71.3571,89.0803,74.2759,61.9595,62.2796,60.5789,55.6139,70.1098,62.6824,76.1014,65.6289,64.6773,66.4286,82.494,70.9042,78.4201,68.9775,77.2034,78.3815,81.7956,78.3841,71.1649,73.2277,82.6864,55.7685,74.2195,73.0109,71.6261,60.8641,76.7647,63.0239,63.1677,48.0049,56.813,49.4914,44.5739,48.1224,47.643,52.6134,58.2435,42.6097,39.3315,38.6149,28.2157,48.1818,44.0176,51.0666,39.2744,42.6363,43.7356,39.7462,43.4601,35.4822,42.0566,47.293,45.5565,35.349,37.9368,36.13,31.9688,34.4042,37.7113,39.3478,46.2637,46.0491,47.0706,39.9841,34.8197,32.5559,44.4018
daysSalesOutstanding,22.4242,48.3664,47.3467,39.1546,64.3716,44.28,40.7657,39.4768,70.1041,44.5514,32.9869,51.883,61.0618,44.8573,35.0703,32.1365,56.2817,40.4594,35.2901,29.2056,53.0256,36.1179,28.1807,36.1646,58.1561,40.4918,31.1922,39.376,49.5754,34.2771,27.5265,35.5529,46.7742,36.7421,31.6238,32.0195,37.3021,36.1342,40.4812,36.5977,43.905,36.6822,30.8623,28.0106,37.2843,38.648,30.0793,25.8561,36.75,18.9618,17.9662,16.7315,22.3025,48.2606,28.5011,20.4815,52.9357,22.4279,17.777,37.7753,21.9005,21.1449,24.6438,22.3066,29.6426,28.1082,27.5799,26.2911,40.1983,33.0874,30.0203,30.3872,35.2391,39.4262,38.7692,32.5964,28.9241,36.4881,40.0629,39.4141,45.8663,47.6877,43.4961,34.2638,45.8757,51.7587,47.2941,48.0526,55.2378,58.7375,51.694,51.4449,57.7138,62.5389,64.5909,63.0719,58.0095,53.3639,56.2654,55.5781,57.8721,54.2796,55.4186,50.8157,57.0818,53.4558,58.1945,45.4921,58.0943,61.1439,58.6322,53.955,55.3337,49.5,45.7867,47.0048,54.1672,45.1472,44.5494,45.8055,50.6499,46.5495,44.0639,45.1507,51.5679
debtToAssets,0.798267,0.772228,0.755228,0.737151,0.732692,0.700669,0.690466,0.684544,0.707029,0.670819,0.654756,0.655356,0.642845,0.616352,0.599195,0.600201,0.601322,0.585929,0.57266,0.562653,0.58892,0.539899,0.506091,0.529092,0.51886,0.456498,0.416576,0.424098,0.403145,0.382786,0.304263,0.350567,0.328596,0.314004,0.320908,0.350639,0.341632,0.350466,0.352219,0.369786,0.364338,0.333936,0.310374,0.336721,0.333909,0.462235,0.437727,0.46458,0.383567,0.381185,0.407535,0.440594,0.426678,0.380792,0.344717,0.423051,0.419704,0.382692,0.37589,0.409068,0.354984,0.349638,0.368411,0.381542,0.369441,0.333795,0.333333,0.378855,0.380337,0.348238,0.349316,0.343436,0.349794,0.353885,0.359195,0.352172,0.348945,0.36452,0.390212,0.379886,0.396296,0.397576,0.398459,0.418139,0.398566,0.408249,0.559271,0.581228,0.61716,0.632269,0.64976,0.698497,0.716513,0.724487,0.7232,0.631639,0.616331,0.622077,0.607184,0.57363,0.534425,0.537304,0.551405,0.53696,0.550553,0.56178,0.601022,0.59282,0.6082,0.576342,0.488591,0.492102,0.482008,0.485319,0.470439,0.486782,0.494276,0.5178,0.469901,0.510611,0.513777,0.478547,0.441282,0.458585,0.458455
debtToEquity,3.95704,3.39036,3.08543,2.80447,2.741,2.34079,2.23066,2.17001,2.4133,2.03784,1.8965,1.90155,1.79991,1.60655,1.49498,1.50125,1.50829,1.41504,1.34006,1.28651,1.43262,1.17344,1.02467,1.12356,1.0784,0.839921,0.714018,0.736405,0.675449,0.620183,0.437324,0.539805,0.489417,0.457735,0.472556,0.539976,0.518906,0.539564,0.543732,0.586763,0.573162,0.501357,0.450061,0.50766,0.501296,0.859549,0.778495,0.867694,0.622236,0.615992,0.687864,0.78761,0.74422,0.614966,0.526058,0.733256,0.723257,0.619936,0.602281,0.692243,0.55035,0.537604,0.583307,0.616926,0.585894,0.501039,0.5,0.609931,0.613782,0.534302,0.536845,0.523081,0.537973,0.547713,0.560538,0.543621,0.535969,0.573613,0.639914,0.612608,0.65644,0.659962,0.662396,0.718623,0.662693,0.689899,1.26897,1.38794,1.61206,1.71938,1.85519,2.31672,2.5275,2.6296,2.61272,1.71473,1.60641,1.64604,1.54572,1.34538,1.14788,1.16124,1.22918,1.15964,1.22496,1.28196,1.5064,1.45592,1.55232,1.3604,0.955381,0.968901,0.930956,0.942951,0.888356,0.947998,0.977363,1.07383,0.886439,1.04337,1.05667,0.917717,0.789813,0.846457,0.846568
dividendYield,0.00180209,0.00237405,0.00309287,0.0027414,0.00351717,0.00398482,0.00385603,0.0047846,0.00322555,0.0040421,0.00380874,0.00382523,0.00412031,0.0044649,0.00397387,0.00510029,0.00508682,0.00623462,0.00497892,0.00496861,0.00454673,0.00417232,0.00381415,0.00417755,0.00470184,0.00515033,0.00563524,0.00548446,0.00630912,0.0076697,0.00613927,0.00516441,0.00393356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000329275,0.00382592,0.00322794,0.00244702,0.00346965,0.00295105,NaN,0.0045743,0.00354038,0.00409212,0.00471438,0.00302562,0.00217474,0.00195875,0.00254592,0.00251684,0.00198251,0.002084,0.00252472,0.00281543,0.00168559,0.00276083,0.00366473,0.00251356,0.00254388,0.0030669,0.00224905

In [664]:
key_mtrcs_with_datetime = key_mtrcs.copy().T
key_mtrcs_with_datetime.reset_index(inplace = True)
key_mtrcs_with_datetime = key_mtrcs_with_datetime.rename(columns = {'index' : "Date"})
key_mtrcs_with_datetime['Date'] = pd.to_datetime(key_mtrcs_with_datetime['Date'])
key_mtrcs_with_datetime.head()

,Date,revenuePerShare,netIncomePerShare,operatingCashFlowPerShare,freeCashFlowPerShare,cashPerShare,bookValuePerShare,tangibleBookValuePerShare,shareholdersEquityPerShare,interestDebtPerShare,marketCap,enterpriseValue,peRatio,priceToSalesRatio,pocfratio,pfcfRatio,pbRatio,ptbRatio,evToSales,enterpriseValueOverEBITDA,evToOperatingCashFlow,evToFreeCashFlow,earningsYield,freeCashFlowYield,debtToEquity,debtToAssets,netDebtToEBITDA,currentRatio,interestCoverage,incomeQuality,dividendYield,payoutRatio,salesGeneralAndAdministrativeToRevenue,researchAndDdevelopementToRevenue,intangiblesToTotalAssets,capexToOperatingCashFlow,capexToRevenue,capexToDepreciation,stockBasedCompensationToRevenue,grahamNumber,roic,returnOnTangibleAssets,grahamNetNet,workingCapital,tangibleAssetValue,netCurrentAssetValue,investedCapital,averageReceivables,averagePayables,averageInventory,daysSalesOutstanding,daysPayablesOutstanding,daysOfInventoryOnHand,receivablesTurnover,payablesTurnover,inventoryTurnover,roe,capexPerShare
0,2020-09-01,3.728536,0.730343,1.185792,1.082980,2.190856,3.765477,18.665617,3.765477,6.191751,1.948296e+12,2.017720e+12,153.735967,30.113696,94.687787,103.676879,29.818269,29.818269,31.186743,115.450015,98.061815,107.371217,0.006505,0.009645,3.957039,0.798267,3.972306,1.363604,NaN,1.623609,0.001802,0.277046,0.0,0.076942,0.0,11.533632,36.265695,1.514574,0.026647,7.866195,0.068198,0.039128,-8.845346,3.832100e+10,NaN,-1.148360e+11,NaN,2.409750e+10,3.881050e+10,4.019500e+09,22.424186,95.144592,9.135195,4.013524,0.945929,9.852007,0.193958,0.102812
1,2020-06-01,3.426401,0.646013,0.934087,0.844243,1.916454,4.149571,18.218108,4.149571,6.116314,1.539984e+12,1.612445e+12,136.850946,25.801855,94.645916,104.718054,21.305217,21.305217,27.015912,97.217213,99.099299,109.645362,0.007307,0.009549,3.390360,0.772228,4.368805,1.469450,18.847920,1.445926,0.002374,0.324891,0.0,0.079719,0.0,-10.396805,-38.137380,-1.758466,0.028449,7.766288,0.059169,0.035460,-7.232944,4.474700e+10,NaN,-1.049970e+11,NaN,3.207500e+10,3.532500e+10,3.978000e+09,48.366424,85.914066,9.674909,1.860795,1.047558,9.302413,0.155682,-0.089844
2,2020-03-01,3.309710,0.638467,0.755501,0.650329,2.280183,4.451220,18.185158,4.451220,5.704203,1.091218e+12,1.150788e+12,97.005793,18.713120,81.978677,95.236356,13.914162,13.914162,19.734676,69.000370,86.453923,100.435344,0.010309,0.010500,3.085432,0.755228,3.571771,1.495962,17.351387,1.183305,0.003093,0.300027,0.0,0.078284,0.0,-7.183486,-31.469509,-1.503508,0.029102,7.996502,0.058558,0.035109,-6.995340,4.765900e+10,NaN,-9.822200e+10,NaN,3.137600e+10,3.387300e+10,3.656000e+09,47.346732,81.181037,8.348218,1.900870,1.108633,10.780744,0.143436,-0.105172
3,2019-12-01,5.153039,1.247922,1.712610,1.594362,2.232017,5.024633,19.116065,5.024633,5.582988,1.290944e+12,1.349868e+12,58.056493,14.059663,42.303847,45.441381,14.418963,14.418963,14.701404,45.728791,44.234768,47.515512,0.017225,0.022006,2.804470,0.737151,1.996138,1.597782,33.016561,1.372369,0.002741,0.159156,0.0,0.048476,0.0,-14.483151,-43.578073,-1.336497,0.018624,11.877833,0.108690,0.065281,-6.280974,6.107000e+10,NaN,-8.785600e+10,NaN,3.601050e+10,4.021800e+10,4.037500e+09,39.154641,71.728738,6.514434,2.298578,1.254727,13.815475,0.248361,-0.118248
4,2019-09-01,3.541742,0.756906,1.101125,0.947543,2.701325,5.004452,18.721677,5.004452,5.452921,9.891485e+11,1.038091e+12,72.274477,15.445792,49.680989,57.733526,10.931267,10.931267,16.210048,51.605264,52.139201,60.590176,0.013836,0.017321,2.741004,0.732692,2.433038,1.540126,19.909877,1.454771,0.003517,0.254201,0.0,0.064179,0.0,-7.169607,-23.060857,-1.144761,0.023407,9.231889,0.069275,0.040429,-6.142466,5.710100e+10,NaN,-8.520900e+10,NaN,3.893950e+10,4.078050e+10,4.042000e+09,64.371643,104.745891,9.301986,1.398131,0.859222,9.675353,0.151247,-0.153582

In [665]:
# key_mtrcs.T

In [666]:
# import re
# year = re.findall(r'^\d{4}', str(key_mtrcs_with_datetime['Date']))
# year

In [667]:
key_mtrcs_with_datetime = key_mtrcs_with_datetime.sort_values(by='Date', ascending = True)
key_mtrcs_with_datetime.reset_index(inplace = True)
key_mtrcs_with_datetime.drop('index', axis = 1, inplace = True)
display(key_mtrcs_with_datetime.head())

,Date,revenuePerShare,netIncomePerShare,operatingCashFlowPerShare,freeCashFlowPerShare,cashPerShare,bookValuePerShare,tangibleBookValuePerShare,shareholdersEquityPerShare,interestDebtPerShare,marketCap,enterpriseValue,peRatio,priceToSalesRatio,pocfratio,pfcfRatio,pbRatio,ptbRatio,evToSales,enterpriseValueOverEBITDA,evToOperatingCashFlow,evToFreeCashFlow,earningsYield,freeCashFlowYield,debtToEquity,debtToAssets,netDebtToEBITDA,currentRatio,interestCoverage,incomeQuality,dividendYield,payoutRatio,salesGeneralAndAdministrativeToRevenue,researchAndDdevelopementToRevenue,intangiblesToTotalAssets,capexToOperatingCashFlow,capexToRevenue,capexToDepreciation,stockBasedCompensationToRevenue,grahamNumber,roic,returnOnTangibleAssets,grahamNetNet,workingCapital,tangibleAssetValue,netCurrentAssetValue,investedCapital,averageReceivables,averagePayables,averageInventory,daysSalesOutstanding,daysPayablesOutstanding,daysOfInventoryOnHand,receivablesTurnover,payablesTurnover,inventoryTurnover,roe,capexPerShare
0,1989-09-01,0.095133,0.011067,0.005362,0.001237,0.030107,0.102145,0.188617,0.102145,0.003918,5.780226e+09,5.399226e+09,35.902024,4.176464,74.105460,321.123662,3.889789,3.889789,3.901175,17.760612,69.220845,299.956995,0.027854,0.003114,0.846568,0.458455,-1.253289,2.563128,NaN,0.484472,0.002249,0.080745,0.0,0.081647,0.0,-1.300000,-23.066667,-0.666667,0.0,0.159481,0.142780,0.058673,0.026344,1.399000e+09,NaN,1.036000e+09,NaN,1.643400e+10,1.782950e+10,2.226500e+09,51.567919,44.401773,63.146233,1.745271,2.026946,1.425263,0.108345,-0.004124
1,1989-12-01,0.102937,0.008618,0.017995,0.013651,0.028337,0.105074,0.193946,0.105074,0.004688,4.564873e+09,4.221873e+09,36.518983,3.057517,17.489935,23.054914,2.995323,2.995323,2.827778,16.687245,16.175758,21.322591,0.027383,0.043375,0.846457,0.458585,-1.355731,2.604703,NaN,2.088000,0.003067,0.112000,0.0,0.070998,0.0,-4.142857,-23.698413,-0.761905,0.0,0.142742,0.106771,0.044437,0.027113,1.433000e+09,NaN,1.036000e+09,NaN,1.641200e+10,1.779200e+10,2.202500e+09,45.150703,32.555866,53.673184,1.993324,2.764479,1.676815,0.082021,-0.004344
2,1990-03-01,0.094655,0.009283,0.021308,0.018284,0.045429,0.109072,0.195218,0.109072,0.001406,5.110312e+09,4.484312e+09,38.714489,3.796666,16.865718,19.655048,3.294850,3.294850,3.331584,17.247356,14.799711,17.247356,0.025830,0.050878,0.789813,0.441282,-2.407692,2.932817,NaN,2.295455,0.002544,0.098485,0.0,0.085438,0.0,-7.046512,-31.302326,-1.023256,0.0,0.150933,0.107892,0.047550,0.029624,1.496000e+09,NaN,1.045000e+09,NaN,1.636700e+10,1.778050e+10,2.145000e+09,44.063893,34.819672,46.032787,2.042489,2.584746,1.955128,0.085106,-0.003024
3,1990-06-01,0.097920,0.008608,0.021664,0.018077,0.047704,0.108106,0.207317,0.108106,0.001793,5.569783e+09,4.929783e+09,46.414856,4.080427,18.442989,22.102313,3.695941,3.695941,3.611562,19.958635,16.323784,19.562630,0.021545,0.045244,0.917717,0.478547,-2.591093,2.636979,NaN,2.516667,0.002514,0.116667,0.0,0.090842,0.0,-6.040000,-27.300000,-1.000000,0.0,0.144702,0.097853,0.041522,0.024139,1.452000e+09,NaN,9.560000e+08,NaN,1.639050e+10,1.780200e+10,2.135000e+09,46.549451,39.984076,41.847134,1.933428,2.250896,2.150685,0.079628,-0.003587
4,1990-09-01,0.098832,0.007153,0.007153,0.002190,0.027372,0.105620,0.217226,0.105620,0.008978,3.547327e+09,3.295327e+09,36.197217,2.619887,36.197217,118.244243,2.451505,2.451505,2.433772,14.843817,33.625789,109.844243,0.027626,0.008457,1.056669,0.513777,-1.135135,2.339825,NaN,1.000000,0.003665,0.132653,0.0,0.097489,0.0,-1.441176,-19.911765,-0.897059,0.0,0.130382,0.082606,0.032930,0.015839,1.376000e+09,NaN,8.740000e+08,NaN,1.641850e+10,1.783300e+10,2.166500e+09,50.649926,47.070552,49.003067,1.776903,1.912023,1.836620,0.067726,-0.004964

In [668]:
start_date_index = min(key_mtrcs_with_datetime[key_mtrcs_with_datetime['Date'].dt.year==start_date].index.values)

In [669]:
key_mtrcs_with_datetime['Date'].iloc[start_date_index]

Timestamp('2005-03-01 00:00:00')

In [670]:
# results = requests.get('http://www.marketwatch.com/investing/stock/{}/financials'.format(get_stock_info))
# print(results)
# # print(results.headers)
# src = results.content
# Soup = BeautifulSoup(src, 'lxml')
# links = Soup.find_all('a')
# # print(links)
# for link in links:
#     if 'EPS' in  link:
#         print(link)
#         print(link.attr['href'])

In [671]:
key_mtrcs.index

Index(['revenuePerShare', 'netIncomePerShare', 'operatingCashFlowPerShare',
       'freeCashFlowPerShare', 'cashPerShare', 'bookValuePerShare',
       'tangibleBookValuePerShare', 'shareholdersEquityPerShare',
       'interestDebtPerShare', 'marketCap', 'enterpriseValue', 'peRatio',
       'priceToSalesRatio', 'pocfratio', 'pfcfRatio', 'pbRatio', 'ptbRatio',
       'evToSales', 'enterpriseValueOverEBITDA', 'evToOperatingCashFlow',
       'evToFreeCashFlow', 'earningsYield', 'freeCashFlowYield',
       'debtToEquity', 'debtToAssets', 'netDebtToEBITDA', 'currentRatio',
       'interestCoverage', 'incomeQuality', 'dividendYield', 'payoutRatio',
       'salesGeneralAndAdministrativeToRevenue',
       'researchAndDdevelopementToRevenue', 'intangiblesToTotalAssets',
       'capexToOperatingCashFlow', 'capexToRevenue', 'capexToDepreciation',
       'stockBasedCompensationToRevenue', 'grahamNumber', 'roic',
       'returnOnTangibleAssets', 'grahamNetNet', 'workingCapital',
       'tangibleAssetValue', 'netCurrentAssetValue', 'investedCapital',
       'averageReceivables', 'averagePayables', 'averageInventory',
       'daysSalesOutstanding', 'daysPayablesOutstanding',
       'daysOfInventoryOnHand', 'receivablesTurnover', 'payablesTurnover',
       'inventoryTurnover', 'roe', 'capexPerShare'],
      dtype='object')

In [672]:
start_date, start_date_index

(2005, 62)

In [673]:
#getting data from key_metrics DataFrame to fill missing data
key_mtrcs_stock = key_mtrcs_with_datetime.iloc[start_date_index:]
key_mtrcs_stock.head()

,Date,revenuePerShare,netIncomePerShare,operatingCashFlowPerShare,freeCashFlowPerShare,cashPerShare,bookValuePerShare,tangibleBookValuePerShare,shareholdersEquityPerShare,interestDebtPerShare,marketCap,enterpriseValue,peRatio,priceToSalesRatio,pocfratio,pfcfRatio,pbRatio,ptbRatio,evToSales,enterpriseValueOverEBITDA,evToOperatingCashFlow,evToFreeCashFlow,earningsYield,freeCashFlowYield,debtToEquity,debtToAssets,netDebtToEBITDA,currentRatio,interestCoverage,incomeQuality,dividendYield,payoutRatio,salesGeneralAndAdministrativeToRevenue,researchAndDdevelopementToRevenue,intangiblesToTotalAssets,capexToOperatingCashFlow,capexToRevenue,capexToDepreciation,stockBasedCompensationToRevenue,grahamNumber,roic,returnOnTangibleAssets,grahamNetNet,workingCapital,tangibleAssetValue,netCurrentAssetValue,investedCapital,averageReceivables,averagePayables,averageInventory,daysSalesOutstanding,daysPayablesOutstanding,daysOfInventoryOnHand,receivablesTurnover,payablesTurnover,inventoryTurnover,roe,capexPerShare
62,2005-03-01,0.135713,0.011927,0.022431,0.020631,0.094325,0.267241,0.418396,0.267241,0.001632,3.629633e+10,3.404233e+10,127.355535,11.192207,67.717029,73.623382,5.683734,5.683734,10.497172,66.880800,63.511805,69.051374,0.007852,0.013583,0.583307,0.368411,-4.428291,2.687053,11.000000,1.880702,NaN,0.0,0.0,0.037003,0.011176,-12.465116,-75.418605,-0.953488,0.003084,0.267795,0.063471,0.028506,0.170740,5.655000e+09,6.273000e+09,5.282000e+09,NaN,1.648150e+10,1.854900e+10,2.071000e+09,24.643848,70.109842,6.485062,3.652027,1.283700,13.878049,0.044629,-0.001799
63,2005-06-01,0.146058,0.013278,0.019585,0.016971,0.128382,0.283029,0.430664,0.283029,0.002116,3.250056e+10,2.940656e+10,101.564253,9.233114,68.857121,79.463475,4.764780,4.764780,8.354137,51.590458,62.302036,71.898682,0.009846,0.012584,0.537604,0.349638,-5.428070,3.002241,9.274510,1.475000,NaN,0.0,0.0,0.041193,0.010393,-7.492063,-55.873016,-0.730159,0.003125,0.290786,0.064223,0.030831,0.189865,6.253000e+09,6.712000e+09,5.709000e+09,NaN,1.645100e+10,1.842750e+10,2.085500e+09,21.144886,55.613893,7.015347,4.256348,1.618301,12.829016,0.046914,-0.002614
64,2005-09-01,0.151608,0.017725,0.030998,0.027040,0.143899,0.306183,0.470734,0.306183,0.002679,4.609400e+10,4.260300e+10,107.195349,12.532355,61.295213,70.265244,6.205439,6.205439,11.583197,71.722222,56.652926,64.943598,0.009329,0.014232,0.550350,0.354984,-5.877104,2.953829,7.353846,1.748837,NaN,0.0,0.0,0.039967,0.008336,-7.833333,-38.312500,-0.531250,0.002991,0.349438,0.059534,0.037653,0.203081,6.813000e+09,7.332000e+09,6.212000e+09,NaN,1.648500e+10,1.855200e+10,2.071500e+09,21.900489,60.578888,5.618615,4.109497,1.485666,16.018182,0.057889,-0.003957
65,2005-12-01,0.247143,0.024289,0.012166,0.008641,0.178404,0.360246,0.605626,0.360246,0.195900,5.972485e+10,6.013185e+10,105.707692,10.388736,211.041859,297.138538,7.127070,7.127070,10.459531,74.977364,212.480022,299.163413,0.009460,0.003365,0.692243,0.409068,0.507481,2.403557,NaN,0.500885,NaN,0.0,0.0,0.031658,0.006558,-3.451220,-70.109756,-0.634146,0.007654,0.443704,0.091108,0.040105,0.207969,7.102000e+09,8.287000e+09,6.361000e+09,NaN,1.724400e+10,1.911050e+10,2.111000e+09,37.775265,62.279570,5.247312,2.382511,1.445097,17.151639,0.067422,-0.003525
66,2006-04-01,0.177195,0.016667,-0.005081,-0.012927,0.257967,0.352927,0.561016,0.352927,0.003537,5.510400e+10,4.875800e+10,134.400000,12.641432,-440.832000,-173.283019,6.346925,6.346925,11.185593,65.711590,-390.064000,-153.327044,0.007440,-0.005771,0.602281,0.375890,-8.552561,2.532765,6.954023,-0.304878,NaN,0.0,0.0,0.040376,0.007907,0.647668,-22.585492,-0.259067,0.009635,0.363796,0.063987,0.029708,0.152226,6.830000e+09,8.572000e+09,6.057000e+09,NaN,1.646800e+10,1.871650e+10,2.091000e+09,17.777013,61.959504,5.996081,5.062718,1.452562,15.009804,0.047224,-0.007846

In [674]:
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

In [675]:
# global dec_df_copy
# dec_df_copy = dec_df_copy.copy()
def key_mtrcs_cleaning(df, name, col_name, dec_df_copy):
    #define param
    param_name = name
    param = df[['Date', col_name]]
    #ensure the date is in datetime format
    param['Date'] = pd.to_datetime(param['Date'])
    #reseting index and dropping the extra column
    param.reset_index(inplace=True)
    param.drop('index', axis = 1, inplace = True)
    #change dates to datetime format and define quarterly and yearly data
    param_quarters = param['Date'].dt.quarter
    param_years = param['Date'].dt.year
    param.insert(1, "Year", param_years)
    param.insert(2, "Quarter", param_quarters)
#     param[param_name] = param[param_name].values.astype('int64')
    #pivot the data based on Year and Quarters
#     display(param)
    param = param.pivot_table(index=['Year', 'Quarter'], values=col_name, aggfunc='mean')
    param_name = param.copy()
    display(param)
    #merge with main dataframe
    global dec_df_final
    dec_df_final = pd.merge(dec_df_copy, param, left_index = True,right_index = True,  how = 'outer')
    dec_df_final[col_name] = dec_df_final[col_name].bfill()
    dec_df_copy = dec_df_copy.rename(columns={'{}'.format(col_name): "{}".format(name)})
    return dec_df_final

In [676]:
dec_df_copy = key_mtrcs_cleaning(key_mtrcs_stock, 'cash_per_share', 'freeCashFlowPerShare', dec_df_copy)
dec_df_copy.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3994: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

              freeCashFlowPerShare
Year Quarter
2005 1                    0.020631
     2                    0.016971
     3                    0.027040
     4                    0.008641
2006 2                   -0.012927
     3                    0.031377
     4                    0.062914
2007 1                    0.021851
     2                    0.038648
     3                    0.058293
     4                    0.101389
2008 1                    0.038840
     2                    0.039189
     3                    0.152865
     4                    0.142036
2009 1                    0.028674
     2                    0.078488
     3                    0.103031
     4                    0.209692
2010 1                    0.078522
     2                    0.160775
     3                    0.187250
     4                    0.325704
2011 1                    0.212263
     2                    0.386367
     3                    0.222670
     4                    0.618547
2012 1                    0.476965
     2                    0.275542
     3                    0.212257
     4                    0.790642
2013 1                    0.385269
     2                    0.224575
     3                    0.298633
     4                    0.817195
2014 1                    0.489362
     2                    0.323199
     3                    0.393419
     4                    1.294500
2015 1                    0.711440
     2                    0.558592
     3                    0.431858
     4                    1.048311
2016 1                    0.406154
     2                    0.353051
     3                    0.560356
     4                    1.115187
2017 2                    0.459949
     3                    0.417953
     4                    1.227656
2018 1                    0.551705
     2                    0.574591
     3                    0.849938
     4                    1.222175
2019 1                    0.467595
     2                    0.523539
     3                    0.947543
     4                    1.594362
2020 1                    0.650329
     2                    0.844243
     3                    1.082980

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

              freeCashFlowPerShare
Year Quarter
2005 1                    0.020631
     2                    0.016971
     3                    0.027040
     4                    0.008641
2006 1                   -0.012927

In [677]:
dec_df_copy = key_mtrcs_cleaning(key_mtrcs_stock, 'PE Ratio', 'peRatio', dec_df_copy)
dec_df_copy.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3994: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                 peRatio
Year Quarter
2005 1        127.355535
     2        101.564253
     3        107.195349
     4        105.707692
2006 2        134.400000
     3        106.341230
     4         74.122611
2007 1        104.131950
     2        129.321538
     3        158.006047
     4        109.662809
2008 1        116.809128
     2        135.822787
     3         51.641691
     4         34.302257
2009 1         59.558990
     2         70.841527
     3         65.862690
     4         57.614192
2010 1         69.319356
     2         76.036028
     3         63.027744
     4         50.461832
2011 1         54.959319
     2         41.881455
     3         57.355988
     4         28.863412
2012 1         48.161167
     2         61.986862
     3         76.919145
     4         36.911401
2013 1         42.500142
     2         53.116960
     3         58.425017
     4         38.623097
2014 1         46.190620
     2         71.846023
     3         71.061651
     4         37.199798
2015 1         53.000497
     2         68.533085
     3         58.602745
     4         32.544583
2016 1         55.425809
     2         65.569292
     3         67.433440
     4         34.301655
2017 2         68.541023
     3         80.266178
     4         43.503031
2018 1         60.595171
     2         78.456284
     3         77.478764
     4         37.351622
2019 1         77.232738
     2         90.671558
     3         72.274477
     4         58.056493
2020 1         97.005793
     2        136.850946
     3        153.735967

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

              freeCashFlowPerShare     peRatio
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000

In [678]:
#fixing column names for better visual appeal
dec_df_copy = dec_df_copy.rename(columns={'peRatio': "P/E ratio"})
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

              freeCashFlowPerShare   P/E ratio
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000

In [679]:
# finding specific elements in income statement
mask = IncomeStatement_Quarterly['Unnamed: 0'].str.contains('net income', case=False, na=False)
IncomeStatement_Quarterly[mask]


# IncomeStatement_Quarterly[IncomeStatement_Quarterly['Unnamed: 0'].str.contains('net income'), na = False]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
36,Net income (loss),11253000,NaN,11249000,NaN,22236000,NaN,10044000,NaN,11561000,NaN,19965000,NaN,11519000,NaN,13822000,NaN,20065000,NaN,8717000,NaN,11029000,NaN,17891000,NaN,7796000,NaN,10516000,NaN,18361000,NaN,10677000,NaN,13569000,NaN,18024000,NaN,7748000,NaN,10223000,NaN,13072000,NaN,6900000,NaN,9547000,NaN,13078000,NaN,8824000,NaN,11622000,NaN,13064000,NaN,7308000,NaN,5987000,NaN,6004000,NaN,3253000,NaN,3074000,NaN,3378000,NaN,1229000,NaN,1205000,NaN,1605000,NaN,1072000,NaN,1045000,NaN,1581000,NaN,818000,NaN,770000,NaN,1004000,NaN,472000,NaN,410000,NaN,565000

In [680]:
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

              freeCashFlowPerShare   P/E ratio
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000

In [681]:
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

              freeCashFlowPerShare   P/E ratio
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000

In [682]:
#cashflow, High & Low PCF and earnings per share
# dec_df['freeCashFlowPerShare'] = key_mtrcs['freeCashFlowPerShare']
dec_df_copy['Cash flow to net earnings ratio'] = (dec_df_copy['freeCashFlowPerShare']/dec_df_copy['Net Income Per Share']) * 100
High_PCF = dec_df_copy['High PCF'] = (dec_df_copy['freeCashFlowPerShare']/dec_df_copy['High']) * 100
Low_PCF = dec_df_copy['Low PCF'] = (dec_df_copy['freeCashFlowPerShare']/dec_df_copy['Low']) * 100
dec_df_copy['Earnings Per Share'] = ((dec_df_copy['High']+dec_df_copy['Low'])/2)/dec_df_copy['P/E ratio']

In [683]:
dec_df_copy.head()

                 Close      High       Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1        1.411996  1.433908  1.390404      5749000.0          NaN
     2        1.352740  1.375603  1.332132      5749000.0     0.000000
     3        1.632829  1.650273  1.608292      5749000.0     0.000000
     4        2.267874  2.295085  2.232783      5749000.0     0.000000
2006 1        2.505685  2.559983  2.467074      4359000.0   -24.178118

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309

              freeCashFlowPerShare   P/E ratio  \
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000

              Cash flow to net earnings ratio  High PCF   Low PCF  \
Year Quarter
2005 1                              86.457977  1.438800  1.483818
     2                              71.119653  1.233710  1.273970
     3                             113.317349  1.638540  1.681311
     4                              36.210526  0.376489  0.386995
2006 1                             -74.966996 -0.504958 -0.523974

              Earnings Per Share
Year Quarter
2005 1                  0.011088
     2                  0.013330
     3                  0.015199
     4                  0.021417
2006 1                  0.018702

In [684]:
# data_IncomeStatement.iloc[[10, 63]]

In [685]:
#just for fun
# import numpy as np
# import matplotlib.pyplot as plt

# data['log+1'] = (data['Adj Close']+1).transform(np.log)
# plt.plot(data['Date'], data['Adj Close'])
# plt.title('AAPl')
# plt.ylabel("USD$")
# # plt.axis(data.Date)
# plt.show()

In [686]:
# finding specific elements in income statement
mask = IncomeStatement_Quarterly['Unnamed: 0'].str.contains('dividend', case=False, na=False)
IncomeStatement_Quarterly[mask]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
26,Interest & dividend income,901000,NaN,1049000,NaN,1045000,NaN,1190000,NaN,1358000,NaN,1307000,NaN,1418000,NaN,1505000,NaN,1452000,NaN,1327000,NaN,1282000,NaN,1224000,NaN,1036000,NaN,986000,NaN,941000,NaN,766000,NaN,675000,NaN,654000,NaN,439000,NaN,410000,NaN,427000,NaN,-,NaN,420000,NaN,421000,NaN,-,NaN,254000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
42,Cash dividends declared per share,0.205,NaN,0.193,NaN,0.193,NaN,0.193,NaN,0.183,NaN,0.183,NaN,0.183,NaN,0.158,NaN,0.158,NaN,0.158,NaN,0.143,NaN,0.143,NaN,0.143,NaN,0.13,NaN,0.13,NaN,0.13,NaN,0.118,NaN,0.118,NaN,0.118,NaN,0.109,NaN,0.109,NaN,0.109,NaN,0.095,NaN,0.095,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-

In [687]:
IncomeStatement_Quarterly.iloc[42].T
IncomeStatement_Quarterly.iloc[42] = IncomeStatement_Quarterly.iloc[42].replace('-', 0)
IncomeStatement_Quarterly

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Powered by Clearbit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Apple Inc (NMS: AAPL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Exchange rate used is that of the Year End rep...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,As Reported Quarterly Income Statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Report Date,06/27/2020,NaN,03/28/2020,NaN,12/28/2019,NaN,06/29/2019,NaN,03/30/2019,NaN,12/29/2018,NaN,06/30/2018,NaN,03/31/2018,NaN,12/30/2017,NaN,07/01/2017,NaN,04/01/2017,NaN,12/31/2016,NaN,06/25/2016,NaN,03/26/2016,NaN,12/26/2015,NaN,06/27/2015,NaN,03/28/2015,NaN,12/27/2014,NaN,06/28/2014,NaN,03/29/2014,NaN,12/28/2013,NaN,06/29/2013,NaN,03/30/2013,NaN,12/29/2012,NaN,06/30/2012,NaN,03/31/2012,NaN,12/31/2011,NaN,06/25/2011,NaN,03/26/2011,NaN,12/25/2010,NaN,06/26/2010,NaN,03/27/2010,NaN,12/26/2009,NaN,06/27/2009,NaN,03/28/2009,NaN,12/27/2008,NaN,06/28/2008,NaN,03/29/2008,NaN,12/29/2007,NaN,06/30/2007,NaN,03/31/2007,NaN,12/30/2006,NaN,07/01/2006,NaN,04/01/2006,NaN,12/31/2005
10,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter,NaN,3rd Quarter,NaN,2nd Quarter,NaN,1st Quarter
11,Currency,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD,NaN,USD
12,Audit Status,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited,NaN,Unaudited
13,Consolidated,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes,NaN,Yes
14,Scale,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands,NaN,Thousands
15,Net sales - products,46529000,NaN,44965000,NaN,79104000,NaN,42354000,NaN,46565000,NaN,73435000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
16,Net sales - services,13156000,NaN,13348000,NaN,12715000,NaN,11455000,NaN,11450000,NaN,10875000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
17,Total net sales,59685000,NaN,58313000,NaN,91819000,NaN,53809000,NaN,58015000,NaN,84310000,NaN,53265000,NaN,61137000,NaN,88293000,NaN,45408000,NaN,52896000,NaN,78351000,NaN,42358000,NaN,50557000,NaN,75872000,NaN,49605000,NaN,58010000,NaN,74599000,NaN,37432000,NaN,45646000,NaN,57594000,NaN,35323000,NaN,43603000,NaN,54512000,NaN,35023000,NaN,39186000,NaN,46333000,NaN,28571000,NaN,24667000,NaN,26741000,NaN,15700000,NaN,13499000,NaN,15683000,NaN,8337000,NaN,8163000,NaN,10167000,NaN,7464000,NaN,7512000,NaN,9608000,NaN,5410000,NaN,5264000,NaN,7115000,NaN,4370000,NaN,4359000,NaN,5749000
18,Cost of sales - products,32693000,NaN,31321000,NaN,52075000,NaN,29473000,NaN,32047000,NaN,48238000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
19,Cost of sales - services,4312000,NaN,4622000,NaN,4527000,NaN,4109000,NaN,4147000,NaN,4041000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
20,Total cost of sales,37005000,NaN,35943000,NaN,56602000,NaN,33582000,NaN,36194000,NaN,52279000,NaN,32844000,NaN,37715000,NaN,54381000,NaN,27920000,NaN,32305000,NaN,48175000,NaN,26252000,NaN,30636000,NaN,45449000,NaN,29924000,NaN,34354000,NaN,44858000,NaN,22697000,NaN,27699000,NaN,35748000,NaN,22299000,NaN,27254000,NaN,33452000,NaN,20029000,NaN,20622000,NaN,25630000,NaN,16649000,NaN,14449000,NaN,16443000,NaN,9564000,NaN,7874000,NaN,9272000,NaN,5314000,NaN,5192000,NaN,6635000,NaN,4864000,NaN,5038000,NaN,6276000,NaN,3415000,NaN,3415000,NaN,4895000,NaN,3045000,NaN,3062000,NaN,4185000
21,Gross margin,22680000,NaN,22370000,NaN,35217000,NaN,20227000,NaN,21821000,NaN,32031000,NaN,20421000,NaN,23422000,NaN,33912000,NaN,17488000,NaN,20591000,NaN,30176000,NaN,16106000,NaN,19921000,NaN,30423000,NaN,19681000,NaN,23656000,NaN,29741000,NaN,14735000,NaN,17947000,NaN,21846000,NaN,13024000,NaN,16349000,NaN,21060000,NaN,14994000,NaN,18564000,NaN,20703000,NaN,11922000,NaN,10218000,NaN,10298000,NaN,6136000,NaN,5625000,NaN,6411000,NaN,3023000,NaN,2971000,NaN,3532000,NaN,2600000,NaN,2474000,NaN,3332000,NaN,1995000,NaN,1849000,NaN,2220000,NaN,1325000,NaN,1297000,NaN,1564000
22,Research & development expenses,4758000,NaN,4565000,NaN,4451000,NaN,4257000,NaN,3948000,NaN,3902000,NaN,3701000,NaN,3378000,NaN,3407000,NaN,2937000,NaN,2776000,NaN,2871000,NaN,2560000,NaN,2511000,NaN,2404000,NaN,2034000,NaN,1918000,NaN,1895000,NaN,1603000,NaN,1422000,NaN,1330000,NaN,1178000,NaN,1119000,NaN,1010000,NaN,876000,NaN,841000,NaN,758000,NaN,628000,NaN,581000,NaN,575000,NaN,464000,NaN,426000,NaN,398000,NaN,341000,NaN,319000,NaN,315000,NaN,292000,NaN,273000,NaN,246000,NaN,208000,NaN,183000,NaN,184000,NaN,175000,NaN,176000,NaN,182000
23,"Selling, general & administrative expenses",4831000,NaN,4952000,NaN,5197000,NaN,4426000,NaN,4458000,NaN,4783000,NaN,4108000,NaN,4150000,NaN,4231000,NaN,3783000,NaN,3718000,NaN,3946000,NaN,3441000,NaN,3423000,NaN,3848000,NaN,3564000,NaN,3460000,NaN,3600000,NaN,2850000,NaN,2932000,NaN,3053000,NaN,2645000,NaN,2672000,NaN,2840000,NaN,2545000,NaN,2339000,NaN,2605000,NaN,1915000,NaN,1763000,NaN,1896000,NaN,1438000,NaN,1220000,NaN,1288000,NaN,1010000,NaN,985000,NaN,1091000,NaN,916000,NaN,886000,NaN,960000,NaN,746000,NaN,680000,NaN,714000,NaN,584000,NaN,592000,NaN,632000
24,Total operating expenses,9589000,NaN,9517000,NaN,9648000,NaN,8683000,NaN,8406000,NaN,8685000,NaN,7809000,NaN,7528000,NaN,7638000,NaN,6720000,NaN,6494000,NaN,6817000,NaN,6001000,NaN,5934000,NaN,6252000,NaN,5598000,NaN,5378000,NaN,5495000,NaN,4453000,NaN,4354000,NaN,4383000,NaN,3823000,NaN,3791000,NaN,3850000,NaN,3421000,NaN,3180000,NaN,3363000,NaN,2543000,NaN,2344000,NaN,2471000,NaN,1902000,NaN,1646000,NaN,1686000,NaN,1351000,NaN,1304000,NaN,1406000,NaN,1208000,NaN,1159000,NaN,1206000,NaN,954000,NaN,863000,NaN,898000,NaN,759000,NaN,768000,NaN,814000
25,Operating income (loss),13091000,NaN,12853000,NaN,25569000,NaN,11544000,NaN,13415000,NaN,23346000,NaN,12612000,NaN,15894000,NaN,26274000,NaN,10768000,NaN,14097000,NaN,23359000,NaN,10105000,NaN,13987000,NaN,24171000,NaN,14083000,NaN,18278000,NaN,24246000,NaN,10282000,NaN,13593000,NaN,17463000,NaN,9201000,NaN,12558000,NaN,17210000,NaN,11573000,NaN,15384000,NaN,17340000,NaN,9379000,NaN,7874000,NaN,7827000,NaN,4234000,NaN,3979000,NaN,4725000,NaN,1672000,NaN,1667000,NaN,2126000,NaN,1392000,NaN,1315000,NaN,2126000,NaN,1041000,NaN,986000,NaN,1322000,NaN,566000,NaN,529000,NaN,750000
26,Interest & dividend income,901000,NaN,1049000,NaN,1045000,NaN,1190000,NaN,1358000,NaN,1307000,NaN,1418000,NaN,1505000,NaN,1452000,NaN,1327000,NaN,1282000,NaN,1224000,NaN,1036000,NaN,986000,NaN,941000,NaN,766000,NaN,675000,NaN,654000,NaN,439000,NaN,410000,NaN,427000,NaN,-,NaN,420000,NaN,421000,NaN,-,NaN,254000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
27,Interest expense,697000,NaN,757000,NaN,785000,NaN,866000,NaN,1010000,NaN,890000,NaN,846000,NaN,792000,NaN,734000,NaN,602000,NaN,530000,NaN,525000,NaN,409000,NaN,321000,NaN,276000,NaN,201000,NaN,163000,NaN,131000,NaN,100000,NaN,85000,NaN,84000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
28,"Other expense, net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,185000,NaN,-,NaN,-,NaN,263000,NaN,-,NaN,-,NaN,175000,NaN,-,NaN,-,NaN,137000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,13000,NaN,-,NaN,7000,NaN,4000,NaN,11000,NaN,7000
29,Interest income,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,168000,NaN,-,NaN,133000,NaN,99000,NaN,87000,NaN,88000
30,"Other income (expense), net",-158000,NaN,-10000,NaN,89000,NaN,43000,NaN,30000,NaN,143000,NaN,100000,NaN,-439000,NaN,38000,NaN,-,NaN,-165000,NaN,122000,NaN,-,NaN,-510000,NaN,-263000,NaN,-,NaN,-226000,NaN,-353000,NaN,-,NaN,-100000,NaN,-97000,NaN,-,NaN,-73000,NaN,41000,NaN,-,NaN,-106000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-
31,"Interest & other income (expense), net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,81000
32,"Other income (expense), net",46000,NaN,282000,NaN,349000,NaN,367000,NaN,378000,NaN,560000,NaN,672000,NaN,274000,NaN,756000,NaN,540000,NaN,587000,NaN,821000,NaN,364000,NaN,155000,NaN,402000,NaN,390000,NaN,286000,NaN,170000,NaN,202000,NaN,225000,NaN,246000,NaN,-,NaN,347000,NaN,462000,NaN,-,NaN,148000,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,155000,NaN,-,NaN,126000,NaN,95000,NaN,76000,NaN,-
33,"Other income (expense), net",-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN,234000,NaN,-,NaN,-,NaN,288000,NaN,-,NaN,137000,NaN,172000,NaN,26000,NaN,136000,NaN,58000,NaN,50000,NaN,33000,NaN,60000,NaN,63000,NaN,158000,NaN,118000,NaN,162000,NaN,200000,NaN,-,NaN,148000,NaN,-,NaN,-,NaN,-,NaN,-
34,Income (loss) before provision for income taxes,13137000,NaN,13135000,NaN,25918000,NaN,11911000,NaN,13793000,NaN,23906000,NaN,13284000,NaN,16168000,NaN,27030000,NaN,11308000,NaN,14684000,NaN,24180000,NaN,10469000,NaN,14142000,NaN,24573000,NaN,14473000,NaN,18564000,NaN,24416000,NaN,10484000,NaN,13818000,NaN,17709000,NaN,9435000,NaN,12905000,NaN,17672000,NaN,11861000,NaN,15532000,NaN,17477000,NaN,9551000,NaN,7900000,NaN,7963000,NaN,4292000,NaN,4029000,NaN,4758000,NaN,1732000,NaN,1730000,NaN,2284000,NaN,1510000,NaN,1477000,NaN,2326000,NaN,1196000,NaN,1134000,NaN,1448000,NaN,661000,NaN,605000,NaN,831000
35,Provision for (benefit from) income taxes,1884000,NaN,1886000,NaN,3682000,NaN,1867000,NaN,2232000,NaN,3941000,NaN,1765000,NaN,2346000,NaN,6965000,NaN,2591000,NaN,3655000,NaN,6289000,NaN,2673000,NaN,3626000,NaN,6212000,NaN,3796000,NaN,4995000,NaN,6392000,NaN,2736000,NaN,3595000,NaN,4637000,NaN,2535000,NaN,3358000,NaN,4594000,NaN,3037000,NaN,3910000,NaN,4413000,NaN,2243000,NaN,1913000,NaN,1959000,NaN,1039000,NaN,955000,NaN,1380000,NaN,503000,NaN,525000,NaN,679000,NaN,438000,NaN,432000,NaN,745000,NaN,378000,NaN,364000,NaN,444000,NaN,189000,NaN,195000,NaN,266000
36,Net income (loss),11253000,NaN,11249000,NaN,22236000,NaN,10044000,NaN,11561000,NaN,19965000,NaN,11519000,NaN,13822000,NaN,20065000,NaN,8717000,NaN,11029000,NaN,17891000,NaN,7796000,NaN,10516000,NaN,18361000,NaN,10677000,NaN,13569000,NaN,18024000,NaN,7748000,NaN,10223000,NaN,13072000,NaN,6900000,NaN,9547000,NaN,13078000,NaN,8824000,NaN,11622000,NaN,13064000,NaN,7308000,NaN,5987000,NaN,6004000,NaN,3253000,NaN,3074000,NaN,3378000,NaN,1229000,NaN,1205000,NaN,1605000,NaN,1072000,NaN,1045000,NaN,1581000,NaN,818000,NaN,770000,NaN,1004000,NaN,472000,NaN,410000,NaN,565000
37,Weighted average shares outstanding - basic,17250292,NaN,17440404,NaN,17660160,NaN,18282532,NaN,18696284,NaN,18943280,NaN,19528668,NaN,20099508,NaN,20451508,NaN,20780352,NaN,20903164,NaN,21194644,NaN,21772232,NaN,22057524,NaN,22235720,NaN,22919544,NaN,23175196,NaN,23372328,NaN,24050540,NaN,24493196,NaN,25090016,NaN,25721304,NaN,26309612,NaN,26289648,NaN,26224688,NaN,26140296,NaN,26069148,NaN,25931024,NaN,25849488,NaN,25740232,NaN,25541516,NaN,25411344,NaN,25299176,NaN,25023936,NaN,24953040,NaN,24895976,NaN,24744664,NaN,24627288,NaN,24524080,NaN,24270568,NaN,24164084,NaN,24015348,NaN,23838500,NaN,23545480,NaN,23261868
38,Weighted average shares outstanding - diluted,17419152,NaN,17618764,NaN,17818416,NaN,18405520,NaN,18802584,NaN,19093008,NaN,19706436,NaN,20273972,NaN,20631148,NaN,20933996,NaN,21046752,NaN,21311980,NaN,21891124,NaN,22163544,NaN,22376508,NaN,23092396,NaN,23339432,NaN,23527212,NaN,24206844,NaN,24626784,NaN,25240656,NaN,25879420,NaN,26488980,NaN,26522076,NaN,26517652,NaN,26457004,NaN,26364016,NaN,26258680,NaN,26206432,NaN,26128312,NaN,25966108,NaN,25840584,NaN,25753924,NaN,25456480,NaN,25283804,NaN,25241832,NaN,25288676,NaN,25181212,NaN,25201512,NaN,24938788,NaN,24826284,NaN,24732316,NaN,24538304,NaN,24599036,NaN,24477796
39,Year end shares outstanding,17135756,NaN,17295948,NaN,17539836,NaN,18125580,NaN,18429136,NaN,18919212,NaN,19371668,NaN,19773128,NaN,20326604,NaN,20679128,NaN,20823260,NaN,21021692,NaN,21572660,NaN,21913784,NaN,22177948,NaN,22821600,NaN,23049112,NaN,23305676,NaN,23956684,NaN,24128860,NaN,24988516,NaN,25436376,NaN,26322632,NaN,26291244,NaN,26243448,NaN,26179496,NaN,26101992,NaN,2.59533e+07,NaN,2.58909e+07,NaN,2.5789e+07,NaN,2.55775e+07,NaN,2.54698e+07,NaN,2.53759e+07,NaN,2.50806e+07,NaN,2.49735e+07,NaN,2.49316e+07,NaN,2.48009e+07,NaN,2.46801e+07,NaN,2.46016e+07,NaN,2.43365e+07,NaN,2.42114e+07,NaN,2.40862e+07,NaN,2.38837e+07,NaN,2.37773e+07,NaN,2.36773e+07

In [691]:
# IncomeStatement_Quarterly.iloc[42].replace('[A-Za-z]{4}', 0, regex = True)

In [692]:
dec_df_copy = data_cleaning(IncomeStatement_Quarterly,42 , dec_df_copy )
dec_df_copy

Cash Dividends Declared Per Share

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3994: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                   Close        High         Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0          NaN
     2          1.352740    1.375603    1.332132      5749000.0     0.000000
     3          1.632829    1.650273    1.608292      5749000.0     0.000000
     4          2.267874    2.295085    2.232783      5749000.0     0.000000
2006 1          2.505685    2.559983    2.467074      4359000.0   -24.178118
     2          2.286786    2.328282    2.255096      4359000.0     0.000000
     3          2.364666    2.395510    2.328226      4370000.0     0.252351
     4          2.958299    2.993095    2.922098      7115000.0    62.814645
2007 1          3.161434    3.198688    3.124374      5264000.0   -26.015460
     2          3.868152    3.911213    3.819632      5410000.0     2.773556
     3          4.843560    4.917976    4.756417      9608000.0    77.597043
     4          6.378103    6.478594    6.254314      9608000.0     0.000000
2008 1          4.969239    5.091739    4.861475      7512000.0   -21.815154
     2          6.198811    6.287919    6.089431      7464000.0    -0.638978
     3          5.719330    5.841925    5.604046     10167000.0    36.213826
     4          3.390580    3.504258    3.277282     10167000.0     0.000000
2009 1          3.341932    3.404854    3.276996      8163000.0   -19.710829
     2          4.621905    4.674467    4.550397      8337000.0     2.131569
     3          5.865184    5.913728    5.804018     15683000.0    88.113230
     4          7.045586    7.121797    6.978984     15683000.0     0.000000
2010 1          7.530539    7.605164    7.447541     13499000.0   -13.925907
     2          9.097817    9.215408    8.952097     15700000.0    16.304911
     3          9.282327    9.375893    9.172846     26741000.0    70.324841
     4         11.124810   11.199632   11.035692     26741000.0     0.000000
2011 1         12.345830   12.433525   12.223433     24667000.0    -7.755880
     2         12.057585   12.168316   11.964943     28571000.0    15.826813
     3         13.589654   13.743108   13.414397     46333000.0    62.167933
     4         13.987806   14.123345   13.849422     46333000.0     0.000000
2012 1         17.988566   18.112079   17.793992     39186000.0   -15.425291
     2         20.753220   21.005403   20.527902     35023000.0   -10.623692
     3         22.876553   23.032630   22.669093     54512000.0    55.646290
     4         20.634424   20.927817   20.386187     54512000.0     0.000000
2013 1         16.649083   16.863107   16.481637     43603000.0   -20.012107
     2         15.383677   15.582623   15.222015     35323000.0   -18.989519
     3         16.580195   16.742271   16.435720     57594000.0    63.049571
     4         18.891892   19.033917   18.737980     57594000.0     0.000000
2014 1         19.021592   19.174455   18.879549     45646000.0   -20.745217
     2         21.279382   21.413271   21.106015     37432000.0   -17.995005
     3         24.540859   24.739531   24.327422     74599000.0    99.292050
     4         27.205313   27.465469   26.948008     74599000.0     0.000000
2015 1         30.194262   30.514057   29.889016     58010000.0   -22.237564
     2         31.984524   32.242222   31.759048     49605000.0   -14.488881
     3         29.325859   29.688789   28.963242     75872000.0    52.952323
     4         28.574844   28.839141   28.291836     75872000.0     0.000000
2016 1         24.913770   25.169385   24.618688     50557000.0   -33.365405
     2         24.850313   25.066563   24.645742     42358000.0   -16.217339
     3         26.466523   26.629531   26.276172     78351000.0    84.973323
     4         28.349762   28.540159   28.122936     78351000.0     0.000000
2017 1         32.928145   33.041290   32.713387     52896000.0   -32.488418
     2         36.968849   37.205000   36.719960     52896000.0     0.000000
     3         38.792262   39.065119   38.494127     45408000.0   -14.156080
     4         41.787064   42.018294   41.486230     88293000.0    94.443710
2018 1         43.047828   43.524303   42.654017     61137000.0   -30.756685
     2         45.349141   45.678125   44.980117     53265000.0   -12.876000
     3         52.075000   52.473532   51.630238     84310000.0    58.284051
     4         48.478016   49.216905   47.816468     84310000.0     0.000000
2019 1         42.415943   42.764181   41.969795     58015000.0   -31.188471
     2         48.723175   49.139563   48.247698     53809000.0    -7.249849
     3         52.280195   52.753438   51.826523     91819000.0    70.638741
     4         64.332187   64.668281   63.725820     91819000.0     0.000000
2020 1         73.540927   74.693105   72.257581     58313000.0   -36.491358
     2         77.490317   78.341389   76.394960     59685000.0     2.352820
     3        109.115351  110.836680  107.262734            NaN     0.000000
     4        116.550244  118.171951  115.108536            NaN     0.000000

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0
     2        24599036.0                   23777268.0           410000.0
     3        24538304.0                   23883653.0           472000.0
     4        24732316.0                   24086156.0          1004000.0
2007 1        24826284.0                   24211406.0           770000.0
     2        24938788.0                   24336530.0           818000.0
     3               NaN                   24601608.0          1581000.0
     4        25201512.0                   24601608.0          1581000.0
2008 1        25181212.0                   24680068.0          1045000.0
     2        25288676.0                   24800906.0          1072000.0
     3               NaN                   24931617.0          1605000.0
     4        25241832.0                   24931617.0          1605000.0
2009 1        25283804.0                   24973530.0          1205000.0
     2        25456480.0                   25080585.0          1229000.0
     3               NaN                   25375901.0          3378000.0
     4        25753924.0                   25375901.0          3378000.0
2010 1        25840584.0                   25469802.0          3074000.0
     2        25966108.0                   25577505.0          3253000.0
     3               NaN                   25788993.0          6004000.0
     4        26128312.0                   25788993.0          6004000.0
2011 1        26206432.0                   25890874.0          5987000.0
     2        26258680.0                   25953305.0          7308000.0
     3               NaN                   26101992.0         13064000.0
     4        26364016.0                   26101992.0         13064000.0
2012 1        26457004.0                   26179496.0         11622000.0
     2        26517652.0                   26243448.0          8824000.0
     3               NaN                   26291244.0         13078000.0
     4        26522076.0                   26291244.0         13078000.0
2013 1        26488980.0                   26322632.0          9547000.0
     2        25879420.0                   25436376.0          6900000.0
     3               NaN                   24988516.0         13072000.0
     4        25240656.0                   24988516.0         13072000.0
2014 1        24626784.0                   24128860.0         10223000.0
     2        24206844.0                   23956684.0          7748000.0
     3               NaN                   23305676.0         18024000.0
     4        23527212.0                   23305676.0         18024000.0
2015 1        23339432.0                   23049112.0         13569000.0
     2        23092396.0                   22821600.0         10677000.0
     3               NaN                   22177948.0         18361000.0
     4        22376508.0                   22177948.0         18361000.0
2016 1        22163544.0                   21913784.0         10516000.0
     2        21891124.0                   21572660.0          7796000.0
     3               NaN                   21021692.0         17891000.0
     4        21311980.0                   21021692.0         17891000.0
2017 1               NaN                   20823260.0         11029000.0
     2        21046752.0                   20823260.0         11029000.0
     3        20933996.0                   20679128.0          8717000.0
     4        20631148.0                   20326604.0         20065000.0
2018 1        20273972.0                   19773128.0         13822000.0
     2        19706436.0                   19371668.0         11519000.0
     3               NaN                   18919212.0         19965000.0
     4        19093008.0                   18919212.0         19965000.0
2019 1        18802584.0                   18429136.0         11561000.0
     2        18405520.0                   18125580.0         10044000.0
     3               NaN                   17539836.0         22236000.0
     4        17818416.0                   17539836.0         22236000.0
2020 1        17618764.0                   17295948.0         11249000.0
     2        17419152.0                   17135756.0         11253000.0
     3               NaN                          NaN                NaN
     4               NaN                          NaN                NaN

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964
     2                    0.017243        4359000.0              0.000000
     3                    0.019762        4370000.0             -0.194203
     4                    0.041684        7115000.0             61.445790
2007 1                    0.031803        5264000.0            -26.398196
     2                    0.033612        5410000.0              2.245156
     3                    0.064264        9608000.0             75.683466
     4                    0.064264        9608000.0              0.000000
2008 1                    0.042342        7512000.0            -22.063710
     2                    0.043224        7464000.0             -1.123097
     3                    0.064376       10167000.0             35.499687
     4                    0.064376       10167000.0              0.000000
2009 1                    0.048251        8163000.0            -19.845578
     2                    0.049002        8337000.0              1.695627
     3                    0.133118       15683000.0             85.924033
     4                    0.133118       15683000.0              0.000000
2010 1                    0.120692       13499000.0            -14.243241
     2                    0.127182       15700000.0             15.815169
     3                    0.232813       26741000.0             68.928056
     4                    0.232813       26741000.0              0.000000
2011 1                    0.231240       24667000.0             -8.118863
     2                    0.281583       28571000.0             15.548190
     3                    0.500498       46333000.0             61.244162
     4                    0.500498       46333000.0              0.000000
2012 1                    0.443935       39186000.0            -15.675673
     2                    0.336236       35023000.0            -10.841491
     3                    0.497428       54512000.0             55.363333
     4                    0.497428       54512000.0              0.000000
2013 1                    0.362692       43603000.0            -20.107488
     2                    0.271265       35323000.0            -16.166946
     3                    0.523120       57594000.0             65.971849
     4                    0.523120       57594000.0              0.000000
2014 1                    0.423684       45646000.0            -17.921550
     2                    0.323417       37432000.0            -17.405637
     3                    0.773374       74599000.0            104.858965
     4                    0.773374       74599000.0              0.000000
2015 1                    0.588699       58010000.0            -21.371975
     2                    0.467846       49605000.0            -13.636408
     3                    0.827894       75872000.0             57.391330
     4                    0.827894       75872000.0              0.000000
2016 1                    0.479881       50557000.0            -32.562145
     2                    0.361383       42358000.0            -14.892501
     3                    0.851073       78351000.0             89.821381
     4                    0.851073       78351000.0              0.000000
2017 1                    0.529648       52896000.0            -31.845076
     2                    0.529648       52896000.0              0.000000
     3                    0.421536       45408000.0            -13.557754
     4                    0.987130       88293000.0             97.815945
2018 1                    0.699030       61137000.0            -28.818473
     2                    0.594631       53265000.0            -11.070435
     3                    1.055277       84310000.0             62.069440
     4                    1.055277       84310000.0              0.000000
2019 1                    0.627322       58015000.0            -29.358604
     2                    0.554134       53809000.0             -5.696527
     3                    1.267743       91819000.0             76.337233
     4                    1.267743       91819000.0              0.000000
2020 1                    0.650384       58313000.0            -35.595831
     2                    0.656697       59685000.0              3.309656
     3                         NaN              NaN              0.000000
     4                         NaN              NaN              0.000000

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309
     2               0.183326          0.078739         0.081294
     3               0.182970          0.076381         0.078588
     4               0.295398          0.098693         0.101091
2007 1               0.217418          0.067971         0.069588
     2               0.222300          0.056836         0.058199
     3               0.390544          0.079411         0.082109
     4               0.390544          0.060282         0.062444
2008 1               0.304375          0.059778         0.062610
     2               0.300957          0.047863         0.049423
     3               0.407795          0.069805         0.072768
     4               0.407795          0.116371         0.124431
2009 1               0.326866          0.096000         0.099746
     2               0.332409          0.071112         0.073050
     3               0.618027          0.104507         0.106483
     4               0.618027          0.086780         0.088555
2010 1               0.530000          0.069690         0.071164
     2               0.613821          0.066608         0.068567
     3               1.036915          0.110594         0.113042
     4               1.036915          0.092585         0.093960
2011 1               0.952730          0.076626         0.077943
     2               1.100862          0.090470         0.092007
     3               1.775075          0.129161         0.132326
     4               1.775075          0.125684         0.128170
2012 1               1.496820          0.082642         0.084119
     2               1.334543          0.063533         0.065011
     3               2.073390          0.090020         0.091463
     4               2.073390          0.099073         0.101706
2013 1               1.656483          0.098231         0.100505
     2               1.388681          0.089117         0.091228
     3               2.304819          0.137665         0.140232
     4               2.304819          0.121090         0.123003
2014 1               1.891759          0.098660         0.100202
     2               1.562487          0.072968         0.074030
     3               3.200894          0.129384         0.131576
     4               3.200894          0.116542         0.118780
2015 1               2.516800          0.082480         0.084205
     2               2.173599          0.067415         0.068440
     3               3.421056          0.115231         0.118117
     4               3.421056          0.118625         0.120920
2016 1               2.307087          0.091662         0.093713
     2               1.963504          0.078332         0.079669
     3               3.727150          0.139963         0.141845
     4               3.727150          0.130593         0.132531
2017 1               2.540236          0.076881         0.077651
     2               2.540236          0.068277         0.069179
     3               2.195837          0.056210         0.057043
     4               4.343716          0.103377         0.104703
2018 1               3.091924          0.071039         0.072488
     2               2.749634          0.060196         0.061130
     3               4.456317          0.084925         0.086312
     4               4.456317          0.090544         0.093196
2019 1               3.148004          0.073613         0.075006
     2               2.968677          0.060413         0.061530
     3               5.234884          0.099233         0.101008
     4               5.234884          0.080950         0.082147
2020 1               3.371483          0.045138         0.046659
     2               3.483068          0.044460         0.045593
     3                    NaN               NaN              NaN
     4                    NaN               NaN              NaN

              freeCashFlowPerShare   P/E ratio  \
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000
     2                   -0.012927  134.400000
     3                    0.031377  106.341230
     4                    0.062914   74.122611
2007 1                    0.021851  104.131950
     2                    0.038648  129.321538
     3                    0.058293  158.006047
     4                    0.101389  109.662809
2008 1                    0.038840  116.809128
     2                    0.039189  135.822787
     3                    0.152865   51.641691
     4                    0.142036   34.302257
2009 1                    0.028674   59.558990
     2                    0.078488   70.841527
     3                    0.103031   65.862690
     4                    0.209692   57.614192
2010 1                    0.078522   69.319356
     2                    0.160775   76.036028
     3                    0.187250   63.027744

                   Close        High         Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0          NaN
     2          1.352740    1.375603    1.332132      5749000.0     0.000000
     3          1.632829    1.650273    1.608292      5749000.0     0.000000
     4          2.267874    2.295085    2.232783      5749000.0     0.000000
2006 1          2.505685    2.559983    2.467074      4359000.0   -24.178118
     2          2.286786    2.328282    2.255096      4359000.0     0.000000
     3          2.364666    2.395510    2.328226      4370000.0     0.252351
     4          2.958299    2.993095    2.922098      7115000.0    62.814645
2007 1          3.161434    3.198688    3.124374      5264000.0   -26.015460
     2          3.868152    3.911213    3.819632      5410000.0     2.773556
     3          4.843560    4.917976    4.756417      9608000.0    77.597043
     4          6.378103    6.478594    6.254314      9608000.0     0.000000
2008 1          4.969239    5.091739    4.861475      7512000.0   -21.815154
     2          6.198811    6.287919    6.089431      7464000.0    -0.638978
     3          5.719330    5.841925    5.604046     10167000.0    36.213826
     4          3.390580    3.504258    3.277282     10167000.0     0.000000
2009 1          3.341932    3.404854    3.276996      8163000.0   -19.710829
     2          4.621905    4.674467    4.550397      8337000.0     2.131569
     3          5.865184    5.913728    5.804018     15683000.0    88.113230
     4          7.045586    7.121797    6.978984     15683000.0     0.000000
2010 1          7.530539    7.605164    7.447541     13499000.0   -13.925907
     2          9.097817    9.215408    8.952097     15700000.0    16.304911
     3          9.282327    9.375893    9.172846     26741000.0    70.324841
     4         11.124810   11.199632   11.035692     26741000.0     0.000000
2011 1         12.345830   12.433525   12.223433     24667000.0    -7.755880
     2         12.057585   12.168316   11.964943     28571000.0    15.826813
     3         13.589654   13.743108   13.414397     46333000.0    62.167933
     4         13.987806   14.123345   13.849422     46333000.0     0.000000
2012 1         17.988566   18.112079   17.793992     39186000.0   -15.425291
     2         20.753220   21.005403   20.527902     35023000.0   -10.623692
     3         22.876553   23.032630   22.669093     54512000.0    55.646290
     4         20.634424   20.927817   20.386187     54512000.0     0.000000
2013 1         16.649083   16.863107   16.481637     43603000.0   -20.012107
     2         15.383677   15.582623   15.222015     35323000.0   -18.989519
     3         16.580195   16.742271   16.435720     57594000.0    63.049571
     4         18.891892   19.033917   18.737980     57594000.0     0.000000
2014 1         19.021592   19.174455   18.879549     45646000.0   -20.745217
     2         21.279382   21.413271   21.106015     37432000.0   -17.995005
     3         24.540859   24.739531   24.327422     74599000.0    99.292050
     4         27.205313   27.465469   26.948008     74599000.0     0.000000
2015 1         30.194262   30.514057   29.889016     58010000.0   -22.237564
     2         31.984524   32.242222   31.759048     49605000.0   -14.488881
     3         29.325859   29.688789   28.963242     75872000.0    52.952323
     4         28.574844   28.839141   28.291836     75872000.0     0.000000
2016 1         24.913770   25.169385   24.618688     50557000.0   -33.365405
     2         24.850313   25.066563   24.645742     42358000.0   -16.217339
     3         26.466523   26.629531   26.276172     78351000.0    84.973323
     4         28.349762   28.540159   28.122936     78351000.0     0.000000
2017 1         32.928145   33.041290   32.713387     52896000.0   -32.488418
     2         36.968849   37.205000   36.719960     52896000.0     0.000000
     3         38.792262   39.065119   38.494127     45408000.0   -14.156080
     4         41.787064   42.018294   41.486230     88293000.0    94.443710
2018 1         43.047828   43.524303   42.654017     61137000.0   -30.756685
     2         45.349141   45.678125   44.980117     53265000.0   -12.876000
     3         52.075000   52.473532   51.630238     84310000.0    58.284051
     4         48.478016   49.216905   47.816468     84310000.0     0.000000
2019 1         42.415943   42.764181   41.969795     58015000.0   -31.188471
     2         48.723175   49.139563   48.247698     53809000.0    -7.249849
     3         52.280195   52.753438   51.826523     91819000.0    70.638741
     4         64.332187   64.668281   63.725820     91819000.0     0.000000
2020 1         73.540927   74.693105   72.257581     58313000.0   -36.491358
     2         77.490317   78.341389   76.394960     59685000.0     2.352820
     3        109.115351  110.836680  107.262734            NaN     0.000000
     4        116.550244  118.171951  115.108536            NaN     0.000000

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0
     2        24599036.0                   23777268.0           410000.0
     3        24538304.0                   23883653.0           472000.0
     4        24732316.0                   24086156.0          1004000.0
2007 1        24826284.0                   24211406.0           770000.0
     2        24938788.0                   24336530.0           818000.0
     3               NaN                   24601608.0          1581000.0
     4        25201512.0                   24601608.0          1581000.0
2008 1        25181212.0                   24680068.0          1045000.0
     2        25288676.0                   24800906.0          1072000.0
     3               NaN                   24931617.0          1605000.0
     4        25241832.0                   24931617.0          1605000.0
2009 1        25283804.0                   24973530.0          1205000.0
     2        25456480.0                   25080585.0          1229000.0
     3               NaN                   25375901.0          3378000.0
     4        25753924.0                   25375901.0          3378000.0
2010 1        25840584.0                   25469802.0          3074000.0
     2        25966108.0                   25577505.0          3253000.0
     3               NaN                   25788993.0          6004000.0
     4        26128312.0                   25788993.0          6004000.0
2011 1        26206432.0                   25890874.0          5987000.0
     2        26258680.0                   25953305.0          7308000.0
     3               NaN                   26101992.0         13064000.0
     4        26364016.0                   26101992.0         13064000.0
2012 1        26457004.0                   26179496.0         11622000.0
     2        26517652.0                   26243448.0          8824000.0
     3               NaN                   26291244.0         13078000.0
     4        26522076.0                   26291244.0         13078000.0
2013 1        26488980.0                   26322632.0          9547000.0
     2        25879420.0                   25436376.0          6900000.0
     3               NaN                   24988516.0         13072000.0
     4        25240656.0                   24988516.0         13072000.0
2014 1        24626784.0                   24128860.0         10223000.0
     2        24206844.0                   23956684.0          7748000.0
     3               NaN                   23305676.0         18024000.0
     4        23527212.0                   23305676.0         18024000.0
2015 1        23339432.0                   23049112.0         13569000.0
     2        23092396.0                   22821600.0         10677000.0
     3               NaN                   22177948.0         18361000.0
     4        22376508.0                   22177948.0         18361000.0
2016 1        22163544.0                   21913784.0         10516000.0
     2        21891124.0                   21572660.0          7796000.0
     3               NaN                   21021692.0         17891000.0
     4        21311980.0                   21021692.0         17891000.0
2017 1               NaN                   20823260.0         11029000.0
     2        21046752.0                   20823260.0         11029000.0
     3        20933996.0                   20679128.0          8717000.0
     4        20631148.0                   20326604.0         20065000.0
2018 1        20273972.0                   19773128.0         13822000.0
     2        19706436.0                   19371668.0         11519000.0
     3               NaN                   18919212.0         19965000.0
     4        19093008.0                   18919212.0         19965000.0
2019 1        18802584.0                   18429136.0         11561000.0
     2        18405520.0                   18125580.0         10044000.0
     3               NaN                   17539836.0         22236000.0
     4        17818416.0                   17539836.0         22236000.0
2020 1        17618764.0                   17295948.0         11249000.0
     2        17419152.0                   17135756.0         11253000.0
     3               NaN                          NaN                NaN
     4               NaN                          NaN                NaN

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964
     2                    0.017243        4359000.0              0.000000
     3                    0.019762        4370000.0             -0.194203
     4                    0.041684        7115000.0             61.445790
2007 1                    0.031803        5264000.0            -26.398196
     2                    0.033612        5410000.0              2.245156
     3                    0.064264        9608000.0             75.683466
     4                    0.064264        9608000.0              0.000000
2008 1                    0.042342        7512000.0            -22.063710
     2                    0.043224        7464000.0             -1.123097
     3                    0.064376       10167000.0             35.499687
     4                    0.064376       10167000.0              0.000000
2009 1                    0.048251        8163000.0            -19.845578
     2                    0.049002        8337000.0              1.695627
     3                    0.133118       15683000.0             85.924033
     4                    0.133118       15683000.0              0.000000
2010 1                    0.120692       13499000.0            -14.243241
     2                    0.127182       15700000.0             15.815169
     3                    0.232813       26741000.0             68.928056
     4                    0.232813       26741000.0              0.000000
2011 1                    0.231240       24667000.0             -8.118863
     2                    0.281583       28571000.0             15.548190
     3                    0.500498       46333000.0             61.244162
     4                    0.500498       46333000.0              0.000000
2012 1                    0.443935       39186000.0            -15.675673
     2                    0.336236       35023000.0            -10.841491
     3                    0.497428       54512000.0             55.363333
     4                    0.497428       54512000.0              0.000000
2013 1                    0.362692       43603000.0            -20.107488
     2                    0.271265       35323000.0            -16.166946
     3                    0.523120       57594000.0             65.971849
     4                    0.523120       57594000.0              0.000000
2014 1                    0.423684       45646000.0            -17.921550
     2                    0.323417       37432000.0            -17.405637
     3                    0.773374       74599000.0            104.858965
     4                    0.773374       74599000.0              0.000000
2015 1                    0.588699       58010000.0            -21.371975
     2                    0.467846       49605000.0            -13.636408
     3                    0.827894       75872000.0             57.391330
     4                    0.827894       75872000.0              0.000000
2016 1                    0.479881       50557000.0            -32.562145
     2                    0.361383       42358000.0            -14.892501
     3                    0.851073       78351000.0             89.821381
     4                    0.851073       78351000.0              0.000000
2017 1                    0.529648       52896000.0            -31.845076
     2                    0.529648       52896000.0              0.000000
     3                    0.421536       45408000.0            -13.557754
     4                    0.987130       88293000.0             97.815945
2018 1                    0.699030       61137000.0            -28.818473
     2                    0.594631       53265000.0            -11.070435
     3                    1.055277       84310000.0             62.069440
     4                    1.055277       84310000.0              0.000000
2019 1                    0.627322       58015000.0            -29.358604
     2                    0.554134       53809000.0             -5.696527
     3                    1.267743       91819000.0             76.337233
     4                    1.267743       91819000.0              0.000000
2020 1                    0.650384       58313000.0            -35.595831
     2                    0.656697       59685000.0              3.309656
     3                         NaN              NaN              0.000000
     4                         NaN              NaN              0.000000

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309
     2               0.183326          0.078739         0.081294
     3               0.182970          0.076381         0.078588
     4               0.295398          0.098693         0.101091
2007 1               0.217418          0.067971         0.069588
     2               0.222300          0.056836         0.058199
     3               0.390544          0.079411         0.082109
     4               0.390544          0.060282         0.062444
2008 1               0.304375          0.059778         0.062610
     2               0.300957          0.047863         0.049423
     3               0.407795          0.069805         0.072768
     4               0.407795          0.116371         0.124431
2009 1               0.326866          0.096000         0.099746
     2               0.332409          0.071112         0.073050
     3               0.618027          0.104507         0.106483
     4               0.618027          0.086780         0.088555
2010 1               0.530000          0.069690         0.071164
     2               0.613821          0.066608         0.068567
     3               1.036915          0.110594         0.113042
     4               1.036915          0.092585         0.093960
2011 1               0.952730          0.076626         0.077943
     2               1.100862          0.090470         0.092007
     3               1.775075          0.129161         0.132326
     4               1.775075          0.125684         0.128170
2012 1               1.496820          0.082642         0.084119
     2               1.334543          0.063533         0.065011
     3               2.073390          0.090020         0.091463
     4               2.073390          0.099073         0.101706
2013 1               1.656483          0.098231         0.100505
     2               1.388681          0.089117         0.091228
     3               2.304819          0.137665         0.140232
     4               2.304819          0.121090         0.123003
2014 1               1.891759          0.098660         0.100202
     2               1.562487          0.072968         0.074030
     3               3.200894          0.129384         0.131576
     4               3.200894          0.116542         0.118780
2015 1               2.516800          0.082480         0.084205
     2               2.173599          0.067415         0.068440
     3               3.421056          0.115231         0.118117
     4               3.421056          0.118625         0.120920
2016 1               2.307087          0.091662         0.093713
     2               1.963504          0.078332         0.079669
     3               3.727150          0.139963         0.141845
     4               3.727150          0.130593         0.132531
2017 1               2.540236          0.076881         0.077651
     2               2.540236          0.068277         0.069179
     3               2.195837          0.056210         0.057043
     4               4.343716          0.103377         0.104703
2018 1               3.091924          0.071039         0.072488
     2               2.749634          0.060196         0.061130
     3               4.456317          0.084925         0.086312
     4               4.456317          0.090544         0.093196
2019 1               3.148004          0.073613         0.075006
     2               2.968677          0.060413         0.061530
     3               5.234884          0.099233         0.101008
     4               5.234884          0.080950         0.082147
2020 1               3.371483          0.045138         0.046659
     2               3.483068          0.044460         0.045593
     3                    NaN               NaN              NaN
     4                    NaN               NaN              NaN

              freeCashFlowPerShare   P/E ratio  \
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000
     2                   -0.012927  134.400000
     3                    0.031377  106.341230
     4                    0.062914   74.122611
2007 1                    0.021851  104.131950
     2                    0.038648  129.321538
     3                    0.058293  158.006047
     4                    0.101389  109.662809
2008 1                    0.038840  116.809128
     2                    0.039189  135.822787
     3                    0.152865   51.641691
     4                    0.142036   34.302257
2009 1                    0.028674   59.558990
     2                    0.078488   70.841527
     3                    0.103031   65.862690
     4                    0.209692   57.614192
2010 1                    0.078522   69.319356
     2                    0.160775   76.036028
     3                    0.187250   63.027744

                   Close        High         Low  Total Revenue  %Rev Growth  \
Year Quarter
2005 1          1.411996    1.433908    1.390404      5749000.0          NaN
     2          1.352740    1.375603    1.332132      5749000.0     0.000000
     3          1.632829    1.650273    1.608292      5749000.0     0.000000
     4          2.267874    2.295085    2.232783      5749000.0     0.000000
2006 1          2.505685    2.559983    2.467074      4359000.0   -24.178118
     2          2.286786    2.328282    2.255096      4359000.0     0.000000
     3          2.364666    2.395510    2.328226      4370000.0     0.252351
     4          2.958299    2.993095    2.922098      7115000.0    62.814645
2007 1          3.161434    3.198688    3.124374      5264000.0   -26.015460
     2          3.868152    3.911213    3.819632      5410000.0     2.773556
     3          4.843560    4.917976    4.756417      9608000.0    77.597043
     4          6.378103    6.478594    6.254314      9608000.0     0.000000
2008 1          4.969239    5.091739    4.861475      7512000.0   -21.815154
     2          6.198811    6.287919    6.089431      7464000.0    -0.638978
     3          5.719330    5.841925    5.604046     10167000.0    36.213826
     4          3.390580    3.504258    3.277282     10167000.0     0.000000
2009 1          3.341932    3.404854    3.276996      8163000.0   -19.710829
     2          4.621905    4.674467    4.550397      8337000.0     2.131569
     3          5.865184    5.913728    5.804018     15683000.0    88.113230
     4          7.045586    7.121797    6.978984     15683000.0     0.000000
2010 1          7.530539    7.605164    7.447541     13499000.0   -13.925907
     2          9.097817    9.215408    8.952097     15700000.0    16.304911
     3          9.282327    9.375893    9.172846     26741000.0    70.324841
     4         11.124810   11.199632   11.035692     26741000.0     0.000000
2011 1         12.345830   12.433525   12.223433     24667000.0    -7.755880
     2         12.057585   12.168316   11.964943     28571000.0    15.826813
     3         13.589654   13.743108   13.414397     46333000.0    62.167933
     4         13.987806   14.123345   13.849422     46333000.0     0.000000
2012 1         17.988566   18.112079   17.793992     39186000.0   -15.425291
     2         20.753220   21.005403   20.527902     35023000.0   -10.623692
     3         22.876553   23.032630   22.669093     54512000.0    55.646290
     4         20.634424   20.927817   20.386187     54512000.0     0.000000
2013 1         16.649083   16.863107   16.481637     43603000.0   -20.012107
     2         15.383677   15.582623   15.222015     35323000.0   -18.989519
     3         16.580195   16.742271   16.435720     57594000.0    63.049571
     4         18.891892   19.033917   18.737980     57594000.0     0.000000
2014 1         19.021592   19.174455   18.879549     45646000.0   -20.745217
     2         21.279382   21.413271   21.106015     37432000.0   -17.995005
     3         24.540859   24.739531   24.327422     74599000.0    99.292050
     4         27.205313   27.465469   26.948008     74599000.0     0.000000
2015 1         30.194262   30.514057   29.889016     58010000.0   -22.237564
     2         31.984524   32.242222   31.759048     49605000.0   -14.488881
     3         29.325859   29.688789   28.963242     75872000.0    52.952323
     4         28.574844   28.839141   28.291836     75872000.0     0.000000
2016 1         24.913770   25.169385   24.618688     50557000.0   -33.365405
     2         24.850313   25.066563   24.645742     42358000.0   -16.217339
     3         26.466523   26.629531   26.276172     78351000.0    84.973323
     4         28.349762   28.540159   28.122936     78351000.0     0.000000
2017 1         32.928145   33.041290   32.713387     52896000.0   -32.488418
     2         36.968849   37.205000   36.719960     52896000.0     0.000000
     3         38.792262   39.065119   38.494127     45408000.0   -14.156080
     4         41.787064   42.018294   41.486230     88293000.0    94.443710
2018 1         43.047828   43.524303   42.654017     61137000.0   -30.756685
     2         45.349141   45.678125   44.980117     53265000.0   -12.876000
     3         52.075000   52.473532   51.630238     84310000.0    58.284051
     4         48.478016   49.216905   47.816468     84310000.0     0.000000
2019 1         42.415943   42.764181   41.969795     58015000.0   -31.188471
     2         48.723175   49.139563   48.247698     53809000.0    -7.249849
     3         52.280195   52.753438   51.826523     91819000.0    70.638741
     4         64.332187   64.668281   63.725820     91819000.0     0.000000
2020 1         73.540927   74.693105   72.257581     58313000.0   -36.491358
     2         77.490317   78.341389   76.394960     59685000.0     2.352820
     3        109.115351  110.836680  107.262734            NaN     0.000000
     4        116.550244  118.171951  115.108536            NaN     0.000000

              Avg_Shares  Year End Shares Outstanding  Net Income (Loss)  \
Year Quarter
2005 1               NaN                   23677280.0           565000.0
     2               NaN                   23677280.0           565000.0
     3               NaN                   23677280.0           565000.0
     4        24477796.0                   23677280.0           565000.0
2006 1               NaN                   23777268.0           410000.0
     2        24599036.0                   23777268.0           410000.0
     3        24538304.0                   23883653.0           472000.0
     4        24732316.0                   24086156.0          1004000.0
2007 1        24826284.0                   24211406.0           770000.0
     2        24938788.0                   24336530.0           818000.0
     3               NaN                   24601608.0          1581000.0
     4        25201512.0                   24601608.0          1581000.0
2008 1        25181212.0                   24680068.0          1045000.0
     2        25288676.0                   24800906.0          1072000.0
     3               NaN                   24931617.0          1605000.0
     4        25241832.0                   24931617.0          1605000.0
2009 1        25283804.0                   24973530.0          1205000.0
     2        25456480.0                   25080585.0          1229000.0
     3               NaN                   25375901.0          3378000.0
     4        25753924.0                   25375901.0          3378000.0
2010 1        25840584.0                   25469802.0          3074000.0
     2        25966108.0                   25577505.0          3253000.0
     3               NaN                   25788993.0          6004000.0
     4        26128312.0                   25788993.0          6004000.0
2011 1        26206432.0                   25890874.0          5987000.0
     2        26258680.0                   25953305.0          7308000.0
     3               NaN                   26101992.0         13064000.0
     4        26364016.0                   26101992.0         13064000.0
2012 1        26457004.0                   26179496.0         11622000.0
     2        26517652.0                   26243448.0          8824000.0
     3               NaN                   26291244.0         13078000.0
     4        26522076.0                   26291244.0         13078000.0
2013 1        26488980.0                   26322632.0          9547000.0
     2        25879420.0                   25436376.0          6900000.0
     3               NaN                   24988516.0         13072000.0
     4        25240656.0                   24988516.0         13072000.0
2014 1        24626784.0                   24128860.0         10223000.0
     2        24206844.0                   23956684.0          7748000.0
     3               NaN                   23305676.0         18024000.0
     4        23527212.0                   23305676.0         18024000.0
2015 1        23339432.0                   23049112.0         13569000.0
     2        23092396.0                   22821600.0         10677000.0
     3               NaN                   22177948.0         18361000.0
     4        22376508.0                   22177948.0         18361000.0
2016 1        22163544.0                   21913784.0         10516000.0
     2        21891124.0                   21572660.0          7796000.0
     3               NaN                   21021692.0         17891000.0
     4        21311980.0                   21021692.0         17891000.0
2017 1               NaN                   20823260.0         11029000.0
     2        21046752.0                   20823260.0         11029000.0
     3        20933996.0                   20679128.0          8717000.0
     4        20631148.0                   20326604.0         20065000.0
2018 1        20273972.0                   19773128.0         13822000.0
     2        19706436.0                   19371668.0         11519000.0
     3               NaN                   18919212.0         19965000.0
     4        19093008.0                   18919212.0         19965000.0
2019 1        18802584.0                   18429136.0         11561000.0
     2        18405520.0                   18125580.0         10044000.0
     3               NaN                   17539836.0         22236000.0
     4        17818416.0                   17539836.0         22236000.0
2020 1        17618764.0                   17295948.0         11249000.0
     2        17419152.0                   17135756.0         11253000.0
     3               NaN                          NaN                NaN
     4               NaN                          NaN                NaN

              Net Income Per Share  Total Net Sales  %Annual Sales Growth  \
Year Quarter
2005 1                    0.023863        5749000.0                   NaN
     2                    0.023863        5749000.0              0.000000
     3                    0.023863        5749000.0              0.000000
     4                    0.023863        5749000.0              0.000000
2006 1                    0.017243        4359000.0            -24.496964
     2                    0.017243        4359000.0              0.000000
     3                    0.019762        4370000.0             -0.194203
     4                    0.041684        7115000.0             61.445790
2007 1                    0.031803        5264000.0            -26.398196
     2                    0.033612        5410000.0              2.245156
     3                    0.064264        9608000.0             75.683466
     4                    0.064264        9608000.0              0.000000
2008 1                    0.042342        7512000.0            -22.063710
     2                    0.043224        7464000.0             -1.123097
     3                    0.064376       10167000.0             35.499687
     4                    0.064376       10167000.0              0.000000
2009 1                    0.048251        8163000.0            -19.845578
     2                    0.049002        8337000.0              1.695627
     3                    0.133118       15683000.0             85.924033
     4                    0.133118       15683000.0              0.000000
2010 1                    0.120692       13499000.0            -14.243241
     2                    0.127182       15700000.0             15.815169
     3                    0.232813       26741000.0             68.928056
     4                    0.232813       26741000.0              0.000000
2011 1                    0.231240       24667000.0             -8.118863
     2                    0.281583       28571000.0             15.548190
     3                    0.500498       46333000.0             61.244162
     4                    0.500498       46333000.0              0.000000
2012 1                    0.443935       39186000.0            -15.675673
     2                    0.336236       35023000.0            -10.841491
     3                    0.497428       54512000.0             55.363333
     4                    0.497428       54512000.0              0.000000
2013 1                    0.362692       43603000.0            -20.107488
     2                    0.271265       35323000.0            -16.166946
     3                    0.523120       57594000.0             65.971849
     4                    0.523120       57594000.0              0.000000
2014 1                    0.423684       45646000.0            -17.921550
     2                    0.323417       37432000.0            -17.405637
     3                    0.773374       74599000.0            104.858965
     4                    0.773374       74599000.0              0.000000
2015 1                    0.588699       58010000.0            -21.371975
     2                    0.467846       49605000.0            -13.636408
     3                    0.827894       75872000.0             57.391330
     4                    0.827894       75872000.0              0.000000
2016 1                    0.479881       50557000.0            -32.562145
     2                    0.361383       42358000.0            -14.892501
     3                    0.851073       78351000.0             89.821381
     4                    0.851073       78351000.0              0.000000
2017 1                    0.529648       52896000.0            -31.845076
     2                    0.529648       52896000.0              0.000000
     3                    0.421536       45408000.0            -13.557754
     4                    0.987130       88293000.0             97.815945
2018 1                    0.699030       61137000.0            -28.818473
     2                    0.594631       53265000.0            -11.070435
     3                    1.055277       84310000.0             62.069440
     4                    1.055277       84310000.0              0.000000
2019 1                    0.627322       58015000.0            -29.358604
     2                    0.554134       53809000.0             -5.696527
     3                    1.267743       91819000.0             76.337233
     4                    1.267743       91819000.0              0.000000
2020 1                    0.650384       58313000.0            -35.595831
     2                    0.656697       59685000.0              3.309656
     3                         NaN              NaN              0.000000
     4                         NaN              NaN              0.000000

              Sales Per Share  High Price/Share  Low Price/Share  \
Year Quarter
2005 1               0.242807          0.169332         0.174630
     2               0.242807          0.176509         0.182269
     3               0.242807          0.147131         0.150972
     4               0.242807          0.105794         0.108746
2006 1               0.183326          0.071612         0.074309
     2               0.183326          0.078739         0.081294
     3               0.182970          0.076381         0.078588
     4               0.295398          0.098693         0.101091
2007 1               0.217418          0.067971         0.069588
     2               0.222300          0.056836         0.058199
     3               0.390544          0.079411         0.082109
     4               0.390544          0.060282         0.062444
2008 1               0.304375          0.059778         0.062610
     2               0.300957          0.047863         0.049423
     3               0.407795          0.069805         0.072768
     4               0.407795          0.116371         0.124431
2009 1               0.326866          0.096000         0.099746
     2               0.332409          0.071112         0.073050
     3               0.618027          0.104507         0.106483
     4               0.618027          0.086780         0.088555
2010 1               0.530000          0.069690         0.071164
     2               0.613821          0.066608         0.068567
     3               1.036915          0.110594         0.113042
     4               1.036915          0.092585         0.093960
2011 1               0.952730          0.076626         0.077943
     2               1.100862          0.090470         0.092007
     3               1.775075          0.129161         0.132326
     4               1.775075          0.125684         0.128170
2012 1               1.496820          0.082642         0.084119
     2               1.334543          0.063533         0.065011
     3               2.073390          0.090020         0.091463
     4               2.073390          0.099073         0.101706
2013 1               1.656483          0.098231         0.100505
     2               1.388681          0.089117         0.091228
     3               2.304819          0.137665         0.140232
     4               2.304819          0.121090         0.123003
2014 1               1.891759          0.098660         0.100202
     2               1.562487          0.072968         0.074030
     3               3.200894          0.129384         0.131576
     4               3.200894          0.116542         0.118780
2015 1               2.516800          0.082480         0.084205
     2               2.173599          0.067415         0.068440
     3               3.421056          0.115231         0.118117
     4               3.421056          0.118625         0.120920
2016 1               2.307087          0.091662         0.093713
     2               1.963504          0.078332         0.079669
     3               3.727150          0.139963         0.141845
     4               3.727150          0.130593         0.132531
2017 1               2.540236          0.076881         0.077651
     2               2.540236          0.068277         0.069179
     3               2.195837          0.056210         0.057043
     4               4.343716          0.103377         0.104703
2018 1               3.091924          0.071039         0.072488
     2               2.749634          0.060196         0.061130
     3               4.456317          0.084925         0.086312
     4               4.456317          0.090544         0.093196
2019 1               3.148004          0.073613         0.075006
     2               2.968677          0.060413         0.061530
     3               5.234884          0.099233         0.101008
     4               5.234884          0.080950         0.082147
2020 1               3.371483          0.045138         0.046659
     2               3.483068          0.044460         0.045593
     3                    NaN               NaN              NaN
     4                    NaN               NaN              NaN

              freeCashFlowPerShare   P/E ratio  \
Year Quarter
2005 1                    0.020631  127.355535
     2                    0.016971  101.564253
     3                    0.027040  107.195349
     4                    0.008641  105.707692
2006 1                   -0.012927  134.400000
     2                   -0.012927  134.400000
     3                    0.031377  106.341230
     4                    0.062914   74.122611
2007 1                    0.021851  104.131950
     2                    0.038648  129.321538
     3                    0.058293  158.006047
     4                    0.101389  109.662809
2008 1                    0.038840  116.809128
     2                    0.039189  135.822787
     3                    0.152865   51.641691
     4                    0.142036   34.302257
2009 1                    0.028674   59.558990
     2                    0.078488   70.841527
     3                    0.103031   65.862690
     4                    0.209692   57.614192
2010 1                    0.078522   69.319356
     2                    0.160775   76.036028
     3                    0.187250   63.027744

In [569]:
Dividendo1 = data_IncomeStatement.iloc[42]
# Dividendo1[net_rev[~(net_rev.index % 2 == 0)]]
# net_rev = net_rev[~(net_rev.index % 2 == 0)]
Dividendo1[Dividendo1[~(Dividendo1.index % 2 == 0)]]

42
0.645    NaN
0.638    NaN
1.248    NaN
0.545    NaN
0.615    NaN
1.045    NaN
0.585    NaN
0.683    NaN
0.973    NaN
0.418    NaN
0.525    NaN
0.840    NaN
0.355    NaN
0.475    NaN
0.820    NaN
0.463    NaN
0.583    NaN
0.765    NaN
0.320    NaN
0.415    NaN
0.518    NaN
0.267    NaN
0.360    NaN
0.493    NaN
0.333    NaN
0.439    NaN
0.495    NaN
0.278    NaN
0.229    NaN
0.230    NaN
0.125    NaN
0.119    NaN
0.131    NaN
0.048    NaN
0.048    NaN
0.064    NaN
0.043    NaN
0.041    NaN
0.063    NaN
0.033    NaN
0.031    NaN
0.041    NaN
0.019    NaN
0.017    NaN
0.023    NaN
Name: 42, dtype: object

In [693]:
os.getcwd()

'C:\\Users\\User\\github\\Guided-Capstone'

In [ ]:
# Third position would be at index 2, because of zero-indexing.
dec_df['EPS % change'] = dec_df['Earnings Per Share'].pct_change()*100
dec_df.insert(11, 'High PE', (dec_df['High']/dec_df['Earnings Per Share']))
dec_df.insert(12, 'Low PE', (dec_df['Low']/dec_df['Earnings Per Share']))
key_fin_ratios = fa.financial_ratios(ticker, api_key)

#getting dividend per share
Dividend_per_share = (key_fin_ratios.loc['dividendPayoutRatio'][:13].fillna(0)) * (dec_df['Net Income Per Share'])
dividendPayoutRatio = key_fin_ratios.loc['dividendPayoutRatio'][:13].fillna(0).reset_index()
dividendPayoutRatio.rename(columns={"index": "Date", 'dividendPayoutRatio': 'Dividend Payout Ratio'}, inplace = True)
dividendPayoutRatio.sort_values(by=['Date'], inplace=True)
dividendPayoutRatio

#dividend payout ratio
dividendPayoutRatio['Date']= pd.to_datetime(dividendPayoutRatio['Date']).dt.year
dec_df1 = pd.merge(dividendPayoutRatio, dec_df[['Date', 'Net Income Per Share']], how = 'outer')
dec_df.drop('Low PE', axis = 1)
display(dec_df[['Date', 'Net Income Per Share']], dividendPayoutRatio)
Dividend_payout_ratio = key_fin_ratios.loc['dividendPayoutRatio'][:10][::-1]
Dividend_payout_ratio = Dividend_payout_ratio.fillna(0)
Dividend_payout_ratio.reset_index(inplace = True, drop = True)
EPS1 = (dec_df['Earnings Per Share'].fillna(0))[:10]
display(Dividend_payout_ratio ,EPS1)
Dividend_Per_Share = EPS1 * Dividend_payout_ratio

dec_df['Dividend Per Share'] = Dividend_Per_Share
dec_df['Payout as % of earnings'] = dec_df['Dividend Per Share']/dec_df['Earnings Per Share']
dec_df['Payout as % of Earnings'] = (dec_df['Dividend Per Share']/dec_df['Earnings Per Share']) * 100
dec_df['Payout as % of Free Cash Flow'] = (dec_df['Dividend Per Share']/dec_df['freeCashFlowPerShare']) * 100
dec_df['Payout as % of cash flow operations'] = (dec_df['Dividend Per Share']/key_metrics['operatingCashFlowPerShare']) * 100
dec_df['High Dividend Per Share'] =dec_df['Dividend Per Share']/dec_df['High']
dec_df['Low Dividend Per Share'] = dec_df['Dividend Per Share']/dec_df['Low']
capexPerShare = key_metrics['capexPerShare'][:10][::-1]
dec_df['Capex Per Share'] = capexPerShare
dec_df['Capex as % of Sales'] = (dec_df['Capex Per Share'] * dec_df['Sales per Share']) * -100

In [ ]:
# dec_df.drop('Adj Close', axis = 1, inplace = True)

In [ ]:
dec_df

In [ ]:
key_mtrcs

In [ ]:
# dec_df = dec_df[3:14]

In [ ]:
dec_df['Book Value Per Share'] = key_mtrcs['tangibleBookValuePerShare']
dec_df['ROE % (earnings divided by book value)'] = (dec_df['Earnings Per Share'] / dec_df['Book Value Per Share'] ) * 100
dec_df['Cash return on equity %'] = (dec_df['freeCashFlowPerShare'] / dec_df['Book Value Per Share']) * 100
dec_df['Annual book value growth'] = (dec_df['Book Value Per Share'].pct_change()) * 100
dec_df['High Book Value Per Share'] = dec_df['High'] / dec_df['Book Value Per Share']
dec_df['Low Book Value Per Share'] = dec_df['Low'] / dec_df['Book Value Per Share']
dec_df['Clean Book Value'] = key_mtrcs['bookValuePerShare']
dec_df['High Price to Book'] = dec_df['High'] / dec_df['Clean Book Value']
dec_df['Low Price to Book'] =dec_df['Low'] / dec_df['Clean Book Value']
dec_df['High FCFE yield'] = dec_df['freeCashFlowPerShare'] / dec_df['High']
dec_df['Low FCFE yield'] = dec_df['freeCashFlowPerShare'] / dec_df['Low']
dec_df.insert(1, 'Adj Close', price_mean['Adj Close'])
dec_df.insert(22, 'Dividend Yield Per Share', dec_df['Dividend Per Share']/dec_df['Adj Close'])
dec_df.insert(23, 'High Dividend Yield Per Share', dec_df['Dividend Per Share']/dec_df['High'])
dec_df.insert(24, 'Low Dividend Yield Per Share', dec_df['Dividend Per Share']/dec_df['Low'])

In [ ]:
dec_df

In [ ]:
stock_data['Adj Close']

In [ ]:
#attempt at making 3 year average High point
# Three_year_average_high = sum(dec_df['High'][:7:-1]) / 3
# dec_df.insert(1, '3 Year Average High', Three_year_average_high])
# pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [ ]:
price_mean.iloc[:,1]

In [ ]:
dec_df.insert(1, 'Adj Close Avg', price_mean.iloc[:,1])
dec_df

In [ ]:
#defining averages to define the short term, mid term and long term trend
#average highs
dec_df['3 Year Average High'] = dec_df['High'].rolling(3, min_periods=1).mean()
dec_df['5 Year Average High'] = dec_df['High'].rolling(5, min_periods=1).mean()
dec_df['10 Year Average High'] = dec_df['High'].rolling(10, min_periods=1).mean()

#average lows
dec_df['3 Year Average Low'] = dec_df['Low'].rolling(3, min_periods=1).mean()
dec_df['5 Year Average Low'] = dec_df['Low'].rolling(5, min_periods=1).mean()
dec_df['10 Year Average Low'] = dec_df['Low'].rolling(10, min_periods=1).mean()

#average sale/share
dec_df['3 Year Sales Per Share'] = dec_df['Sales per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Sales Per Share'] = dec_df['Sales per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Sales Per Share'] = dec_df['Sales per Share'].rolling(10, min_periods=1).mean()

#average annual sales growth%
dec_df['3 Year %Rev Growth'] = dec_df['%Rev Growth'].rolling(3, min_periods=1).mean()
dec_df['5 Year %Rev Growth'] = dec_df['%Rev Growth'].rolling(5, min_periods=1).mean()
dec_df['10 Year %Rev Growth'] = dec_df['%Rev Growth'].rolling(10, min_periods=1).mean()

#cash flow to net earnings
dec_df['3 Year Cash Flow to Net Earnings'] = dec_df['Cash flow to net earnings ratio'].rolling(3, min_periods=1).mean()
dec_df['5 Year Cash Flow to Net Earnings'] = dec_df['Cash flow to net earnings ratio'].rolling(5, min_periods=1).mean()
dec_df['10 Year Cash Flow to Net Earnings'] = dec_df['Cash flow to net earnings ratio'].rolling(10, min_periods=1).mean()

#high PCF
dec_df['3 Year High PCF'] = dec_df['High PCF'].rolling(3, min_periods=1).mean()
dec_df['5 Year High PCF'] = dec_df['High PCF'].rolling(5, min_periods=1).mean()
dec_df['10 Year High PCF'] = dec_df['High PCF'].rolling(10, min_periods=1).mean()

#low PCF
dec_df['3 Year Low PCF'] = dec_df['High PCF'].rolling(3, min_periods=1).mean()
dec_df['5 Year Low PCF'] = dec_df['High PCF'].rolling(5, min_periods=1).mean()
dec_df['10 Year Low PCF'] = dec_df['High PCF'].rolling(10, min_periods=1).mean()

#earnings per share
dec_df['3 Year EPS'] = dec_df['Earnings Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year EPS'] = dec_df['Earnings Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year EPS'] = dec_df['Earnings Per Share'].rolling(10, min_periods=1).mean()

#annual earnings growth%
dec_df['3 Year Annual Earnings Growth%'] = dec_df['EPS % change'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Earnings Growth%'] = dec_df['EPS % change'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Earnings Growth%'] = dec_df['EPS % change'].rolling(10, min_periods=1).mean()

#dividends per share
dec_df['3 Year Annual Dividend Per Share'] = dec_df['Dividend Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Dividend Per Share'] = dec_df['Dividend Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Dividend Per Share'] = dec_df['Dividend Per Share'].rolling(10, min_periods=1).mean()

#payout as %of earnings
dec_df['3 Year Annual Payout As % Of Earnings'] = dec_df['Payout as % of Earnings'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Payout As % Of Earnings'] = dec_df['Payout as % of Earnings'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Payout As % Of Earnings'] = dec_df['Payout as % of Earnings'].rolling(10, min_periods=1).mean()

#payout as % of cashflow
dec_df['3 Year Annual Payout As % Of Cashflow'] = dec_df['Payout as % of Free Cash Flow'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Payout As % Of Cashflow'] = dec_df['Payout as % of Free Cash Flow'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Payout As % Of Cashflow'] = dec_df['Payout as % of Free Cash Flow'].rolling(10, min_periods=1).mean()

#Payout As % Of Cashflow Operations
dec_df['3 Year Annual Payout As % Of Cashflow Operations'] = dec_df['Payout as % of cash flow operations'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Payout As % Of Cashflow Operations'] = dec_df['Payout as % of cash flow operations'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Payout As % Of Cashflow Operations'] = dec_df['Payout as % of cash flow operations'].rolling(10, min_periods=1).mean()

#High Dividend Yield
dec_df['3 Year Annual High Dividend Yield Per Share'] = dec_df['High Dividend Yield Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual High Dividend Yield Per Share'] = dec_df['High Dividend Yield Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual High Dividend Yield Per Share'] = dec_df['High Dividend Yield Per Share'].rolling(10, min_periods=1).mean()

#Low Dividend Yield
dec_df['3 Year Annual Low Dividend Yield Per Share'] = dec_df['Low Dividend Yield Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Low Dividend Yield Per Share'] = dec_df['Low Dividend Yield Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Low Dividend Yield Per Share'] = dec_df['Low Dividend Yield Per Share'].rolling(10, min_periods=1).mean()

#CAPEX per share
dec_df['3 Year Annual Capex Per Share'] = dec_df['Capex Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Capex Per Share'] = dec_df['Capex Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Capex Per Share'] = dec_df['Capex Per Share'].rolling(10, min_periods=1).mean()

#CAPEX as % of sales
dec_df['3 Year Annual Capex As % Of Sales'] = dec_df['Capex as % of Sales'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Capex As % Of Sales'] = dec_df['Capex as % of Sales'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Capex As % Of Sales'] = dec_df['Capex as % of Sales'].rolling(10, min_periods=1).mean()

#book value per share
dec_df['3 Year Annual Book Value Per Share'] = dec_df['Book Value Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Book Value Per Share'] = dec_df['Book Value Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Book Value Per Share'] = dec_df['Book Value Per Share'].rolling(10, min_periods=1).mean()

# ROE %
dec_df['3 Year Annual ROE%'] = dec_df['ROE % (earnings divided by book value)'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual ROE%'] = dec_df['ROE % (earnings divided by book value)'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual ROE%'] = dec_df['ROE % (earnings divided by book value)'].rolling(10, min_periods=1).mean()

#cash return on equity %
dec_df['3 Year Annual Cash Return On Equity%'] = dec_df['Cash return on equity %'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Cash Return On Equity%'] = dec_df['Cash return on equity %'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Cash Return On Equity%'] = dec_df['Cash return on equity %'].rolling(10, min_periods=1).mean()

#annual book value growth
dec_df['3 Year Annual Book Value Growth'] = dec_df['Annual book value growth'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Book Value Growth'] = dec_df['Annual book value growth'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Book Value Growth'] = dec_df['Annual book value growth'].rolling(10, min_periods=1).mean()

#high BVPS
dec_df['3 Year Annual High Book Value Per Share'] = dec_df['High Book Value Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual High Book Value Per Share'] = dec_df['High Book Value Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual High Book Value Per Share'] = dec_df['High Book Value Per Share'].rolling(10, min_periods=1).mean()

#low BVPS
dec_df['3 Year Annual Low Book Value Per Share'] = dec_df['Low Book Value Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Low Book Value Per Share'] = dec_df['Low Book Value Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Low Book Value Per Share'] = dec_df['Low Book Value Per Share'].rolling(10, min_periods=1).mean()

#clean book value
dec_df['3 Year Annual Clean Book Value'] = dec_df['Clean Book Value'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Clean Book Value'] = dec_df['Clean Book Value'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Clean Book Value'] = dec_df['Clean Book Value'].rolling(10, min_periods=1).mean()

#clean high price to book per share
dec_df['3 Year Annual High Clean Book Value Per Share'] = dec_df['High Book Value Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual High CleanBook Value Per Share'] = dec_df['High Book Value Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual High CleanBook Value Per Share'] = dec_df['High Book Value Per Share'].rolling(10, min_periods=1).mean()

#clean low price to book per share
dec_df['3 Year Annual Low Clean Book Value Per Share'] = dec_df['Low Book Value Per Share'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual Low Clean Book Value Per Share'] = dec_df['Low Book Value Per Share'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Low Clean Book Value Per Share'] = dec_df['Low Book Value Per Share'].rolling(10, min_periods=1).mean()

#cash flow per share
dec_df['3 Year Annual FCF Per Share'] = dec_df['freeCashFlowPerShare'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual FCF Per Share'] = dec_df['freeCashFlowPerShare'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual FCF Per Share'] = dec_df['freeCashFlowPerShare'].rolling(10, min_periods=1).mean()

#high cash flow per share
dec_df['3 Year Annual High FCF Per Share'] = dec_df['High FCFE yield'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual High FCF Per Share'] = dec_df['High FCFE yield'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual High FCF Per Share'] = dec_df['High FCFE yield'].rolling(10, min_periods=1).mean()

#low cash flow per share
dec_df['3 Year Annual Low FCF Per Share'] = dec_df['Low FCFE yield'].rolling(3, min_periods=1).mean()
dec_df['5 Year Annual LowFCF Per Share'] = dec_df['Low FCFE yield'].rolling(5, min_periods=1).mean()
dec_df['10 Year Annual Low FCF Per Share'] = dec_df['Low FCFE yield'].rolling(10, min_periods=1).mean()

print(dec_df.shape)
dec_df

In [ ]:
dec_df.columns

In [ ]:
data_IncomeStatement1 = pd.read_excel('IncomeStatement_full.xlsx', header=None, parse_dates=True)
data_IncomeStatement1

In [ ]:
key_fin_ratios = fa.financial_ratios(ticker, api_key)

In [ ]:
key_fin_ratios

In [ ]:
key_fin_ratios.sort_index()

In [ ]:
# data_IncomeStatement1['Cash dividends declared per share']

In [ ]:
data_IncomeStatement1.iloc[63]

In [ ]:
#getting dividend per share
# Dividend_per_share = (key_fin_ratios.loc['dividendPayoutRatio'][:13].fillna(0)) * (dec_df['Net Income Per Share'])
# dividendPayoutRatio = key_fin_ratios.loc['dividendPayoutRatio'][:13].fillna(0).reset_index()
# dividendPayoutRatio.rename(columns={"index": "Date", 'dividendPayoutRatio': 'Dividend Payout Ratio'}, inplace = True)
# dividendPayoutRatio.sort_values(by=['Date'], inplace=True)
Dividend_per_share = (key_fin_ratios.loc['dividendPayoutRatio'][:13].fillna(0)) * (dec_df['Net Income Per Share'])

dividendPayoutRatio

In [ ]:
# dec_df["High Price/Share"] = pd.merge(dec_df, high_ps, how = 'outer')
# dec_df["Low Price/Share"] = pd.merge(dec_df, low_ps, how = 'outer')
# dec_df

In [ ]:
#defining function to extract requested data - attempting to automate column auto-naming
def get_col(col_name, col_num):
    col_name = data_IncomeStatement.iloc[[10, col_num]]
    col_name.reset_index(inplace=True)
    col_name = col_name.drop('index')
    col_name = col_name.T
    col_name = avg_shares.rename(columns={"Report Date": "Date", 1: col_name})
    col_name.reset_index(drop = True)
    col_name.index = col_name.index.astype('int64') 
    col_name = col_name[~(col_name.index % 2 == 0)]
    #merging net_revenue into main dataframe (dec_df)
    dec_df = pd.merge(dec_df, col_name, how = 'outer')
    return col_name

In [ ]:
dec_df

In [ ]:
#testing bining
data = price_mean.copy()
data['bin'] = pd.cut(dec_df['Adj Close'], bins=[0,30,70,100], labels=["Low", "Mid", "High"])
data

In [ ]:
# pd.set_option('display.float_format', lambda x: '%.2f' % x)
# dec_df['3 Year Average High'] = sum(dec_df['High'][:7:-1]) / 3

In [ ]:
#importing library to convert pdf into excel
import PyPDF2

In [ ]:
#testing differnt source to circumvent need for pdf to excel exchange -uselss becuase of limit
import requests 


# demo= '0198f6647a1a1041971cadc17290951e'
demo = '3c0957c453824c72e29b2e5e35c8b34f'
companies = requests.get(f'https://fmpcloud.io/api/v3/stock-screener?sector=technology&marketCapMoreThan=100000000000&limit=5&apikey={demo}')
companies = companies.json()
print(companies)
technological_companies = []

for item in companies:
  technological_companies.append(item['symbol'])

print(technological_companies)
pricetosales = {}
for item in technological_companies:
    try:
      #annual income statement since we need anual sales
      IS = requests.get(f'https://fmpcloud.io/api/v3/income-statement/{item}?apikey={demo}')
      IS = IS.json()
      Revenue = IS[0]['revenue']
      grossprofitratip = IS[0]['grossProfitRatio']
      #most recent market capitliazation
      MarketCapit = requests.get(f'https://fmpcloud.io/api/v3/market-capitalization/{item}?apikey={demo}')
      MarketCapit = MarketCapit.json()
      MarketCapit = MarketCapit[0]['marketCap']

      #Price to sales
      p_to_sales = MarketCapit/Revenue

      pricetosales[item] = {}
      pricetosales[item]['revenue'] = Revenue
      pricetosales[item]['Gross_Profit_ratio'] = grossprofitratip
      pricetosales[item]['price_to_sales'] = p_to_sales
      pricetosales[item]['Market_Capit'] = MarketCapit
    except:
      pass

print(pricetosales)

In [ ]:
dec_df.columns

In [ ]:
IS[0]

In [ ]:
# #convert dict to DataFrame
price_to_sales_df = pd.DataFrame.from_dict(pricetosales, orient='index')

In [ ]:
price_to_sales_df['ps_average_sector'] = price_to_sales_df['price_to_sales'].mean()
price_to_sales_df['pscompany_vs_averagesector'] = price_to_sales_df['price_to_sales'] - price_to_sales_df['ps_average_sector']
price_to_sales_df['price_as_per_average_industryPS'] = price_to_sales_df['ps_average_sector'] * price_to_sales_df['revenue']
price_to_sales_df['price_difference'] = price_to_sales_df['price_as_per_average_industryPS'] - price_to_sales_df['Market_Capit']

In [ ]:
price_to_sales_df

In [ ]:
# Getting price based on quarters (Now we need to devide DataFrame into Years and Quarters for further processing)
price_mean = df12.pivot_table(index=['year', 'Quarters'], values=['Close', 'High', 'Low'], aggfunc='mean')

In [ ]:
# #List of 1000 companies in US stock exchanges

# full_stock_list = requests.get(f'https://fmpcloud.io/api/v3/rss_feed?apikey=0198f6647a1a1041971cadc17290951e')
# full_stock_list = full_stock_list.json()

# all_companies = []

# for item in full_stock_list:
#     #print(item.keys())
#     all_companies.append(item['ticker'])
# len(all_companies)

In [ ]:

#stock_name = []
#stock_ratios = https://fmpcloud.io/api/v3/ratios/AAPL?apikey=0198f6647a1a1041971cadc17290951e

In [ ]:
# dec_df.drop('Adj Close', axis = 1, inplace = True)

In [ ]:
dec_df2 = dec_df.copy()
dec_df2.T.reset_index(inplace = True)

In [ ]:
dec_df2 = dec_df2.T
dec_df2

In [ ]:
dec_df2.reset_index(inplace = True)

In [ ]:
dec_df2.columns = dec_df2.iloc[0]
dec_df2.drop(0, inplace = True)
dec_df2

In [ ]:
dec_df2 = dec_df2.fillna(0)

In [ ]:
dec_df2.columns

In [ ]:
target = dec_df2[2020][1:4].values

In [ ]:
target

In [ ]:
dec_df2

In [ ]:
# target = dec_df['Low'].values
# data = dec_df.drop('Low', axis = 1).fillna(0).values
data = dec_df2.drop(['Date', 2020], axis = 1)
data

In [ ]:
data = data.values

In [ ]:
target = target.reshape(-1, 1)
target

In [ ]:
# data = data.reshape(-1, 1)
data

In [ ]:
print(data.shape, target.shape)

In [ ]:
import seaborn as sns
with sns.axes_style("white"):
    f, ax = plt.subplots(figsize=(15, 5))
    ax = sns.heatmap(dec_df.corr(), square=True, cmap='RdYlGn')
# correlation = 

plt.plot()
plt.show()

In [ ]:
#train model linear regression(sample) --- Why is it not working?

# from sklearn.model_selection import train_test_split
# import numpy as np
# from sklearn import linear_model
# # n_samples, n_features = 10, 5
# y = target
# X = data

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, 
#                                                     random_state = 21, 
#                                                     stratify = y)
# clf = linear_model.SGDRegressor()
# clf.fit(X_train, y_train)

# # predict price ranges(sample)
# y = y.values.reshape(-1, 1)
# clf.predict(X_test)

# clf.score(X_test, y_test)

In [ ]:
# Import necessary modules
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
y = target
X = data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, 
                                                    random_state = 42)
reg = LinearRegression()
reg.fit(X_train, y_train)
# prediction_space = np.linspace(min(X_train), max(X_train)).reshape(-1, 1)

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
# Compute and print R^2 and RMSE
print("R^2: {}".format(reg.score(X_test, y_test)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: {}".format(rmse))

In [ ]:
dec_df2

In [ ]:
#Which year(s) are these predictions for?
# dec_df2.apply(lambda x: '%.5f' % x, axis=1)
pd.set_option('display.float_format', lambda x: '%.5f' % x)
print([y_pred, dec_df2[2020]])

In [ ]:
# Import the necessary modules
from sklearn.model_selection import cross_val_score


# Create a linear regression object: reg
reg = LinearRegression()

# Compute 5-fold cross-validation scores: cv_scores
cv_scores = cross_val_score(reg, X_train, y_train, cv = 10)

# Print the 5-fold cross-validation scores
print(cv_scores)
print('---------------------------------------------')
print("Average 4-Fold CV Score: {}".format(np.mean(cv_scores)))